"""empty message

Revision ID: 0104dcbbdd86
Revises: 07b79e5fff19
Create Date: 2016-06-12 21:33:58.473136

"""

# revision identifiers, used by Alembic.
revision = '0104dcbbdd86'
down_revision = '07b79e5fff19'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advertiser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('state', sa.Enum('active', 'inactive', name='advartiser_state'), nullable=True),
    sa.Column('default_brand_id', sa.Integer(), nullable=True),
    sa.Column('remarketing_segment_id', sa.Integer(), nullable=True),
    sa.Column('lifetime_budget', sa.Float(), nullable=True),
    sa.Column('lifetime_budget_imps', sa.Integer(), nullable=True),
    sa.Column('daily_budget', sa.Float(), nullable=True),
    sa.Column('daily_budget_imps', sa.Integer(), nullable=True),
    sa.Column('enable_pacing', sa.Boolean(), nullable=True),
    sa.Column('allow_safety_pacing', sa.Boolean(), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('control_pct', sa.Float(), nullable=True),
    sa.Column('last_modified', sa.TIMESTAMP(), nullable=True),
    sa.Column('billing_name', sa.String(), nullable=True),
    sa.Column('billing_phonee', sa.String(), nullable=True),
    sa.Column('billing_address1', sa.String(), nullable=True),
    sa.Column('billing_address2', sa.String(), nullable=True),
    sa.Column('billing_city', sa.String(), nullable=True),
    sa.Column('billing_state', sa.String(), nullable=True),
    sa.Column('use_insertion_orders', sa.Boolean(), nullable=True),
    sa.Column('is_mediated', sa.Boolean(), nullable=True),
    sa.Column('is_malicious', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('advertiser')
    ### end Alembic commands ###
