"""empty message

Revision ID: d15a988a582e
Revises: 0104dcbbdd86
Create Date: 2016-06-12 22:28:51.236167

"""

# revision identifiers, used by Alembic.
revision = 'd15a988a582e'
down_revision = '0104dcbbdd86'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('urls', sa.String(), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('num_creatives', sa.Integer(), nullable=True),
    sa.Column('last_modified', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'advertiser', sa.Column('billing_country', sa.String(), nullable=True))
    op.add_column(u'advertiser', sa.Column('billing_zip', sa.String(), nullable=True))
    op.add_column(u'advertiser', sa.Column('default_currency', sa.String(), nullable=True))
    op.add_column(u'advertiser', sa.Column('time_format', sa.Enum('12-hour', '24-hour', name='time_formats'), nullable=True))
    op.add_column(u'advertiser', sa.Column('timezone', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'advertiser', 'timezone')
    op.drop_column(u'advertiser', 'time_format')
    op.drop_column(u'advertiser', 'default_currency')
    op.drop_column(u'advertiser', 'billing_zip')
    op.drop_column(u'advertiser', 'billing_country')
    op.drop_table('brands')
    ### end Alembic commands ###
