# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 06:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkAnalyticsRaw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', models.TextField(blank=True, null=True)),
                ('csv', models.TextField(blank=True, null=True)),
                ('report_type', models.CharField(blank=True, max_length=50, null=True)),
                ('report_id', models.CharField(blank=True, max_length=100, null=True)),
                ('last_updated', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'NetworkAnalyticsRaw',
            },
        ),
    ]
