# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insertionorder',
            name='billing_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='insertionorder',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='insertionorder',
            name='currency',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='insertionorder',
            name='timezone',
            field=models.TextField(blank=True, null=True),
        ),
    ]
