# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0003_auto_20160625_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api_campaign',
            name='advertiser',
        ),
        migrations.RemoveField(
            model_name='api_sitedomainperformancereport',
            name='advertiser',
        ),
        migrations.RemoveField(
            model_name='api_sitedomainperformancereport',
            name='campaign',
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='API_Campaign',
        ),
        migrations.DeleteModel(
            name='API_SiteDomainPerformanceReport',
        ),
    ]
