# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 06:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('rtb', '0004_auto_20160625_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoAnaliticsReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetch_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('day', models.DateField(blank=True, db_index=True, null=True)),
                ('member_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('advertiser_currency', models.TextField(blank=True, null=True)),
                ('geo_country_code', models.TextField(blank=True, null=True)),
                ('geo_country_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('geo_region_code', models.TextField(blank=True, null=True)),
                ('geo_region_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('geo_dma_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('geo_dma_name', models.TextField(blank=True, null=True)),
                ('geo_country_name', models.TextField(blank=True, null=True)),
                ('geo_region_name', models.TextField(blank=True, null=True)),
                ('geo_country', models.TextField(blank=True, null=True)),
                ('geo_region', models.TextField(blank=True, null=True)),
                ('geo_dma', models.TextField(blank=True, null=True)),
                ('pixel_id', models.IntegerField(blank=True, null=True)),
                ('imps', models.IntegerField(blank=True, null=True)),
                ('clicks', models.IntegerField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('booked_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('cpm', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('total_convs', models.IntegerField(blank=True, null=True)),
                ('convs_rate', models.FloatField(blank=True, null=True)),
                ('post_view_convs', models.IntegerField(blank=True, null=True)),
                ('post_click_convs', models.IntegerField(blank=True, null=True)),
                ('profit', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('click_thru_pct', models.FloatField(blank=True, null=True)),
                ('external_imps', models.IntegerField(blank=True, null=True)),
                ('external_clicks', models.IntegerField(blank=True, null=True)),
                (
                'booked_revenue_adv_curr', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('advertiser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                 to='rtb.Advertiser')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                               to='rtb.Campaign')),
                ('insertion_order',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                   to='rtb.InsertionOrder')),
                ('line_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                to='rtb.LineItem')),
            ],
            options={
                'db_table': 'geo_analytics_report',
            },
        ),
    ]
