# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 21:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0004_auto_20160625_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerGroup',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.TextField(blank=True, db_index=True, null=True)),
                ('name', models.TextField(blank=True, db_index=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'buyer_group',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, db_index=True, null=True)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, db_index=True, null=True)),
                ('entity_id', models.IntegerField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('billing_address_1', models.TextField(blank=True, null=True)),
                ('billing_address_2', models.TextField(blank=True, null=True)),
                ('billing_city', models.TextField(blank=True, null=True)),
                ('billing_region', models.TextField(blank=True, null=True)),
                ('billing_postal_code', models.TextField(blank=True, null=True)),
                ('billing_country', models.TextField(blank=True, null=True)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'developer',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, db_index=True, null=True)),
                ('reselling_description', models.TextField(blank=True, null=True)),
                ('state', models.TextField(blank=True, choices=[(b'active', b'Active'), (b'inactive', b'Inactive')], null=True)),
                ('no_reselling_priority', models.IntegerField(blank=True, null=True)),
                ('entity_type', models.TextField(blank=True, choices=[(b'reseller', b'reseller'), (b'direct', b'direct')], null=True)),
                ('buyer_clearing_fee_pct', models.FloatField(blank=True, null=True)),
                ('app_contract_accepted', models.NullBooleanField()),
                ('interface_domain', models.TextField(blank=True, null=True)),
                ('interface_domain_beta', models.TextField(blank=True, null=True)),
                ('creative_size_minimum_bytes', models.IntegerField(blank=True, null=True)),
                ('creative_size_fee_per_gb', models.FloatField(blank=True, null=True)),
                ('default_ad_profile_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('email_code', models.TextField(blank=True, null=True)),
                ('reselling_exposure', models.TextField(blank=True, choices=[(b'public', b'public'), (b'private', b'private')], null=True)),
                ('reselling_exposed_on', models.TextField(blank=True, null=True)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('standard_sizes', models.TextField(blank=True, null=True)),
                ('buyer_credit_limit', models.FloatField(blank=True, null=True)),
                ('timezone', models.TextField(blank=True, null=True)),
                ('seller_revshare_pct', models.IntegerField(blank=True, null=True)),
                ('dongle', models.TextField(blank=True, null=True)),
                ('platform_exposure', models.TextField(blank=True, choices=[(b'public', b'public'), (b'private', b'private'), (b'hidden', b'hidden')], null=True)),
                ('audit_notify_email', models.TextField(blank=True, null=True)),
                ('sherlock_notify_email', models.TextField(blank=True, null=True)),
                ('domain_blacklist_email', models.TextField(blank=True, null=True)),
                ('contact_email', models.TextField(blank=True, null=True)),
                ('allow_ad_profile_override', models.NullBooleanField()),
                ('default_currency', models.TextField(blank=True, null=True)),
                ('use_insertion_orders', models.NullBooleanField()),
                ('expose_optimization_levers', models.NullBooleanField()),
                ('pops_enabled_UI', models.NullBooleanField()),
                ('default_accept_supply_partner_usersync', models.NullBooleanField()),
                ('default_accept_data_provider_usersync', models.NullBooleanField()),
                ('default_accept_demand_partner_usersync', models.NullBooleanField()),
                ('short_name', models.TextField(blank=True, db_index=True, null=True)),
                ('expose_eap_ecp_placement_settings', models.NullBooleanField()),
                ('daily_imps_verified', models.IntegerField(blank=True, null=True)),
                ('daily_imps_self_audited', models.IntegerField(blank=True, null=True)),
                ('daily_imps_unaudited', models.IntegerField(blank=True, null=True)),
                ('is_iash_compliant', models.NullBooleanField()),
                ('deal_types', models.TextField(blank=True, null=True)),
                ('allow_non_cpm_payment', models.NullBooleanField()),
                ('default_allow_cpc', models.NullBooleanField()),
                ('default_allow_cpa', models.NullBooleanField()),
                ('visibility_profile_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('default_campaign_trust', models.TextField(blank=True, choices=[(b'seller', b'seller'), (b'appnexus', b'appnexus')], null=True)),
                ('default_campaign_allow_unaudited', models.NullBooleanField()),
                ('website_url', models.TextField(blank=True, null=True)),
                ('contract_allows_unaudited', models.NullBooleanField()),
                ('reporting_decimal_type', models.TextField(blank=True, choices=[(b'comma', b'comma'), (b'decimal', b'decimal')], null=True)),
                ('plugins_enabled', models.NullBooleanField()),
                ('enable_click_and_imp_trackers', models.NullBooleanField()),
                ('max_hosted_video_size', models.IntegerField(blank=True, null=True)),
                ('require_facebook_preaudit', models.NullBooleanField()),
                ('pitbull_segment_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('pitbull_segment_value', models.IntegerField(blank=True, null=True)),
                ('default_content_retrieval_timeout_ms', models.IntegerField(blank=True, null=True)),
                ('default_enable_for_mediation', models.NullBooleanField()),
                ('prioritize_margin', models.NullBooleanField()),
                ('mediation_auto_bid_adjustment_enabled', models.NullBooleanField()),
                ('reporting_sync_enabled', models.NullBooleanField()),
                ('native_custom_keys', models.TextField(blank=True, null=True)),
                ('daily_budget', models.DecimalField(decimal_places=10, max_digits=35)),
                ('daily_budget_imps', models.IntegerField(blank=True, null=True)),
                ('default_buyer_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.BuyerGroup')),
                ('developer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Developer')),
            ],
            options={
                'db_table': 'member',
            },
        ),
        migrations.CreateModel(
            name='MemberBrandException',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'member_brand_exception',
            },
        ),
        migrations.CreateModel(
            name='MemberContentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.ContentCategory')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Member')),
            ],
            options={
                'db_table': 'member_content_category',
            },
        ),
        migrations.CreateModel(
            name='MemberCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Country')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Member')),
            ],
            options={
                'db_table': 'member_country',
            },
        ),
        migrations.CreateModel(
            name='MemberFloorOptimisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.NullBooleanField()),
                ('bidder_id', models.IntegerField(blank=True, null=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Member')),
            ],
            options={
                'db_table': 'member_floor_optimization',
            },
        ),
        migrations.CreateModel(
            name='MemberInventoryTrust',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', models.TextField(blank=True, null=True)),
                ('default_is_banned', models.NullBooleanField()),
                ('default_trust', models.TextField(blank=True, choices=[(b'appnexus', b'appnexus'), (b'seller', b'seller')], null=True)),
                ('default_allow_unaudited', models.NullBooleanField()),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Member')),
            ],
            options={
                'db_table': 'member_inventory_trust',
            },
        ),
        migrations.CreateModel(
            name='MemberPlugin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.TextField(blank=True, choices=[(b'available', b'available'), (b'installed', b'installedinstalled'), (b'accept_permissions', b'accept_permissions')], null=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Member')),
            ],
            options={
                'db_table': 'member_plugin',
            },
        ),
        migrations.CreateModel(
            name='MemberThirdpartyPixel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Member')),
                ('thirdparty_pixel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.ThirdPartyPixel')),
            ],
            options={
                'db_table': 'member_thirdparty_pixel',
            },
        ),
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, db_index=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('public_key', models.TextField(blank=True, null=True)),
                ('moreinfo_url', models.TextField(blank=True, null=True)),
                ('log_level_data_fee', models.IntegerField(blank=True, null=True)),
                ('is_available', models.NullBooleanField()),
                ('summary', models.TextField(blank=True, null=True)),
                ('contact_name', models.TextField(blank=True, null=True)),
                ('contact_phone', models.TextField(blank=True, null=True)),
                ('contact_email', models.TextField(blank=True, null=True)),
                ('contact_text', models.TextField(blank=True, null=True)),
                ('author_display_name', models.TextField(blank=True, null=True)),
                ('recommended', models.NullBooleanField()),
                ('featured', models.NullBooleanField()),
                ('has_payment_access', models.NullBooleanField()),
                ('allowed_asset_count', models.IntegerField(blank=True, null=True)),
                ('addendum', models.TextField(blank=True, null=True)),
                ('click_to_install', models.NullBooleanField()),
                ('video_url', models.TextField(blank=True, null=True)),
                ('permissions', models.TextField(blank=True, null=True)),
                ('member_availabilities', models.TextField(blank=True, null=True)),
                ('developer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Developer')),
                ('plugin_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Category')),
            ],
            options={
                'db_table': 'plugin',
            },
        ),
        migrations.CreateModel(
            name='PluginDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, db_index=True, null=True)),
                ('plugin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Plugin')),
            ],
            options={
                'db_table': 'plugin_domain',
            },
        ),
        migrations.CreateModel(
            name='PluginInstance',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, db_index=True, null=True)),
                ('flavor', models.TextField(blank=True, choices=[(b'standalone', b'standalone'), (b'creative_action', b'creative_action'), (b'advertiser_menu', b'advertiser_menu'), (b'publisher_menu', b'publisher_menu'), (b'conversion_pixel', b'conversion_pixel')], null=True)),
                ('iframe_url', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon_url', models.TextField(blank=True, null=True)),
                ('proxy_url', models.TextField(blank=True, null=True)),
                ('plugin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Plugin')),
            ],
            options={
                'db_table': 'plugin_instance',
            },
        ),
        migrations.CreateModel(
            name='SellerMemberGroup',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('display_order', models.IntegerField(blank=True, null=True)),
                ('name', models.TextField(blank=True, db_index=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Member')),
            ],
            options={
                'db_table': 'seller_member_group',
            },
        ),
        migrations.RemoveField(
            model_name='brand',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='clicktracker',
            name='member_id',
        ),
        migrations.RemoveField(
            model_name='creative',
            name='member_id',
        ),
        migrations.RemoveField(
            model_name='cteativetemplate',
            name='member_id',
        ),
        migrations.RemoveField(
            model_name='impressiontracker',
            name='member_id',
        ),
        migrations.RemoveField(
            model_name='label',
            name='member_id',
        ),
        migrations.RemoveField(
            model_name='lineitem',
            name='member_id',
        ),
        migrations.RemoveField(
            model_name='networkanalyticsreport',
            name='buyer_member_id',
        ),
        migrations.RemoveField(
            model_name='networkanalyticsreport',
            name='entity_member_id',
        ),
        migrations.RemoveField(
            model_name='networkanalyticsreport',
            name='seller_member_id',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='member_id',
        ),
        migrations.RemoveField(
            model_name='sitedomainperformancereport',
            name='buyer_member_id',
        ),
        migrations.AlterField(
            model_name='networkanalyticsraw',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberplugin',
            name='plugin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Plugin'),
        ),
        migrations.AddField(
            model_name='memberbrandexception',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Brand'),
        ),
        migrations.AddField(
            model_name='memberbrandexception',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Member'),
        ),
        migrations.AddField(
            model_name='brand',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Company'),
        ),
        migrations.AddField(
            model_name='clicktracker',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Member'),
        ),
        migrations.AddField(
            model_name='creative',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Member'),
        ),
        migrations.AddField(
            model_name='cteativetemplate',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Member'),
        ),
        migrations.AddField(
            model_name='impressiontracker',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Member'),
        ),
        migrations.AddField(
            model_name='label',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Member'),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Member'),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='buyer_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_member_id', to='rtb.Member'),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='entity_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entity_member_id', to='rtb.Member'),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='seller_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_member_id', to='rtb.Member'),
        ),
        migrations.AddField(
            model_name='segment',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Member'),
        ),
        migrations.AddField(
            model_name='sitedomainperformancereport',
            name='buyer_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Member'),
        ),
    ]
