# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0005_auto_20160613_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertiser',
            name='billing_address1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='billing_address2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='billing_city',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='billing_country',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='billing_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='billing_phone',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='billing_state',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='billing_zip',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='default_category',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='default_currency',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='timezone',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advertiserlabel',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advertiserlabel',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='urls',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='bid_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='buyer_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='geo_country',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='inventory_class',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='payment_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='seller_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='size',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='supply_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thirdpartypixel',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
