# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 07:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0005_geoanaliticsreport'),
        ('rtb', '0005_auto_20160630_2135'),
    ]

    operations = [
    ]
