# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0006_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyergroup',
            name='fetch_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='developer',
            name='fetch_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='fetch_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
