# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 21:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0006_auto_20160613_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('member_id', models.IntegerField(blank=True, null=True)),
                ('is_user_associated', models.NullBooleanField()),
                ('is_reporting_enabled', models.NullBooleanField()),
                ('object_type', models.TextField(blank=True, choices=[(b'advertiser', b'Advertiser'), (b'insertion_order', b'Insertion order'), (b'line_item', b'Line item'), (b'campaign', b'Campaign'), (b'publisher', b'Publisher')], default=b'ACTIVE', null=True)),
                ('report_field', models.TextField(blank=True, null=True)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'label',
            },
        ),
        migrations.CreateModel(
            name='LabeledObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insertion_order_id', models.IntegerField(blank=True, null=True)),
                ('line_item_id', models.IntegerField(blank=True, null=True)),
                ('campaign_id', models.IntegerField(blank=True, null=True)),
                ('publisher_id', models.IntegerField(blank=True, null=True)),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'labeled_object',
            },
        ),
        migrations.AddField(
            model_name='advertiser',
            name='is_malicious',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='advertiser',
            name='is_mediated',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='allow_safety_pacing',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='control_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='daily_budget',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='daily_budget_imps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='default_brand_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Brand'),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='enable_pacing',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='lifetime_budget',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='lifetime_budget_imps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='profile_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='remarketing_segment_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='state',
            field=models.TextField(blank=True, choices=[(b'ACTIVE', b'Active'), (b'INACTIVE', b'Inactive')], default=b'ACTIVE', null=True),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='time_format',
            field=models.TextField(blank=True, choices=[(b'12', b'12-Hour'), (b'24', b'24-Hour')], default=b'12', null=True),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='use_insertion_orders',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='advertiserbrand',
            name='advertiser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Advertiser'),
        ),
        migrations.AlterField(
            model_name='advertiserbrand',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Brand'),
        ),
        migrations.AlterField(
            model_name='advertisercategory',
            name='advertiser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Advertiser'),
        ),
        migrations.AlterField(
            model_name='advertisercategory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Category'),
        ),
        migrations.AlterField(
            model_name='advertiserlabel',
            name='advertiser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Advertiser'),
        ),
        migrations.AlterField(
            model_name='advertiserthirdpartypixel',
            name='advertiser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Advertiser'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Category'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='company_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='is_premium',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='brand',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='num_creatives',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brandincountry',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Brand'),
        ),
        migrations.AlterField(
            model_name='brandincountry',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_brand_eligible',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_sensitive',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='requires_whitelist',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='requires_whitelist_on_external',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='adjustment_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='advertiser_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='billing_period_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='billing_period_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='brand_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='buyer_member_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='campaign_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='creative_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='deal_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='entity_member_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='hour',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='imp_type_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='insertion_order_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='line_item_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='media_type_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='pixel_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='placement_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='pub_rule_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='publisher_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='revenue_type_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='seller_member_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='site_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thirdpartypixel',
            name='is_active',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='labeledobject',
            name='advertiser_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Advertiser'),
        ),
        migrations.AddField(
            model_name='labeledobject',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Label'),
        ),
        migrations.AddField(
            model_name='advertiserlabel',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Label'),
        ),
    ]
