# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 10:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0007_auto_20160613_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertiserthirdpartypixel',
            name='thirdparty_pixel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.ThirdPartyPixel'),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='code',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='name',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='profile_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='remarketing_segment_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='advertiserlabel',
            name='name',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='company_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='urls',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='label',
            name='member_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='label',
            name='name',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='label',
            name='object_type',
            field=models.TextField(blank=True, choices=[(b'advertiser', b'Advertiser'), (b'insertion_order', b'Insertion order'), (b'line_item', b'Line item'), (b'campaign', b'Campaign'), (b'publisher', b'Publisher')], db_index=True, default=b'ACTIVE', null=True),
        ),
        migrations.AlterField(
            model_name='labeledobject',
            name='campaign_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='labeledobject',
            name='insertion_order_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='labeledobject',
            name='line_item_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='labeledobject',
            name='publisher_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='networkanalyticsraw',
            name='json',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='adjustment_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='advertiser_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Advertiser'),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='billing_period_end_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='billing_period_start_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='brand_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Brand'),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='buyer_member_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='campaign_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='creative_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='deal_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='entity_member_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='hour',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='imp_type_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='insertion_order_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='line_item_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='media_type_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='pixel_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='placement_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='pub_rule_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='publisher_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='revenue_type_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='seller_member_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='site_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='thirdpartypixel',
            name='name',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterIndexTogether(
            name='networkanalyticsreport',
            index_together=set([('campaign_id', 'hour')]),
        ),
    ]
