# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0007_auto_20160703_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdProfile',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('state', models.TextField(blank=True, choices=[(b'active', b'Active'), (b'inactive', b'Inactive')], null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('default_member_status', models.TextField(blank=True, choices=[(b'case-by-case', b'case-by-case'), (b'trusted', b'trusted'), (b'banned', b'banned')], null=True)),
                ('default_brand_status', models.TextField(blank=True, choices=[(b'trusted', b'trusted'), (b'banned', b'banned')], null=True)),
                ('default_language_status', models.TextField(blank=True, choices=[(b'trusted', b'trusted'), (b'banned', b'banned')], null=True)),
                ('default_ad_server_status', models.TextField(blank=True, choices=[(b'trusted', b'trusted'), (b'banned', b'banned')], null=True)),
                ('default_category_status', models.TextField(blank=True, choices=[(b'trusted', b'trusted'), (b'banned', b'banned')], null=True)),
                ('default_technical_attribute_status', models.TextField(blank=True, choices=[(b'trusted', b'trusted'), (b'banned', b'banned')], null=True)),
                ('default_audit_type', models.TextField(blank=True, choices=[(b'platform', b'platform'), (b'platform_or_self', b'platform_or_self')], null=True)),
                ('total_creative_count', models.IntegerField(blank=True, null=True)),
                ('approved_creative_count', models.IntegerField(blank=True, null=True)),
                ('banned_creative_count', models.IntegerField(blank=True, null=True)),
                ('creatives_approved_percent', models.FloatField(blank=True, null=True)),
                ('creatives_unreviewed', models.IntegerField(blank=True, null=True)),
                ('brands_unreviewed', models.IntegerField(blank=True, null=True)),
                ('exclude_unaudited', models.NullBooleanField()),
                ('exclude_unaudited_direct', models.NullBooleanField()),
                ('audit_type_direct', models.TextField(blank=True, null=True)),
                ('check_attributes_direct', models.NullBooleanField()),
                ('excluded_landing_page_urls', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ad_profile',
            },
        ),
        migrations.CreateModel(
            name='AdProfileAdServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(blank=True, choices=[(b'trusted', b'trusted'), (b'banned', b'banned')], null=True)),
                ('ad_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.AdProfile')),
            ],
            options={
                'db_table': 'ad_profile_ad_server',
            },
        ),
        migrations.CreateModel(
            name='AdProfileBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(blank=True, choices=[(b'trusted', b'trusted'), (b'banned', b'banned')], null=True)),
                ('ad_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.AdProfile')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Brand')),
            ],
            options={
                'db_table': 'ad_profile_brand',
            },
        ),
        migrations.CreateModel(
            name='AdProfileCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(blank=True, choices=[(b'trusted', b'trusted'), (b'banned', b'banned')], null=True)),
                ('ad_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.AdProfile')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Category')),
            ],
            options={
                'db_table': 'ad_profile_category',
            },
        ),
        migrations.CreateModel(
            name='AdProfileCreative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.NullBooleanField()),
                ('ad_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.AdProfile')),
            ],
            options={
                'db_table': 'ad_profile_creative',
            },
        ),
        migrations.CreateModel(
            name='AdProfileFrequencyCaps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_session_imps', models.IntegerField(blank=True, null=True)),
                ('max_day_imps', models.IntegerField(blank=True, null=True)),
                ('min_minutes_per_imp', models.IntegerField(blank=True, null=True)),
                ('cap_user_without_cookie', models.NullBooleanField()),
                ('ad_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.AdProfile')),
            ],
            options={
                'db_table': 'ad_profile_frequency_caps',
            },
        ),
        migrations.CreateModel(
            name='AdProfileFrequencyCapsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Category')),
                ('frequency_caps', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.AdProfileFrequencyCaps')),
            ],
            options={
                'db_table': 'ad_profile_frequency_caps_category',
            },
        ),
        migrations.CreateModel(
            name='AdProfileFrequencyCapsTechnicalAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency_caps', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.AdProfileFrequencyCaps')),
            ],
            options={
                'db_table': 'ad_profile_frequency_caps_technical_attribute',
            },
        ),
        migrations.CreateModel(
            name='AdProfileLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(blank=True, choices=[(b'trusted', b'trusted'), (b'banned', b'banned')], null=True)),
                ('ad_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.AdProfile')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Language')),
            ],
            options={
                'db_table': 'ad_profile_language',
            },
        ),
        migrations.CreateModel(
            name='AdProfileMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(blank=True, choices=[(b'case-by-case', b'case-by-case'), (b'trusted', b'trusted'), (b'banned', b'banned')], null=True)),
                ('audit_type', models.TextField(blank=True, choices=[(b'platform', b'platform'), (b'platform_or_self', b'platform_or_self')], null=True)),
                ('exclude_unaudited', models.NullBooleanField()),
                ('ad_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.AdProfile')),
            ],
            options={
                'db_table': 'ad_profile_member',
            },
        ),
        migrations.CreateModel(
            name='AdProfileTechnicalAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(blank=True, choices=[(b'trusted', b'trusted'), (b'banned', b'banned')], null=True)),
                ('ad_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.AdProfile')),
            ],
            options={
                'db_table': 'ad_profile_technical_attribute',
            },
        ),
        migrations.CreateModel(
            name='AdServer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, db_index=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('declare_to_adx', models.NullBooleanField()),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ad_server',
            },
        ),
        migrations.CreateModel(
            name='AdServerHostname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.TextField(blank=True, db_index=True, null=True)),
                ('ad_server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.AdServer')),
            ],
            options={
                'db_table': 'ad_server_hostname',
            },
        ),
        migrations.CreateModel(
            name='CreativeTechnicalAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'creative_technical_attribute',
            },
        ),
        migrations.CreateModel(
            name='TechnicalAttribute',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, db_index=True, null=True)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'technical_attribute',
            },
        ),
        migrations.RemoveField(
            model_name='creative',
            name='technical_attributes',
        ),
        migrations.AlterField(
            model_name='mediasubtype',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='default_ad_profile_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_ad_profile', to='rtb.AdProfile'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='ad_profile_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.AdProfile'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='default_ad_profile_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publisher_ad_profile', to='rtb.AdProfile'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creativetechnicalattribute',
            name='creative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Creative'),
        ),
        migrations.AddField(
            model_name='creativetechnicalattribute',
            name='technical_attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.TechnicalAttribute'),
        ),
        migrations.AddField(
            model_name='adprofiletechnicalattribute',
            name='technical_attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.TechnicalAttribute'),
        ),
        migrations.AddField(
            model_name='adprofilemember',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Member'),
        ),
        migrations.AddField(
            model_name='adprofilefrequencycapstechnicalattribute',
            name='technical_attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.TechnicalAttribute'),
        ),
        migrations.AddField(
            model_name='adprofilefrequencycaps',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Member'),
        ),
        migrations.AddField(
            model_name='adprofilecreative',
            name='creative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Creative'),
        ),
        migrations.AddField(
            model_name='adprofileadserver',
            name='ad_server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.AdServer'),
        ),
        migrations.AddField(
            model_name='adprofile',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Member'),
        ),
        migrations.AddField(
            model_name='adprofile',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Publisher'),
        ),
        migrations.AddField(
            model_name='creativeadserver',
            name='ad_server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.AdServer'),
        ),
    ]
