# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 14:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0008_auto_20160614_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, db_index=True, null=True)),
                ('media_type_group_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('uses_sizes', models.TextField(blank=True, choices=[(b'always', b'Width and height are required when adding creatives (Banner, Expandable, and Facebook)'), (b'sometimes', b'Width and height are sometimes required when adding creatives (Pop and Text)'), (b'never', b'Width and height are not required when adding creatives (Interstitial, Video, and Skin)')], null=True)),
                ('last_modified', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'media_type',
            },
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'placement',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(blank=True, db_index=True, null=True)),
                ('name', models.TextField(blank=True, db_index=True, null=True)),
                ('state', models.TextField(blank=True, choices=[(b'ACTIVE', b'Active'), (b'INACTIVE', b'Inactive')], null=True)),
                ('expose_domains', models.NullBooleanField()),
                ('enable_cookie_tracking_default', models.NullBooleanField()),
                ('reselling_exposure', models.TextField(blank=True, choices=[(b'public', b'public'), (b'private', b'private')], null=True)),
                ('reselling_exposed_on', models.DateTimeField(default=datetime.datetime.now)),
                ('reselling_name', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_rtb', models.NullBooleanField()),
                ('timezone', models.TextField(blank=True, null=True)),
                ('last_modified', models.DateTimeField(default=datetime.datetime.now)),
                ('max_learn_pct', models.IntegerField(blank=True, null=True)),
                ('learn_bypass_cpm', models.IntegerField(blank=True, null=True)),
                ('ad_quality_advanced_mode_enabled', models.NullBooleanField()),
                ('allow_report_on_default_imps', models.NullBooleanField()),
                ('default_site_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('default_ad_profile_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('billing_dba', models.TextField(blank=True, null=True)),
                ('billing_address1', models.TextField(blank=True, null=True)),
                ('billing_address2', models.TextField(blank=True, null=True)),
                ('billing_city', models.TextField(blank=True, null=True)),
                ('billing_state', models.TextField(blank=True, null=True)),
                ('billing_zip', models.TextField(blank=True, null=True)),
                ('billing_country', models.TextField(blank=True, null=True)),
                ('accept_supply_partner_usersync', models.NullBooleanField()),
                ('accept_demand_partner_usersync', models.NullBooleanField()),
                ('accept_data_provider_usersync', models.NullBooleanField()),
                ('ym_profile_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('allow_cpm_managed', models.NullBooleanField()),
                ('allow_cpm_external', models.NullBooleanField()),
                ('allow_cpa_managed', models.NullBooleanField()),
                ('allow_cpa_external', models.NullBooleanField()),
                ('allow_cpc_managed', models.NullBooleanField()),
                ('allow_cpc_external', models.NullBooleanField()),
                ('managed_cpc_bias_pct', models.IntegerField(blank=True, null=True)),
                ('managed_cpa_bias_pct', models.IntegerField(blank=True, null=True)),
                ('external_cpc_bias_pct', models.IntegerField(blank=True, null=True)),
                ('external_cpa_bias_pct', models.IntegerField(blank=True, null=True)),
                ('is_oo', models.NullBooleanField()),
                ('base_payment_rule_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('base_ad_quality_rule_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('currency', models.TextField(blank=True, null=True)),
                ('visibility_profile_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('billing_internal_user', models.IntegerField(blank=True, null=True)),
                ('cpm_reselling_disabled', models.NullBooleanField()),
                ('cpc_reselling_disabled', models.NullBooleanField()),
                ('platform_ops_notes', models.TextField(blank=True, null=True)),
                ('pitbull_segment_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('pitbull_segment_value', models.IntegerField(blank=True, null=True)),
                ('seller_page_cap_enabled', models.NullBooleanField()),
                ('inventory_relationship', models.TextField(blank=True, choices=[(b'unknown', b'unknown'), (b'owned_operated', b'owned_operated'), (b'direct', b'direct'), (b'indirect_single_publisher', b'indirect_single_publisher'), (b'indirect_multiple_publishers', b'indirect_multiple_publishers')], null=True)),
                ('inventory_source', models.TextField(blank=True, choices=[(b'other', b'other'), (b'rubicon', b'rubicon'), (b'openx', b'openx'), (b'pubmatic', b'pubmatic'), (b'aol', b'aol')], null=True)),
                ('disclosure_status', models.TextField(blank=True, choices=[(b'undisclosed', b'undisclosed'), (b'disclosed_pending', b'disclosed_pending'), (b'disclosed_approved', b'disclosed_approved'), (b'disclosed_rejected', b'disclosed_rejected')], null=True)),
                ('inventory_source_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'publisher',
            },
        ),
        migrations.CreateModel(
            name='PublisherBrandExceptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Brand')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Publisher')),
            ],
            options={
                'db_table': 'publisher_brand_exceptions',
            },
        ),
        migrations.CreateModel(
            name='PublisherContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Publisher')),
            ],
            options={
                'db_table': 'publisher_contact',
            },
        ),
        migrations.CreateModel(
            name='PublisherExternalInventoryCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, db_index=True, null=True)),
                ('code', models.TextField(blank=True, db_index=True, null=True)),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Publisher')),
            ],
            options={
                'db_table': 'publisher_external_inventory_code',
            },
        ),
        migrations.CreateModel(
            name='PublisherLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'publisher_label',
            },
        ),
        migrations.CreateModel(
            name='PublisherPlacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(blank=True, null=True)),
                ('placement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Placement')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Publisher')),
            ],
            options={
                'db_table': 'publisher_placement',
            },
        ),
        migrations.RemoveField(
            model_name='advertiserlabel',
            name='name',
        ),
        migrations.AlterField(
            model_name='label',
            name='object_type',
            field=models.TextField(blank=True, choices=[(b'advertiser', b'Advertiser'), (b'insertion_order', b'Insertion order'), (b'line_item', b'Line item'), (b'campaign', b'Campaign'), (b'publisher', b'Publisher')], db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='networkanalyticsraw',
            name='json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='media_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.MediaType'),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='publisher_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Publisher'),
        ),
        migrations.AddField(
            model_name='publisherlabel',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Label'),
        ),
        migrations.AddField(
            model_name='publisherlabel',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Publisher'),
        ),
    ]
