# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 19:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0008_auto_20160703_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geoanaliticsreport',
            name='member_id',
        ),
        migrations.RemoveField(
            model_name='networkanalyticsreport',
            name='pixel_id',
        ),
        migrations.AddField(
            model_name='geoanaliticsreport',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Member'),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='pixel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.ConversionPixel'),
        ),
        migrations.AlterField(
            model_name='geoanaliticsreport',
            name='pixel_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.ConversionPixel'),
        ),
    ]
