# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 21:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0009_auto_20160614_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, db_index=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_system', models.NullBooleanField()),
                ('type', models.TextField(blank=True, choices=[(b'standard', b'standard'), (b'standard', b'standard')], null=True)),
                ('last_modified', models.DateTimeField()),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.ContentCategory')),
            ],
            options={
                'db_table': 'content_category',
            },
        ),
        migrations.CreateModel(
            name='MediaSubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, db_index=True, null=True)),
                ('last_modified', models.DateTimeField()),
            ],
            options={
                'db_table': 'media_sub_type',
            },
        ),
        migrations.CreateModel(
            name='MediaSubTypeNativeAssets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('native_asset_name', models.TextField(blank=True, choices=[(b'title', b'title'), (b'content', b'content'), (b'description', b'description'), (b'full_text', b'full_text'), (b'context', b'context'), (b'icon_img_url', b'icon_img_url'), (b'main_media', b'main_media'), (b'cta', b'cta'), (b'rating', b'rating'), (b'click_fallback_url', b'click_fallback_url')], null=True)),
                ('min_text_length', models.IntegerField(blank=True, null=True)),
                ('max_text_length', models.IntegerField(blank=True, null=True)),
                ('requirement', models.TextField(blank=True, choices=[(b'required', b'required'), (b'recommended', b'recommended'), (b'optional', b'optional')], null=True)),
                ('media_sub_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.MediaSubType')),
            ],
            options={
                'db_table': 'media_sub_type_native_assets',
            },
        ),
        migrations.CreateModel(
            name='MediaSubTypePermittedSizes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_width', models.IntegerField(blank=True, null=True)),
                ('platform_height', models.IntegerField(blank=True, null=True)),
                ('validate_image_size', models.NullBooleanField()),
                ('scaling_permitted', models.NullBooleanField()),
                ('aspect_ratio_tolerance', models.FloatField(blank=True, null=True)),
                ('min_image_width', models.IntegerField(blank=True, null=True)),
                ('max_image_width', models.IntegerField(blank=True, null=True)),
                ('min_image_height', models.IntegerField(blank=True, null=True)),
                ('max_image_height', models.IntegerField(blank=True, null=True)),
                ('media_sub_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.MediaSubType')),
            ],
            options={
                'db_table': 'media_sub_type_permitted_sizes',
            },
        ),
        migrations.CreateModel(
            name='PlacementContentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.ContentCategory')),
            ],
            options={
                'db_table': 'placement_content_category',
            },
        ),
        migrations.CreateModel(
            name='PlacementMediaSubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_private', models.NullBooleanField()),
                ('last_modified', models.DateTimeField()),
                ('media_sub_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.MediaSubType')),
            ],
            options={
                'db_table': 'placement_media_sub_type',
            },
        ),
        migrations.CreateModel(
            name='PlacementMediaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField()),
            ],
            options={
                'db_table': 'placement_media_type',
            },
        ),
        migrations.CreateModel(
            name='PlacementPopValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pop_freq_times', models.IntegerField(blank=True, null=True)),
                ('pop_freq_duration', models.IntegerField(blank=True, null=True)),
                ('pop_is_prepop', models.NullBooleanField()),
                ('pop_max_width', models.IntegerField(blank=True, null=True)),
                ('pop_max_height', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'placement_pop_values',
            },
        ),
        migrations.RenameField(
            model_name='networkanalyticsreport',
            old_name='media_type_id',
            new_name='media_type',
        ),
        migrations.AddField(
            model_name='placement',
            name='acb_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placement',
            name='ad_profile_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='placement',
            name='apply_floor_to_direct',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='placement',
            name='audit_level',
            field=models.TextField(blank=True, choices=[(b'site', b'site'), (b'placement', b'placement')], null=True),
        ),
        migrations.AddField(
            model_name='placement',
            name='audited',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='placement',
            name='code',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='placement',
            name='code2',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='placement',
            name='code3',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='placement',
            name='content_retrieval_timeout_ms',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='placement',
            name='cost_cpm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placement',
            name='default_calculation_type',
            field=models.TextField(blank=True, choices=[(b'gross', b'gross'), (b'net', b'net')], null=True),
        ),
        migrations.AddField(
            model_name='placement',
            name='default_creative_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='placement',
            name='default_position',
            field=models.TextField(blank=True, choices=[(b'above', b'above the fold'), (b'below', b'below the fold'), (b'unknown', b'unknown')], null=True),
        ),
        migrations.AddField(
            model_name='placement',
            name='default_referrer_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placement',
            name='demand_filter_action',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placement',
            name='enable_for_mediation',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='placement',
            name='exclusive',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='placement',
            name='floor_application_target',
            field=models.TextField(blank=True, choices=[(b'external_only', b'external_only'), (b'external_non_preferred', b'external_non_preferred'), (b'all', b'all')], null=True),
        ),
        migrations.AddField(
            model_name='placement',
            name='height',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='placement',
            name='hide_referer',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='placement',
            name='intended_audience',
            field=models.TextField(blank=True, choices=[(b'general', b'general'), (b'children', b'children'), (b'young_adult', b'young_adult'), (b'mature', b'mature')], null=True),
        ),
        migrations.AddField(
            model_name='placement',
            name='inventory_source_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='placement',
            name='is_prohibited',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='placement',
            name='is_resizable',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='placement',
            name='last_modified',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='placement',
            name='pixel_type',
            field=models.TextField(blank=True, choices=[(b'javascript', b'javascript'), (b'image', b'image')], null=True),
        ),
        migrations.AddField(
            model_name='placement',
            name='pixel_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placement',
            name='pixel_url_secure',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placement',
            name='publisher_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Publisher'),
        ),
        migrations.AddField(
            model_name='placement',
            name='reserve_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placement',
            name='site_audit_status',
            field=models.TextField(blank=True, choices=[(b'self', b'self'), (b'unaudited', b'unaudited')], null=True),
        ),
        migrations.AddField(
            model_name='placement',
            name='site_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='placement',
            name='state',
            field=models.TextField(blank=True, choices=[(b'active', b'Active'), (b'inactive', b'Inactive')], null=True),
        ),
        migrations.AddField(
            model_name='placement',
            name='tag_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placement',
            name='visibility_profile_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='placement',
            name='width',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='state',
            field=models.TextField(blank=True, choices=[(b'active', b'Active'), (b'inactive', b'Inactive')], null=True),
        ),
        migrations.AlterField(
            model_name='mediatype',
            name='last_modified',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='networkanalyticsraw',
            name='last_updated',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='last_modified',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='reselling_exposed_on',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='state',
            field=models.TextField(blank=True, choices=[(b'active', b'Active'), (b'inactive', b'Inactive')], null=True),
        ),
        migrations.AddField(
            model_name='placementpopvalues',
            name='placement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Placement'),
        ),
        migrations.AddField(
            model_name='placementmediatype',
            name='media_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.MediaType'),
        ),
        migrations.AddField(
            model_name='placementmediatype',
            name='placement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Placement'),
        ),
        migrations.AddField(
            model_name='placementmediasubtype',
            name='placement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Placement'),
        ),
        migrations.AddField(
            model_name='placementcontentcategory',
            name='placement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Placement'),
        ),
        migrations.AddField(
            model_name='mediasubtype',
            name='media_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.MediaType'),
        ),
    ]
