# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0009_auto_20160703_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='adprofile',
            name='fetch_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
