# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0010_auto_20160614_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedSegments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.IntegerField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'allowed_segments',
            },
        ),
        migrations.CreateModel(
            name='FilteredAdvertisers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertiser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Advertiser')),
            ],
            options={
                'db_table': 'filtered_advertisers',
            },
        ),
        migrations.CreateModel(
            name='FilteredCampaigns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.IntegerField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'filtered_campaigns',
            },
        ),
        migrations.CreateModel(
            name='FilteredLineItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_item', models.IntegerField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'filtered_line_items',
            },
        ),
        migrations.CreateModel(
            name='InventoryAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('last_activity', models.DateTimeField()),
            ],
            options={
                'db_table': 'inventoryattribute',
            },
        ),
        migrations.CreateModel(
            name='PlacementEstimatedClearPrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clear_price', models.IntegerField(blank=True, null=True)),
                ('average_price', models.IntegerField(blank=True, null=True)),
                ('width', models.FloatField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('verified', models.NullBooleanField()),
            ],
            options={
                'db_table': 'placement_estimated_clear_prices',
            },
        ),
        migrations.CreateModel(
            name='PlacementInventoryAttributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.InventoryAttribute')),
            ],
            options={
                'db_table': 'placement_inventory_attributes',
            },
        ),
        migrations.CreateModel(
            name='PlacementPrivateSizes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'placement_private_sizes',
            },
        ),
        migrations.AddField(
            model_name='placement',
            name='ad_types',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='placement',
            name='content_retrieval_timeout_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='placement',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placementprivatesizes',
            name='placement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Placement'),
        ),
        migrations.AddField(
            model_name='placementinventoryattributes',
            name='placement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Placement'),
        ),
        migrations.AddField(
            model_name='placementestimatedclearprices',
            name='placement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Placement'),
        ),
        migrations.AddField(
            model_name='filteredlineitems',
            name='placement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Placement'),
        ),
        migrations.AddField(
            model_name='filteredcampaigns',
            name='placement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Placement'),
        ),
        migrations.AddField(
            model_name='filteredadvertisers',
            name='placement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Placement'),
        ),
        migrations.AddField(
            model_name='allowedsegments',
            name='placement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Placement'),
        ),
    ]
