# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 19:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0011_auto_20160615_1941'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='inventoryattribute',
            table='inventory_attribute',
        ),
    ]
