# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0011_auto_20160704_2020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placement',
            old_name='ad_profile_id',
            new_name='ad_profile',
        ),
        migrations.RemoveField(
            model_name='advertiser',
            name='profile_id',
        ),
        migrations.RemoveField(
            model_name='member',
            name='default_ad_profile_id',
        ),
        migrations.RemoveField(
            model_name='networkanalyticsreport',
            name='site_id',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='default_ad_profile_id',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='default_site_id',
        ),
        migrations.AddField(
            model_name='advertiser',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_id', to='rtb.Profile'),
        ),
        migrations.AddField(
            model_name='member',
            name='default_ad_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_ad_profile_id', to='rtb.AdProfile'),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Site'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='default_ad_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publisher_ad_profile_id', to='rtb.AdProfile'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='default_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Site'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='advertiser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertiser_id', to='rtb.Advertiser'),
        ),
    ]
