# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0012_auto_20160615_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='PiggybackPixels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(blank=True, null=True)),
                ('pixel_type', models.TextField(blank=True, choices=[(b'js', b'js'), (b'img', b'img')], null=True)),
            ],
            options={
                'db_table': 'piggyback_pixels',
            },
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(blank=True, db_index=True, null=True)),
                ('state', models.TextField(blank=True, choices=[(b'active', b'Active'), (b'inactive', b'Inactive')], null=True)),
                ('short_name', models.TextField(blank=True, db_index=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('member_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('expire_minutes', models.IntegerField(blank=True, null=True)),
                ('enable_rm_piggyback', models.NullBooleanField()),
                ('max_usersync_pixels', models.IntegerField(blank=True, null=True)),
                ('last_modified', models.DateTimeField()),
                ('provider', models.TextField(blank=True, null=True)),
                ('querystring_mapping', models.TextField(blank=True, null=True)),
                ('querystring_mapping_key_value', models.TextField(blank=True, null=True)),
                ('advertiser_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Advertiser')),
                ('parent_segment_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Segment')),
            ],
            options={
                'db_table': 'segment',
            },
        ),
        migrations.AddField(
            model_name='piggybackpixels',
            name='segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Segment'),
        ),
    ]
