# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 21:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0012_auto_20160704_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, db_index=True, null=True)),
                ('state', models.TextField(blank=True, choices=[(b'active', b'Active'), (b'inactive', b'Inactive')], null=True)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Member')),
            ],
            options={
                'db_table': 'broker',
            },
        ),
        migrations.CreateModel(
            name='FilteredPaymentRuleAdvertisers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertiser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Advertiser')),
            ],
            options={
                'db_table': 'filtered_payment_rule_advertisers',
            },
        ),
        migrations.CreateModel(
            name='FilteredPaymentRuleCampaigns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Campaign')),
            ],
            options={
                'db_table': 'filtered_payment_rule_campaigns',
            },
        ),
        migrations.CreateModel(
            name='FilteredPaymentRuleLineItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.LineItem')),
            ],
            options={
                'db_table': 'filtered_payment_rule_line_items',
            },
        ),
        migrations.CreateModel(
            name='PaymentRule',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, db_index=True, null=True)),
                ('code', models.TextField(blank=True, db_index=True, null=True)),
                ('state', models.TextField(blank=True, choices=[(b'active', b'Active'), (b'inactive', b'Inactive')], null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('pricing_type', models.TextField(blank=True, choices=[(b'cpm', b'cpm'), (b'revshare', b'revshare'), (b'dynamic', b'dynamic')], null=True)),
                ('cost_cpm', models.FloatField(blank=True, null=True)),
                ('revshare', models.FloatField(blank=True, null=True)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('timezone', models.TextField(blank=True, null=True)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('buyer_type', models.TextField(blank=True, choices=[(b'direct', b'direct'), (b'rtb', b'rtb'), (b'both', b'both')], null=True)),
                ('max_revshare', models.FloatField(blank=True, null=True)),
                ('apply_cost_on_default', models.NullBooleanField()),
                ('demand_filter_action', models.TextField(blank=True, choices=[(b'include', b'include'), (b'exclude', b'exclude'), (b'default', b'default')], null=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Profile')),
            ],
            options={
                'db_table': 'payment_rule',
            },
        ),
        migrations.CreateModel(
            name='YieldManagementProfile',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.TextField(blank=True, db_index=True, null=True)),
                ('name', models.TextField(blank=True, db_index=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_ym_bias_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('base_ym_floor_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('biases', models.TextField(blank=True, null=True)),
                ('floors', models.TextField(blank=True, null=True)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'yield_management_profile',
            },
        ),
        migrations.CreateModel(
            name='YieldManagementProfileModifiers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(blank=True, choices=[(b'bias-pct', b'bias-pct'), (b'bias-cpm', b'bias-cpm'), (b'floor-pct', b'floor-pct'), (b'floor-cpm', b'floor-cpm')], null=True)),
                ('amount_pct', models.FloatField(blank=True, null=True)),
                ('amount_cpm', models.FloatField(blank=True, null=True)),
                ('technical_attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.TechnicalAttribute')),
                ('yield_management_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.YieldManagementProfile')),
            ],
            options={
                'db_table': 'yield_management_profile_modifiers',
            },
        ),
        migrations.RenameField(
            model_name='impressiontracker',
            old_name='advertiser_id',
            new_name='advertiser',
        ),
        migrations.RemoveField(
            model_name='campaignbrokerfees',
            name='broker_id',
        ),
        migrations.RemoveField(
            model_name='clicktracker',
            name='payment_rule_id',
        ),
        migrations.RemoveField(
            model_name='impressiontracker',
            name='payment_rule_id',
        ),
        migrations.RemoveField(
            model_name='insertionorderbrokerfees',
            name='broker_id',
        ),
        migrations.RemoveField(
            model_name='lineitembroker',
            name='broker_id',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='base_payment_rule_id',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='ym_profile_id',
        ),
        migrations.AlterField(
            model_name='insertionorder',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='buyer_type',
            field=models.TextField(blank=True, choices=[(b'direct', b'direct'), (b'rtb', b'rtb'), (b'both', b'both')], null=True),
        ),
        migrations.AlterField(
            model_name='placement',
            name='demand_filter_action',
            field=models.TextField(blank=True, choices=[(b'include', b'include'), (b'exclude', b'exclude'), (b'default', b'default')], null=True),
        ),
        migrations.AddField(
            model_name='yieldmanagementprofile',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Publisher'),
        ),
        migrations.AddField(
            model_name='filteredpaymentrulelineitems',
            name='payment_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.PaymentRule'),
        ),
        migrations.AddField(
            model_name='filteredpaymentrulecampaigns',
            name='payment_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.PaymentRule'),
        ),
        migrations.AddField(
            model_name='filteredpaymentruleadvertisers',
            name='payment_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.PaymentRule'),
        ),
        migrations.AddField(
            model_name='campaignbrokerfees',
            name='broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Broker'),
        ),
        migrations.AddField(
            model_name='clicktracker',
            name='payment_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.PaymentRule'),
        ),
        migrations.AddField(
            model_name='impressiontracker',
            name='payment_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.PaymentRule'),
        ),
        migrations.AddField(
            model_name='insertionorderbrokerfees',
            name='broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Broker'),
        ),
        migrations.AddField(
            model_name='lineitembroker',
            name='broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Broker'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='base_payment_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.PaymentRule'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='ym_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ym_profile_id', to='rtb.YieldManagementProfile'),
        ),
    ]
