# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 08:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0014_sitedomainperformancereport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitedomainperformancereport',
            old_name='second_level_category_id',
            new_name='second_level_category',
        ),
        migrations.RenameField(
            model_name='sitedomainperformancereport',
            old_name='top_level_category_id',
            new_name='top_level_category',
        ),
    ]
