# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 22:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0014_auto_20160704_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('domain_list_action', models.TextField(blank=True, choices=[(b'include', b'include'), (b'exclude', b'exclude')], null=True)),
                ('domain_list_targets', models.TextField(blank=True, null=True)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'member_profile',
            },
        ),
        migrations.CreateModel(
            name='MemberProfileCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Country')),
                ('member_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.MemberProfile')),
            ],
            options={
                'db_table': 'member_profilecountry',
            },
        ),
    ]
