# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0015_auto_20160616_0801'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignConversionPixel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.IntegerField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'campaign_conversion_pixel',
            },
        ),
        migrations.CreateModel(
            name='ConversionPixel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(blank=True, db_index=True, null=True)),
                ('name', models.TextField(blank=True, db_index=True, null=True)),
                ('state', models.TextField(blank=True, choices=[(b'active', b'Active'), (b'inactive', b'Inactive')], null=True)),
                ('trigger_type', models.TextField(blank=True, choices=[(b'view', b'view'), (b'click', b'click'), (b'hybrid', b'hybrid')], null=True)),
                ('min_minutes_per_conv', models.IntegerField(blank=True, null=True)),
                ('post_view_expire_mins', models.IntegerField(blank=True, null=True)),
                ('post_click_expire_mins', models.IntegerField(blank=True, null=True)),
                ('post_click_value', models.FloatField(blank=True, null=True)),
                ('post_view_value', models.FloatField(blank=True, null=True)),
                ('created_on', models.DateTimeField()),
                ('last_modified', models.DateTimeField()),
                ('advertiser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Advertiser')),
            ],
            options={
                'db_table': 'conversion_pixel',
            },
        ),
        migrations.CreateModel(
            name='LineItemConversionPixel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_item', models.IntegerField(blank=True, db_index=True, null=True)),
                ('conversion_pixel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.ConversionPixel')),
            ],
            options={
                'db_table': 'line_item_conversion_pixel',
            },
        ),
        migrations.CreateModel(
            name='SegmentPiggybackPixels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(blank=True, null=True)),
                ('pixel_type', models.TextField(blank=True, choices=[(b'js', b'js'), (b'img', b'img')], null=True)),
                ('segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Segment')),
            ],
            options={
                'db_table': 'segment_piggyback_pixels',
            },
        ),
        migrations.RenameModel(
            old_name='PiggybackPixels',
            new_name='ConversionPixelPiggybackPixels',
        ),
        migrations.AlterField(
            model_name='conversionpixelpiggybackpixels',
            name='segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.ConversionPixel'),
        ),
        migrations.AlterModelTable(
            name='conversionpixelpiggybackpixels',
            table='conversion_pixel_piggyback_pixels',
        ),
        migrations.AddField(
            model_name='campaignconversionpixel',
            name='conversion_pixel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.ConversionPixel'),
        ),
    ]
