# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 22:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0015_memberprofile_memberprofilecountry'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAdvertiserAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertiser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Advertiser')),
            ],
            options={
                'db_table': 'user_advertiser_access',
            },
        ),
        migrations.CreateModel(
            name='UserPubliserAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Publisher')),
            ],
            options={
                'db_table': 'user_publisher_access',
            },
        ),
        migrations.RemoveField(
            model_name='memberflooroptimisation',
            name='bidder_id',
        ),
        migrations.RemoveField(
            model_name='networkanalyticsreport',
            name='entity_member_id',
        ),
        migrations.RemoveField(
            model_name='platformmember',
            name='bidder_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.AddField(
            model_name='memberflooroptimisation',
            name='bidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.User'),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='entity_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Member'),
        ),
        migrations.AddField(
            model_name='platformmember',
            name='bidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='advertiser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Advertiser'),
        ),
        migrations.AddField(
            model_name='user',
            name='api_login',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='user',
            name='custom_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='decimal_mark',
            field=models.TextField(blank=True, choices=[(b'comma', b'comma'), (b'period', b'period')], null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Member'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_developer',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='user',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Publisher'),
        ),
        migrations.AddField(
            model_name='user',
            name='read_only',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='user',
            name='reporting_decimal_type',
            field=models.TextField(blank=True, choices=[(b'comma', b'comma'), (b'decimal', b'decimal')], null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='send_safety_budget_notifications',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.TextField(blank=True, choices=[(b'active', b'Active'), (b'inactive', b'Inactive')], null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='thousand_separator',
            field=models.TextField(blank=True, choices=[(b'comma', b'comma'), (b'space', b'space'), (b'period', b'period')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.TextField(blank=True, choices=[(b'member', b'member'), (b'bidder', b'bidder'), (b'publisher', b'publisher'), (b'advertiser', b'advertiser'), (b'member_advertiser', b'member_advertiser'), (b'member_publisher', b'member_publisher')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
        migrations.AddField(
            model_name='userpubliseraccess',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.User'),
        ),
        migrations.AddField(
            model_name='useradvertiseraccess',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.User'),
        ),
    ]
