# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0016_auto_20160704_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fetch_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.TextField(blank=True, db_index=True, null=True)),
                ('custom_model_structure', models.TextField(blank=True, choices=[(b'decision_tree', b'decision_tree'), (b'decision_tree', b'decision_tree')], null=True)),
                ('model_output', models.TextField(blank=True, choices=[(b'bid', b'bid'), (b'bid_modifier', b'bid_modifier')], null=True)),
                ('model_text', models.TextField(blank=True, null=True)),
                ('original_text', models.TextField(blank=True, null=True)),
                ('active', models.NullBooleanField()),
                ('last_modified', models.DateTimeField()),
                ('advertiser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Advertiser')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Member')),
            ],
            options={
                'db_table': 'custom_model',
            },
        ),
        migrations.AlterField(
            model_name='campaign',
            name='bid_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.CustomModel'),
        ),
    ]
