# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0017_auto_20160616_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertiser',
            name='state',
            field=models.TextField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive')], null=True),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='time_format',
            field=models.TextField(blank=True, choices=[('12', '12-Hour'), ('24', '24-Hour')], default='12', null=True),
        ),
        migrations.AlterField(
            model_name='contentcategory',
            name='type',
            field=models.TextField(blank=True, choices=[('standard', 'standard'), ('standard', 'standard')], null=True),
        ),
        migrations.AlterField(
            model_name='conversionpixel',
            name='state',
            field=models.TextField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive')], null=True),
        ),
        migrations.AlterField(
            model_name='conversionpixel',
            name='trigger_type',
            field=models.TextField(blank=True, choices=[('view', 'view'), ('click', 'click'), ('hybrid', 'hybrid')], null=True),
        ),
        migrations.AlterField(
            model_name='conversionpixelpiggybackpixels',
            name='pixel_type',
            field=models.TextField(blank=True, choices=[('js', 'js'), ('img', 'img')], null=True),
        ),
        migrations.AlterField(
            model_name='label',
            name='object_type',
            field=models.TextField(blank=True, choices=[('advertiser', 'Advertiser'), ('insertion_order', 'Insertion order'), ('line_item', 'Line item'), ('campaign', 'Campaign'), ('publisher', 'Publisher')], db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='mediasubtypenativeassets',
            name='native_asset_name',
            field=models.TextField(blank=True, choices=[('title', 'title'), ('content', 'content'), ('description', 'description'), ('full_text', 'full_text'), ('context', 'context'), ('icon_img_url', 'icon_img_url'), ('main_media', 'main_media'), ('cta', 'cta'), ('rating', 'rating'), ('click_fallback_url', 'click_fallback_url')], null=True),
        ),
        migrations.AlterField(
            model_name='mediasubtypenativeassets',
            name='requirement',
            field=models.TextField(blank=True, choices=[('required', 'required'), ('recommended', 'recommended'), ('optional', 'optional')], null=True),
        ),
        migrations.AlterField(
            model_name='mediatype',
            name='uses_sizes',
            field=models.TextField(blank=True, choices=[('always', 'Width and height are required when adding creatives (Banner, Expandable, and Facebook)'), ('sometimes', 'Width and height are sometimes required when adding creatives (Pop and Text)'), ('never', 'Width and height are not required when adding creatives (Interstitial, Video, and Skin)')], null=True),
        ),
        migrations.AlterField(
            model_name='placement',
            name='audit_level',
            field=models.TextField(blank=True, choices=[('site', 'site'), ('placement', 'placement')], null=True),
        ),
        migrations.AlterField(
            model_name='placement',
            name='default_calculation_type',
            field=models.TextField(blank=True, choices=[('gross', 'gross'), ('net', 'net')], null=True),
        ),
        migrations.AlterField(
            model_name='placement',
            name='default_position',
            field=models.TextField(blank=True, choices=[('above', 'above the fold'), ('below', 'below the fold'), ('unknown', 'unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='placement',
            name='floor_application_target',
            field=models.TextField(blank=True, choices=[('external_only', 'external_only'), ('external_non_preferred', 'external_non_preferred'), ('all', 'all')], null=True),
        ),
        migrations.AlterField(
            model_name='placement',
            name='intended_audience',
            field=models.TextField(blank=True, choices=[('general', 'general'), ('children', 'children'), ('young_adult', 'young_adult'), ('mature', 'mature')], null=True),
        ),
        migrations.AlterField(
            model_name='placement',
            name='pixel_type',
            field=models.TextField(blank=True, choices=[('javascript', 'javascript'), ('image', 'image')], null=True),
        ),
        migrations.AlterField(
            model_name='placement',
            name='site_audit_status',
            field=models.TextField(blank=True, choices=[('self', 'self'), ('unaudited', 'unaudited')], null=True),
        ),
        migrations.AlterField(
            model_name='placement',
            name='state',
            field=models.TextField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive')], null=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='disclosure_status',
            field=models.TextField(blank=True, choices=[('undisclosed', 'undisclosed'), ('disclosed_pending', 'disclosed_pending'), ('disclosed_approved', 'disclosed_approved'), ('disclosed_rejected', 'disclosed_rejected')], null=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='inventory_relationship',
            field=models.TextField(blank=True, choices=[('unknown', 'unknown'), ('owned_operated', 'owned_operated'), ('direct', 'direct'), ('indirect_single_publisher', 'indirect_single_publisher'), ('indirect_multiple_publishers', 'indirect_multiple_publishers')], null=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='inventory_source',
            field=models.TextField(blank=True, choices=[('other', 'other'), ('rubicon', 'rubicon'), ('openx', 'openx'), ('pubmatic', 'pubmatic'), ('aol', 'aol')], null=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='reselling_exposure',
            field=models.TextField(blank=True, choices=[('public', 'public'), ('private', 'private')], null=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='state',
            field=models.TextField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive')], null=True),
        ),
        migrations.AlterField(
            model_name='segment',
            name='state',
            field=models.TextField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive')], null=True),
        ),
        migrations.AlterField(
            model_name='segmentpiggybackpixels',
            name='pixel_type',
            field=models.TextField(blank=True, choices=[('js', 'js'), ('img', 'img')], null=True),
        ),
        migrations.AlterField(
            model_name='sitedomainperformancereport',
            name='gender',
            field=models.TextField(blank=True, choices=[('m', 'm'), ('f', 'f'), ('u', 'u')], null=True),
        ),
        migrations.AlterField(
            model_name='sitedomainperformancereport',
            name='supply_type',
            field=models.TextField(blank=True, choices=[('web', 'web'), ('mobile_app', 'mobile_app'), ('mobile_web', 'mobile_web')], null=True),
        ),
    ]
