# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 08:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0017_auto_20160705_0817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.TextField(blank=True, db_index=True, null=True)),
                ('name', models.TextField(blank=True, db_index=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.NullBooleanField()),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('package_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('floor_price', models.FloatField(blank=True, null=True)),
                ('currency', models.TextField(blank=True, null=True)),
                ('use_deal_floor', models.NullBooleanField()),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('data_protected', models.NullBooleanField()),
                ('allow_creative_add_on_view', models.NullBooleanField()),
                ('allow_creative_add_on_click', models.NullBooleanField()),
                ('visibility_profile_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('size_preference', models.TextField(blank=True, null=True)),
                ('audit_status_option', models.TextField(blank=True, null=True)),
                ('brand_restrict', models.NullBooleanField()),
                ('category_restrict', models.NullBooleanField()),
                ('language_restrict', models.NullBooleanField()),
                ('technical_attribute_restrict', models.NullBooleanField()),
                ('created_by', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, choices=[(b'1', b'Open Auction'), (b'2', b'Private Auction')], null=True)),
                ('ask_price', models.FloatField(blank=True, null=True)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('payment_type', models.TextField(blank=True, choices=[(b'default', b'default'), (b'cpvm', b'cpvm')], null=True)),
                ('media_preference', models.TextField(blank=True, null=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_id', to='rtb.PlatformMember')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Profile')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_id', to='rtb.PlatformMember')),
            ],
            options={
                'db_table': 'deal',
            },
        ),
        migrations.CreateModel(
            name='DealAllowedMediaSubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField()),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Deal')),
                ('media_sub_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.MediaSubType')),
            ],
            options={
                'db_table': 'deal_allowed_media_sub_type',
            },
        ),
        migrations.CreateModel(
            name='DealAllowedMediaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField()),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Deal')),
                ('media_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.MediaType')),
            ],
            options={
                'db_table': 'deal_allowed_media_type',
            },
        ),
        migrations.CreateModel(
            name='DealBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('override', models.NullBooleanField()),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Brand')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Deal')),
            ],
            options={
                'db_table': 'deal_brand',
            },
        ),
        migrations.CreateModel(
            name='DealCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('override', models.NullBooleanField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Category')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Deal')),
            ],
            options={
                'db_table': 'deal_category',
            },
        ),
        migrations.CreateModel(
            name='DealCreative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(blank=True, choices=[(b'banned', b'banned'), (b'approved', b'approved')], null=True)),
                ('creative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Creative')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Deal')),
            ],
            options={
                'db_table': 'deal_creative',
            },
        ),
        migrations.CreateModel(
            name='DealLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('override', models.NullBooleanField()),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Deal')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Language')),
            ],
            options={
                'db_table': 'deal_language',
            },
        ),
        migrations.CreateModel(
            name='DealTechnicalAtribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('override', models.NullBooleanField()),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Deal')),
                ('technical_attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.TechnicalAttribute')),
            ],
            options={
                'db_table': 'deal_technical_attribute',
            },
        ),
    ]
