# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0017_auto_20160616_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.TextField(blank=True, choices=[(b'active', b'Active'), (b'inactive', b'Inactive')], null=True)),
                ('parent_inactive', models.NullBooleanField()),
                ('code', models.TextField(blank=True, db_index=True, null=True)),
                ('name', models.TextField(blank=True, db_index=True, null=True)),
                ('short_name', models.TextField(blank=True, db_index=True, null=True)),
                ('profile_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('line_item_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('start_date', models.DateTimeField(db_index=True)),
                ('end_date', models.DateTimeField(db_index=True)),
                ('timezone', models.TextField(blank=True, null=True)),
                ('last_modified', models.DateTimeField()),
                ('supply_type', models.TextField(blank=True, null=True)),
                ('supply_type_action', models.TextField(blank=True, null=True)),
                ('inventory_type', models.TextField(blank=True, choices=[(b'real_time', b'real_time'), (b'direct', b'direct'), (b'both', b'both')], null=True)),
                ('roadblock_creatives', models.NullBooleanField()),
                ('roadblock_type', models.TextField(blank=True, choices=[(b'normal_roadblock', b'normal_roadblock'), (b'partial_roadblock', b'partial_roadblock'), (b'exact_roadblock', b'exact_roadblock')], null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('click_url', models.TextField(blank=True, null=True)),
                ('valuation_min_margin_rtb_pct', models.DecimalField(decimal_places=10, max_digits=35)),
                ('remaining_days_eap_multiplier', models.DecimalField(decimal_places=10, max_digits=35)),
                ('first_run', models.DateTimeField()),
                ('last_run', models.DateTimeField()),
                ('alerts', models.TextField(blank=True, null=True)),
                ('creative_distribution_type', models.TextField(blank=True, choices=[(b'even', b'even'), (b'weighted', b'weighted'), (b'ctr-optimized', b'ctr-optimized')], null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('advertiser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Advertiser')),
            ],
            options={
                'db_table': 'campaign',
            },
        ),
        migrations.CreateModel(
            name='CampaignBrokerFees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('payment_type', models.TextField(blank=True, choices=[(b'cpm', b'cpm'), (b'revshare', b'revshare')], null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Campaign')),
            ],
            options={
                'db_table': 'campaign_brocker_fees',
            },
        ),
        migrations.CreateModel(
            name='CampaignCreatives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creative', models.IntegerField(blank=True, db_index=True, null=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Campaign')),
            ],
            options={
                'db_table': 'campaign_creatives',
            },
        ),
        migrations.CreateModel(
            name='CampaignLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Campaign')),
                ('label', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Label')),
            ],
            options={
                'db_table': 'campaign_label',
            },
        ),
        migrations.CreateModel(
            name='CampaignLineItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_item', models.IntegerField(blank=True, db_index=True, null=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Campaign')),
            ],
            options={
                'db_table': 'campaign_line_items',
            },
        ),
        migrations.CreateModel(
            name='OperatingSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, db_index=True, null=True)),
                ('platform_type', models.TextField(blank=True, choices=[(b'web', b'web'), (b'mobile', b'mobile'), (b'both', b'both')], null=True)),
                ('last_modified', models.DateTimeField()),
            ],
            options={
                'db_table': 'operating_system',
            },
        ),
        migrations.CreateModel(
            name='OSFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, db_index=True, null=True)),
                ('last_modified', models.DateTimeField()),
            ],
            options={
                'db_table': 'os_family',
            },
        ),
        migrations.RemoveField(
            model_name='sitedomainperformancereport',
            name='age_bucket_id',
        ),
        migrations.RemoveField(
            model_name='sitedomainperformancereport',
            name='campaign_group',
        ),
        migrations.RemoveField(
            model_name='sitedomainperformancereport',
            name='fold_position_id',
        ),
        migrations.RemoveField(
            model_name='sitedomainperformancereport',
            name='operating_system_id',
        ),
        migrations.AddField(
            model_name='sitedomainperformancereport',
            name='age_bucket',
            field=models.TextField(blank=True, choices=[(b'0', b'unknown'), (b'1', b'13-17'), (b'2', b'18-24'), (b'3', b'25-34'), (b'4', b'35-44'), (b'5', b'45-54'), (b'6', b'55-64'), (b'7', b'65+')], null=True),
        ),
        migrations.AddField(
            model_name='sitedomainperformancereport',
            name='fold_position',
            field=models.TextField(blank=True, choices=[(b'0', b'unknown'), (b'1', b'above'), (b'2', b'below'), (b'11', b'Top FB Ad Slot'), (b'12', b'2nd FB Ad Slot'), (b'13', b'3nd FB Ad Slot'), (b'14', b'4nd FB Ad Slot'), (b'15', b'5nd FB Ad Slot'), (b'16', b'6nd FB Ad Slot'), (b'17', b'7nd FB Ad Slot'), (b'18', b'8nd FB Ad Slot'), (b'19', b'9nd FB Ad Slot'), (b'20', b'10nd FB Ad Slot')], null=True),
        ),
        migrations.AddField(
            model_name='operatingsystem',
            name='os_family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.OSFamily'),
        ),
        migrations.AddField(
            model_name='sitedomainperformancereport',
            name='operating_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.OperatingSystem'),
        ),
    ]
