# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0019_stgsitedomainperformancereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='stgsitedomainperformancereport',
            name='fetch_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
