# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0020_auto_20160705_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentcategory',
            name='fetch_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentcategory',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contentcategory',
            name='type',
            field=models.TextField(blank=True, choices=[(b'standard', b'standard')], null=True),
        ),
    ]
