# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 09:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0020_stgsitedomainperformancereport_fetch_date'),
        ('rtb', '0020_auto_20160618_2026'),
    ]

    operations = [
    ]
