# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 22:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0021_auto_20160706_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='booked_revenue',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='booked_revenue_adv_curr',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='booked_revenue_buying_currency',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='booked_revenue_selling_currency',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='buying_currency',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='click_thru_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='clicks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='commissions',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='commissions_buying_currency',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='commissions_selling_currency',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='convs_per_mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='convs_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='cost_buying_currency',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='cost_including_fees',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='cost_selling_currency',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='cpm',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='cpm_buying_currency',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='cpm_including_fees',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='cpm_selling_currency',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='cpvm',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='ctr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='data_costs',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='data_costs_buying_currency',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='data_costs_selling_currency',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='external_click',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='external_impression',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='imps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='imps_blank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='imps_default_bidder',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='imps_default_error',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='imps_kept',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='imps_psa',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='imps_psa_error',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='imps_resold',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='imps_rtb',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='imps_viewed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='media_cost_pub_curr',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='post_click_convs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='post_click_revenue',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='post_view_convs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='post_view_revenue',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='ppm',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='ppm_buying_currency',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='ppm_including_fees',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='ppm_selling_currency',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='profit_buying_currency',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='profit_including_fees',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='profit_selling_currency',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='reseller_revenue',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='reseller_revenue_buying_currency',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='reseller_revenue_selling_currency',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='revenue',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='revenue_buying_currency',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='revenue_including_fees',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='revenue_selling_currency',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='rpm',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='rpm_buying_currency',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='rpm_including_fees',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='rpm_selling_currency',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='salesperson_for_advertiser',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='salesperson_for_publisher',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='salesrep_for_line_item',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='selling_currency',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='serving_fees',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='serving_fees_buying_currency',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='serving_fees_selling_currency',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='sold_network_rpm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='sold_network_rpm_buying_currency',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='sold_network_rpm_selling_currency',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='sold_publisher_rpm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='total_convs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='total_network_rpm',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='total_network_rpm_buying_currency',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='total_network_rpm_selling_currency',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='total_publisher_rpm',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='trafficker_for_line_item',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='view_measured_imps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='view_measurement_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='view_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='daily_budget',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='geo_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Country'),
        ),
        migrations.AlterField(
            model_name='networkdevicereport',
            name='booked_revenue',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AlterField(
            model_name='networkdevicereport',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AlterField(
            model_name='networkdevicereport',
            name='cpm',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AlterField(
            model_name='networkdevicereport',
            name='ppm',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AlterField(
            model_name='networkdevicereport',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AlterField(
            model_name='networkdevicereport',
            name='reseller_revenue',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AlterField(
            model_name='networkdevicereport',
            name='revenue',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AlterField(
            model_name='networkdevicereport',
            name='rpm',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AlterField(
            model_name='networkdevicereport',
            name='total_publisher_rpm',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AlterField(
            model_name='sitedomainperformancereport',
            name='booked_revenue',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AlterField(
            model_name='sitedomainperformancereport',
            name='cost_ecpa',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AlterField(
            model_name='sitedomainperformancereport',
            name='cost_ecpc',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AlterField(
            model_name='sitedomainperformancereport',
            name='cpm',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AlterField(
            model_name='sitedomainperformancereport',
            name='media_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AlterField(
            model_name='sitedomainperformancereport',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AlterField(
            model_name='sitedomainperformancereport',
            name='profit_ecpm',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True),
        ),
    ]
