# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rtb', '0021_auto_20160706_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='fetch_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='platformmember',
            name='fetch_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='publisher',
            name='fetch_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fetch_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.TextField(blank=True, choices=[(b'member', b'member'), (b'bidder', b'bidder'),
                                                        (b'publisher', b'publisher'), (b'advertiser', b'advertiser'),
                                                        (b'member_advertiser', b'member_advertiser'),
                                                        (b'member_advertiser', b'member_advertiser'),
                                                        (b'member_publisher', b'member_publisher')], null=True),
        ),
    ]
