# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0022_auto_20160706_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkCarrierReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetch_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('day', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('device_type', models.TextField(blank=True, choices=[(b'pc', b'pc'), (b'phone', b'phone'), (b'tablet', b'tablet')], null=True)),
                ('connection_type', models.TextField(blank=True, choices=[(b'Carrier-based', b'Carrier-based'), (b'Wifi or Static', b'Wifi or Static')], null=True)),
                ('entity_member', models.IntegerField(blank=True, db_index=True, null=True)),
                ('buyer_type', models.TextField(blank=True, choices=[(b'Real Time', b'Real Time'), (b'Direct', b'Direct')], null=True)),
                ('seller_type', models.TextField(blank=True, choices=[(b'Real Time', b'Real Time'), (b'Direct', b'Direct')], null=True)),
                ('size', models.TextField(blank=True, null=True)),
                ('payment_type', models.TextField(blank=True, choices=[(b'default', b'default'), (b'cpvm', b'cpvm')], null=True)),
                ('revenue_type_id', models.IntegerField(blank=True, choices=[(b'-1', b'No Payment'), (b'0', b'Flat CPM'), (b'1', b'Cost Plus CPM'), (b'2', b'Cost Plus Margin'), (b'3', b'CPC'), (b'4', b'CPA'), (b'5', b'Revshare'), (b'6', b'Flat Fee'), (b'9', b'CPVM')], null=True)),
                ('bid_type', models.TextField(blank=True, choices=[(b'Manual', b'Manual'), (b'Learn', b'Learn'), (b'Optimized', b'Optimized'), (b'Unknown', b'Unknown'), (b'Optimized give up', b'Optimized give up'), (b'Learn give up', b'Learn give up'), (b'Manual give up', b'Manual give up')], null=True)),
                ('imp_type_id', models.IntegerField(blank=True, choices=[(b'1', b'Blank'), (b'2', b'PSA'), (b'3', b'Default Error'), (b'4', b'Default'), (b'5', b'Kept'), (b'6', b'Resold'), (b'7', b'RTB'), (b'8', b'PSA Error'), (b'9', b'External Impression'), (b'10', b'External Click'), (b'11', b'Insertion')], null=True)),
                ('venue', models.TextField(blank=True, db_index=True, null=True)),
                ('imps', models.IntegerField(blank=True, null=True)),
                ('imps_blank', models.IntegerField(blank=True, null=True)),
                ('imps_psa', models.IntegerField(blank=True, null=True)),
                ('imps_default_error', models.IntegerField(blank=True, null=True)),
                ('imps_default_bidder', models.IntegerField(blank=True, null=True)),
                ('imps_kept', models.IntegerField(blank=True, null=True)),
                ('imps_resold', models.IntegerField(blank=True, null=True)),
                ('imps_rtb', models.IntegerField(blank=True, null=True)),
                ('clicks', models.IntegerField(blank=True, null=True)),
                ('click_thru_pct', models.FloatField(blank=True, null=True)),
                ('ctr', models.FloatField(blank=True, null=True)),
                ('total_convs', models.IntegerField(blank=True, null=True)),
                ('post_view_convs', models.IntegerField(blank=True, null=True)),
                ('post_click_convs', models.IntegerField(blank=True, null=True)),
                ('convs_per_mm', models.FloatField(blank=True, null=True)),
                ('convs_rate', models.FloatField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True)),
                ('cpm', models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True)),
                ('revenue', models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True)),
                ('booked_revenue', models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True)),
                ('reseller_revenue', models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True)),
                ('rpm', models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True)),
                ('profit', models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True)),
                ('ppm', models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True)),
                ('total_publisher_rpm', models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True)),
                ('sold_publisher_rpm', models.FloatField(blank=True, null=True)),
                ('sold_network_rpm', models.FloatField(blank=True, null=True)),
                ('advertiser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Advertiser')),
                ('buyer_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rtb.PlatformMember')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Campaign')),
                ('geo_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Country')),
                ('insertion_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.InsertionOrder')),
                ('line_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.LineItem')),
                ('media_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.MediaType')),
                ('pixel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.ConversionPixel')),
                ('pub_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.AdQualityRule')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Publisher')),
                ('seller_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rtb.PlatformMember')),
            ],
            options={
                'db_table': 'network_carrier_report',
            },
        ),
    ]
