# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0024_auto_20160620_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertiser',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
