# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 07:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('rtb', '0025_mobileappinstance_fetch_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='managed_optimization_zone_id',
            new_name='managed_optimization_zone',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='mobile_app_instance_id',
            new_name='mobile_app_instance',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='primary_content_category_id',
            new_name='primary_content_category',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='rtb_optimization_zone_id',
            new_name='rtb_optimization_zone',
        ),
    ]
