# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0028_api_campaign_api_sitedomainperformancereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='advertiser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Advertiser'),
        ),
        migrations.AddField(
            model_name='profile',
            name='fetch_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_campaign',
            name='allow_safety_pacing',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='api_campaign',
            name='allow_unverified_ecp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_campaign',
            name='base_bid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_campaign',
            name='base_cpm_bid_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_campaign',
            name='bid_margin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_campaign',
            name='bid_model',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_campaign',
            name='bid_modifier_model',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_campaign',
            name='bid_multiplier',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_campaign',
            name='broker_fees',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_campaign',
            name='cadence_modifier_enabled',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_campaign',
            name='cadence_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_campaign',
            name='campaign_modifiers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_campaign',
            name='campaign_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_campaign',
            name='click_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_campaign',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_campaign',
            name='comments',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_campaign',
            name='cpc_goal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_campaign',
            name='cpc_payout',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_campaign',
            name='cpm_bid_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_campaign',
            name='creative_distribution_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_campaign',
            name='creative_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_campaign',
            name='creatives',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_campaign',
            name='daily_budget',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_campaign',
            name='daily_budget_imps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_campaign',
            name='defer_to_li_prediction',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_campaign',
            name='ecp_learn_divisor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_campaign',
            name='enable_pacing',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='api_campaign',
            name='end_date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_campaign',
            name='impression_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_campaign',
            name='inventory_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_campaign',
            name='labels',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_campaign',
            name='last_modified',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_campaign',
            name='learn_override_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_campaign',
            name='learn_threshold',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_campaign',
            name='lifetime_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='api_campaign',
            name='lifetime_budget_imps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_campaign',
            name='lifetime_pacing',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_campaign',
            name='lifetime_pacing_pct',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_campaign',
            name='lifetime_pacing_span',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_campaign',
            name='line_item_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_campaign',
            name='max_bid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_campaign',
            name='max_learn_bid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_campaign',
            name='min_bid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_campaign',
            name='name',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_campaign',
            name='optimization_lookback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_campaign',
            name='optimization_version',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_campaign',
            name='pixels',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_campaign',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_campaign',
            name='projected_learn_events',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_campaign',
            name='remaining_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_campaign',
            name='require_cookie_for_tracking',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_campaign',
            name='roadblock_creatives',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_campaign',
            name='roadblock_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_campaign',
            name='short_name',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_campaign',
            name='start_date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_campaign',
            name='state',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_campaign',
            name='supply_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_campaign',
            name='supply_type_action',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_campaign',
            name='timezone',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_campaign',
            name='total_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api_campaign',
            name='valuation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
