# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0029_auto_20160620_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='insertionorder',
            name='fetch_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='fetch_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='end_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='insertionorder',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
