# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 16:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0030_auto_20160620_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='line_item_id',
            new_name='line_item',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='profile_id',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='insertionorder',
            old_name='advertiser_id',
            new_name='advertiser',
        ),
        migrations.RenameField(
            model_name='lineitem',
            old_name='insertion_order_id',
            new_name='insertion_order',
        ),
        migrations.RenameField(
            model_name='lineitem',
            old_name='profile_id',
            new_name='profile',
        ),
    ]
