# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 06:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0031_auto_20160707_1719'),
        ('rtb', '0023_networkcarrierreport'),
    ]

    operations = [
    ]
