# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0031_auto_20160620_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='remaining_days_eap_multiplier',
            field=models.DecimalField(decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='valuation_min_margin_rtb_pct',
            field=models.DecimalField(decimal_places=10, max_digits=35, null=True),
        ),
    ]
