# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0033_auto_20160620_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='flat_fee_allocation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
