# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0033_networkadvertiseranalyticsreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickTrackerLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'click_tracker_line_item',
            },
        ),
        migrations.CreateModel(
            name='ClickTrackerPaymentRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'click_tracker_payment_rule',
            },
        ),
        migrations.CreateModel(
            name='ClickTrackerPublisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'click_tracker_publisher',
            },
        ),
        migrations.CreateModel(
            name='NetworkAnalyticsFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetch_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('hour', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('day', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('month', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('bid_type', models.TextField(blank=True, choices=[(b'Manual', b'Manual'), (b'Learn', b'Learn'), (b'Optimized', b'Optimized'), (b'Unknown', b'Unknown'), (b'Optimized give up', b'Optimized give up'), (b'Learn give up', b'Learn give up'), (b'Manual give up', b'Manual give up')], null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('imp_type_id', models.IntegerField(blank=True, choices=[(b'1', b'Blank'), (b'2', b'PSA'), (b'3', b'Default Error'), (b'4', b'Default'), (b'5', b'Kept'), (b'6', b'Resold'), (b'7', b'RTB'), (b'8', b'PSA Error'), (b'9', b'External Impression'), (b'10', b'External Click'), (b'11', b'Insertion')], null=True)),
                ('insertion_order_code', models.IntegerField(blank=True, null=True)),
                ('line_item_code', models.IntegerField(blank=True, null=True)),
                ('size', models.TextField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('payment_type', models.TextField(blank=True, choices=[(b'default', b'default'), (b'cpvm', b'cpvm')], null=True)),
                ('revenue_type_id', models.IntegerField(blank=True, choices=[(b'-1', b'No Payment'), (b'0', b'Flat CPM'), (b'1', b'Cost Plus CPM'), (b'2', b'Cost Plus Margin'), (b'3', b'CPC'), (b'4', b'CPA'), (b'5', b'Revshare'), (b'6', b'Flat Fee'), (b'9', b'CPVM')], null=True)),
                ('booked_revenue', models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True)),
                ('booked_revenue_adv_curr', models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True)),
                ('clicks', models.IntegerField(blank=True, null=True)),
                ('commissions', models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True)),
                ('imps', models.IntegerField(blank=True, null=True)),
                ('media_cost', models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True)),
                ('media_cost_pub_curr', models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True)),
                ('network_advertiser_rpm', models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True)),
                ('network_advertiser_rpm_adv_curr', models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True)),
                ('network_resold_rpm', models.FloatField(blank=True, null=True)),
                ('post_click_convs', models.IntegerField(blank=True, null=True)),
                ('post_click_revenue', models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True)),
                ('post_view_convs', models.IntegerField(blank=True, null=True)),
                ('post_view_revenue', models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True)),
                ('ppm', models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True)),
                ('profit', models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True)),
                ('publisher_rpm_publisher_currency', models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True)),
                ('reseller_revenue', models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True)),
                ('revenue', models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True)),
                ('revenue_adv_curr', models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True)),
                ('rpm_adv_curr', models.FloatField(blank=True, null=True)),
                ('serving_fees', models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True)),
                ('total_convs', models.IntegerField(blank=True, null=True)),
                ('total_network_rpm', models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True)),
                ('total_publisher_rpm', models.FloatField(blank=True, null=True)),
                ('imps_viewed', models.IntegerField(blank=True, null=True)),
                ('view_measured_imps', models.IntegerField(blank=True, null=True)),
                ('view_rate', models.FloatField(blank=True, null=True)),
                ('view_measurement_rate', models.FloatField(blank=True, null=True)),
                ('advertiser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Advertiser')),
                ('buyer_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rtb.PlatformMember')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Campaign')),
                ('creative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Creative')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Deal')),
                ('geo_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Country')),
                ('media_subtype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.MediaSubType')),
                ('media_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.MediaType')),
                ('pixel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.ConversionPixel')),
                ('placement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Placement')),
                ('pub_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.AdQualityRule')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Publisher')),
                ('seller_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rtb.PlatformMember')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Site')),
            ],
            options={
                'db_table': 'network_analytics_feed',
            },
        ),
        migrations.RemoveField(
            model_name='clicktracker',
            name='line_item',
        ),
        migrations.RemoveField(
            model_name='clicktracker',
            name='payment_rule',
        ),
        migrations.RemoveField(
            model_name='clicktracker',
            name='publisher',
        ),
        migrations.AddField(
            model_name='clicktracker',
            name='fetch_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='clicktracker',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='clicktracker',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clicktrackerpublisher',
            name='click_tracker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.ClickTracker'),
        ),
        migrations.AddField(
            model_name='clicktrackerpublisher',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Publisher'),
        ),
        migrations.AddField(
            model_name='clicktrackerpaymentrule',
            name='click_tracker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.ClickTracker'),
        ),
        migrations.AddField(
            model_name='clicktrackerpaymentrule',
            name='payment_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.PaymentRule'),
        ),
        migrations.AddField(
            model_name='clicktrackerlineitem',
            name='click_tracker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.ClickTracker'),
        ),
        migrations.AddField(
            model_name='clicktrackerlineitem',
            name='line_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.LineItem'),
        ),
    ]
