# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0034_auto_20160709_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickTrackerFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetch_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('hour', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('day', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('month', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('datetime', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('auction_id', models.BigIntegerField(blank=True, null=True)),
                ('pricing_type', models.TextField(blank=True, choices=[(b'cpm', b'cpm'), (b'revshare', b'revshare'), (b'dynamic', b'dynamic')], null=True)),
                ('site_domain', models.TextField(blank=True, db_index=True, null=True)),
                ('commission_cpm', models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True)),
                ('commission_revshare', models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True)),
                ('media_buy_cost', models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True)),
                ('media_buy_rev_share_pct', models.FloatField(blank=True, null=True)),
                ('revenue_value', models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True)),
                ('advertiser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Advertiser')),
                ('insertion_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.InsertionOrder')),
                ('line_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.LineItem')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Member')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Publisher')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Placement')),
                ('tracker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.ClickTracker')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.User')),
            ],
            options={
                'db_table': 'click_tracker_feed',
            },
        ),
        migrations.AddField(
            model_name='networkanalyticsfeed',
            name='entity_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rtb.Member'),
        ),
        migrations.AddField(
            model_name='networkanalyticsfeed',
            name='external_inv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.PublisherExternalInventoryCode'),
        ),
        migrations.AddField(
            model_name='networkanalyticsfeed',
            name='insertion_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.InsertionOrder'),
        ),
        migrations.AddField(
            model_name='networkanalyticsfeed',
            name='line_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.LineItem'),
        ),
    ]
