# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0034_auto_20160620_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='first_run',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='last_run',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
