# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0036_auto_20160620_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitedomainperformancereport',
            name='fetch_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitedomainperformancereport',
            name='is_remarketing',
            field=models.NullBooleanField(),
        ),
    ]
