# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 08:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0036_auto_20160709_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='clicktracker',
            name='line_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.LineItem'),
        ),
        migrations.AddField(
            model_name='clicktracker',
            name='payment_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.PaymentRule'),
        ),
        migrations.AddField(
            model_name='clicktracker',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Publisher'),
        ),
        migrations.AddField(
            model_name='clicktrackerplacement',
            name='fetch_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='clicktracker',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
        migrations.AlterField(
            model_name='clicktrackerplacement',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
