# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0037_auto_20160710_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clicktracker',
            name='last_modified',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
