# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0037_auto_20160621_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatingsystem',
            name='fetch_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='operatingsystem',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
