# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0039_osfamily_fetch_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osfamily',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
