# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0040_auto_20160621_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatingSystemExtended',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fetch_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.TextField(blank=True, db_index=True, null=True)),
                ('last_modified', models.DateTimeField()),
                ('os_family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.OSFamily')),
            ],
            options={
                'db_table': 'operating_system_extended',
            },
        ),
        migrations.AlterField(
            model_name='sitedomainperformancereport',
            name='operating_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.OperatingSystemExtended'),
        ),
    ]
