# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0041_auto_20160621_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatingsystemextended',
            name='search_string',
            field=models.TextField(blank=True, null=True),
        ),
    ]
