# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rtb', '0042_auto_20160712_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='cteativetemplate',
            name='fetch_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='cteativetemplate',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
