# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0042_operatingsystemextended_search_string'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignCreative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Campaign')),
            ],
            options={
                'db_table': 'campaign_creative',
            },
        ),
        migrations.CreateModel(
            name='Creative',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.TextField(blank=True, db_index=True, null=True)),
                ('code2', models.TextField(blank=True, db_index=True, null=True)),
                ('name', models.TextField(blank=True, db_index=True, null=True)),
                ('type', models.TextField(blank=True, choices=[(b'standard', b'standard'), (b'html', b'html'), (b'video', b'video')], null=True)),
                ('state', models.TextField(blank=True, choices=[(b'active', b'Active'), (b'inactive', b'Inactive')], null=True)),
                ('click_track_result', models.TextField(blank=True, choices=[(b'not_tested', b'not_tested'), (b'passed', b'passed'), (b'failed', b'failed')], null=True)),
                ('custom_macros', models.TextField(blank=True, choices=[(b'not_tested', b'not_tested'), (b'passed', b'passed'), (b'failed', b'failed')], null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('media_url', models.TextField(blank=True, null=True)),
                ('media_url_secure', models.TextField(blank=True, null=True)),
                ('click_url', models.TextField(blank=True, null=True)),
                ('file_name', models.TextField(blank=True, null=True)),
                ('flash_click_variable', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('content_secure', models.TextField(blank=True, null=True)),
                ('original_content', models.TextField(blank=True, null=True)),
                ('original_content_secure', models.TextField(blank=True, null=True)),
                ('macros', models.TextField(blank=True, null=True)),
                ('audit_status', models.TextField(blank=True, null=True)),
                ('audit_feedback', models.TextField(blank=True, null=True)),
                ('allow_audit', models.NullBooleanField()),
                ('ssl_status', models.TextField(blank=True, choices=[(b'disabled', b'disabled'), (b'pending', b'pending'), (b'approved', b'approved'), (b'failed', b'failed')], null=True)),
                ('allow_ssl_audit', models.NullBooleanField()),
                ('google_audit_status', models.TextField(blank=True, choices=[(b'approved', b'approved'), (b'rejected', b'rejected'), (b'pending', b'pending')], null=True)),
                ('google_audit_feedback', models.TextField(blank=True, null=True)),
                ('msft_audit_status', models.TextField(blank=True, choices=[(b'approved', b'approved'), (b'rejected', b'rejected'), (b'pending', b'pending')], null=True)),
                ('msft_audit_feedback', models.TextField(blank=True, null=True)),
                ('facebook_audit_status', models.TextField(blank=True, choices=[(b'pending_pre_audit', b'pending_pre_audit'), (b'rejected_by_pre_audit', b'rejected_by_pre_audit'), (b'approved', b'approved'), (b'rejected', b'rejected'), (b'pending', b'pending')], null=True)),
                ('facebook_audit_feedback', models.TextField(blank=True, null=True)),
                ('is_self_audited', models.NullBooleanField()),
                ('is_expired', models.NullBooleanField()),
                ('is_prohibited', models.NullBooleanField()),
                ('is_hosted', models.NullBooleanField()),
                ('lifetime_budget', models.FloatField(blank=True, null=True)),
                ('lifetime_budget_imps', models.IntegerField(blank=True, null=True)),
                ('daily_budget', models.FloatField(blank=True, null=True)),
                ('daily_budget_imps', models.IntegerField(blank=True, null=True)),
                ('enable_pacing', models.NullBooleanField()),
                ('allow_safety_pacing', models.NullBooleanField()),
                ('track_clicks', models.NullBooleanField()),
                ('flash_backup_content', models.TextField(blank=True, null=True)),
                ('flash_backup_file_name', models.TextField(blank=True, null=True)),
                ('flash_backup_url', models.TextField(blank=True, null=True)),
                ('is_control', models.NullBooleanField()),
                ('created_on', models.DateTimeField()),
                ('last_modified', models.DateTimeField()),
                ('creative_upload_status', models.TextField(blank=True, choices=[(b'pending', b'pending'), (b'processing', b'processing'), (b'completed', b'completed'), (b'failed', b'failed')], null=True)),
                ('backup_upload_status', models.TextField(blank=True, choices=[(b'pending', b'pending'), (b'processing', b'processing'), (b'completed', b'completed'), (b'failed', b'failed')], null=True)),
                ('use_dynamic_click_url', models.NullBooleanField()),
                ('size_in_bytes', models.IntegerField(blank=True, null=True)),
                ('text_title', models.TextField(blank=True, null=True)),
                ('text_description', models.TextField(blank=True, null=True)),
                ('text_display_url', models.TextField(blank=True, null=True)),
                ('click_action', models.TextField(blank=True, choices=[(b'click-to-web', b'click-to-web'), (b'click-to-web', b'click-to-web')], null=True)),
                ('click_target', models.TextField(blank=True, null=True)),
                ('sla', models.IntegerField(blank=True, null=True)),
                ('sla_eta', models.DateTimeField()),
                ('currency', models.TextField(blank=True, null=True)),
                ('first_run', models.DateTimeField()),
                ('last_run', models.DateTimeField()),
                ('content_source', models.TextField(blank=True, null=True)),
                ('flash_backup_url_secure', models.TextField(blank=True, null=True)),
                ('member_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('advertiser_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Advertiser')),
                ('brand_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Brand')),
            ],
            options={
                'db_table': 'creative',
            },
        ),
        migrations.CreateModel(
            name='CreativeAdserver',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('use_type', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('creative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Creative')),
            ],
            options={
                'db_table': 'creative_adserver',
            },
        ),
        migrations.CreateModel(
            name='CreativeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Category')),
                ('creative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Creative')),
            ],
            options={
                'db_table': 'creative_category',
            },
        ),
        migrations.CreateModel(
            name='CreativeFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, db_index=True, null=True)),
                ('last_modified', models.DateTimeField()),
                ('advertiser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Advertiser')),
            ],
            options={
                'db_table': 'creative_folder',
            },
        ),
        migrations.CreateModel(
            name='CreativePixel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('param_1', models.TextField(blank=True, null=True)),
                ('param_2', models.TextField(blank=True, null=True)),
                ('param_3', models.TextField(blank=True, null=True)),
                ('param_4', models.TextField(blank=True, null=True)),
                ('param_5', models.TextField(blank=True, null=True)),
                ('format', models.TextField(blank=True, choices=[(b'raw-js', b'raw-js'), (b'url-html', b'url-html'), (b'url-js', b'url-js'), (b'url-image', b'url-image'), (b'raw-url', b'raw-url')], null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('secure_content', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('secure_url', models.TextField(blank=True, null=True)),
                ('creative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Creative')),
            ],
            options={
                'db_table': 'creative_pixel',
            },
        ),
        migrations.CreateModel(
            name='CreativeSegment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField(blank=True, choices=[(b'add on view', b'add on view'), (b'add on click', b'add on click')], null=True)),
                ('creative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Creative')),
                ('segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Segment')),
            ],
            options={
                'db_table': 'creative_segment',
            },
        ),
        migrations.CreateModel(
            name='CteativeFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, db_index=True, null=True)),
                ('last_modified', models.DateTimeField()),
            ],
            options={
                'db_table': 'creative_format',
            },
        ),
        migrations.CreateModel(
            name='CteativeTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, db_index=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('member_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('is_default', models.NullBooleanField()),
                ('is_archived', models.NullBooleanField()),
                ('content_js', models.TextField(blank=True, null=True)),
                ('content_html', models.TextField(blank=True, null=True)),
                ('content_xml', models.TextField(blank=True, null=True)),
                ('callback_content_html', models.TextField(blank=True, null=True)),
                ('macros', models.TextField(blank=True, null=True)),
                ('last_modified', models.DateTimeField()),
                ('format', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.CteativeFormat')),
                ('media_subtype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.MediaSubType')),
            ],
            options={
                'db_table': 'creative_template',
            },
        ),
        migrations.CreateModel(
            name='PixelTemplate',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, db_index=True, null=True)),
                ('format', models.TextField(blank=True, choices=[(b'raw-js', b'raw-js'), (b'url-html', b'url-html'), (b'url-js', b'url-js'), (b'url-image', b'url-image'), (b'raw-url', b'raw-url')], null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('secure_content', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('secure_url', models.TextField(blank=True, null=True)),
                ('num_required_params', models.IntegerField(blank=True, null=True)),
                ('require_reaudit', models.NullBooleanField()),
            ],
            options={
                'db_table': 'pixel_template',
            },
        ),
        migrations.RenameField(
            model_name='conversionpixelpiggybackpixels',
            old_name='segment',
            new_name='conversion_pixel',
        ),
        migrations.AlterField(
            model_name='allowedsegments',
            name='segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Segment'),
        ),
        migrations.AddField(
            model_name='creativepixel',
            name='pixel_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.PixelTemplate'),
        ),
        migrations.AddField(
            model_name='creative',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.CreativeFolder'),
        ),
        migrations.AddField(
            model_name='creative',
            name='profile_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Profile'),
        ),
        migrations.AddField(
            model_name='creative',
            name='publisher_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Publisher'),
        ),
        migrations.AddField(
            model_name='creative',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.CteativeTemplate'),
        ),
        migrations.AddField(
            model_name='campaigncreative',
            name='creative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Creative'),
        ),
    ]
