# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0043_auto_20160622_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreativeCompetitiveBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Brand')),
            ],
            options={
                'db_table': 'creative_competitive_brand',
            },
        ),
        migrations.CreateModel(
            name='CreativeCompetitiveCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Category')),
            ],
            options={
                'db_table': 'creative_competitive_category',
            },
        ),
        migrations.CreateModel(
            name='CreativeThirdpartyPixel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'creative_thirdparty_pixel',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'language',
            },
        ),
        migrations.RemoveField(
            model_name='campaigncreatives',
            name='campaign',
        ),
        migrations.RenameField(
            model_name='creative',
            old_name='brand_id',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='networkanalyticsreport',
            old_name='advertiser_id',
            new_name='advertiser',
        ),
        migrations.RenameField(
            model_name='networkanalyticsreport',
            old_name='brand_id',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='networkanalyticsreport',
            old_name='campaign_id',
            new_name='campaign',
        ),
        migrations.RenameField(
            model_name='networkanalyticsreport',
            old_name='insertion_order_id',
            new_name='insertion_order',
        ),
        migrations.RenameField(
            model_name='networkanalyticsreport',
            old_name='line_item_id',
            new_name='line_item',
        ),
        migrations.RenameField(
            model_name='networkanalyticsreport',
            old_name='placement_id',
            new_name='placement',
        ),
        migrations.RenameField(
            model_name='networkanalyticsreport',
            old_name='publisher_id',
            new_name='publisher',
        ),
        migrations.RemoveField(
            model_name='lineitemconversionpixel',
            name='conversion_pixel',
        ),
        migrations.RemoveField(
            model_name='placement',
            name='acb_code',
        ),
        migrations.RemoveField(
            model_name='placement',
            name='default_creative_id',
        ),
        migrations.RemoveField(
            model_name='placement',
            name='tag_data',
        ),
        migrations.AddField(
            model_name='creative',
            name='custom_request_template',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creative',
            name='mobile',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creative',
            name='pop_values',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creative',
            name='technical_attributes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creative',
            name='video_attribute',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lineitemconversionpixel',
            name='pixel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.ConversionPixel'),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='creative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Creative'),
        ),
        migrations.AddField(
            model_name='placement',
            name='default_creative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Creative'),
        ),
        migrations.AddField(
            model_name='placement',
            name='toolbar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placement',
            name='use_detected_domain',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='placement',
            name='video',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lineitemcreatives',
            name='creative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Creative'),
        ),
        migrations.AlterIndexTogether(
            name='networkanalyticsreport',
            index_together=set([('campaign', 'hour')]),
        ),
        migrations.DeleteModel(
            name='CampaignCreatives',
        ),
        migrations.AddField(
            model_name='creativethirdpartypixel',
            name='creative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Creative'),
        ),
        migrations.AddField(
            model_name='creativethirdpartypixel',
            name='thirdparty_pixel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.ThirdPartyPixel'),
        ),
        migrations.AddField(
            model_name='creativecompetitivecategory',
            name='creative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Creative'),
        ),
        migrations.AddField(
            model_name='creativecompetitivebrand',
            name='creative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Creative'),
        ),
        migrations.AddField(
            model_name='creative',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Language'),
        ),
    ]
