# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 10:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0044_auto_20160623_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkanalyticsreport',
            name='creative_id',
        ),
    ]
