# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0050_auto_20160712_1854'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='sitedomainperformancereport',
            index_together=set([('advertiser', 'day')]),
        ),
    ]
