# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rtb', '0052_auto_20160714_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='adprofilebrand',
            name='brand_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advertiserbrand',
            name='brand_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brandincountry',
            name='brand_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creative',
            name='brand_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creativecompetitivebrand',
            name='brand_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dealbrand',
            name='brand_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberbrandexception',
            name='brand_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='brand_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publisherbrandexceptions',
            name='brand_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
