# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 07:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('rtb', '0053_auto_20160714_0414'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CteativeFormat',
            new_name='CreativeFormat',
        ),
        migrations.RenameModel(
            old_name='CteativeTemplate',
            new_name='CreativeTemplate',
        ),
    ]
