# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0054_auto_20160715_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversionpixel',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='creative',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='inventoryattribute',
            name='last_activity',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='reselling_exposed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
