# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 09:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0055_auto_20160716_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adprofilebrand',
            name='brand_id',
        ),
        migrations.RemoveField(
            model_name='advertiserbrand',
            name='brand_id',
        ),
        migrations.RemoveField(
            model_name='brandincountry',
            name='brand_id',
        ),
        migrations.RemoveField(
            model_name='creative',
            name='brand_id',
        ),
        migrations.RemoveField(
            model_name='creativecompetitivebrand',
            name='brand_id',
        ),
        migrations.RemoveField(
            model_name='dealbrand',
            name='brand_id',
        ),
        migrations.RemoveField(
            model_name='memberbrandexception',
            name='brand_id',
        ),
        migrations.RemoveField(
            model_name='networkanalyticsreport',
            name='brand_id',
        ),
        migrations.RemoveField(
            model_name='publisherbrandexceptions',
            name='brand_id',
        ),
    ]
