# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 09:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0056_auto_20160716_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='adprofilebrand',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Brand'),
        ),
        migrations.AddField(
            model_name='advertiserbrand',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Brand'),
        ),
        migrations.AddField(
            model_name='brandincountry',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Brand'),
        ),
        migrations.AddField(
            model_name='creative',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Brand'),
        ),
        migrations.AddField(
            model_name='creativecompetitivebrand',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Brand'),
        ),
        migrations.AddField(
            model_name='dealbrand',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Brand'),
        ),
        migrations.AddField(
            model_name='memberbrandexception',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Brand'),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Brand'),
        ),
        migrations.AddField(
            model_name='publisherbrandexceptions',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.Brand'),
        ),
    ]
