# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 12:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0057_auto_20160716_0913'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='sitedomainperformancereport',
            index_together=set([('advertiser', 'day')]),
        ),
    ]
