# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 08:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0060_auto_20160719_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frameworkuser',
            name='apnexus_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtb.User'),
        ),
    ]
