# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 12:52
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rtb', '0061_auto_20160719_0811'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='frameworkuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='frameworkuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='frameworkuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='frameworkuser',
            name='id',
        ),
        migrations.RemoveField(
            model_name='frameworkuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='frameworkuser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='frameworkuser',
            name='username',
        ),
        migrations.AddField(
            model_name='frameworkuser',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
