# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 14:21
from __future__ import unicode_literals

from django.db import migrations

def add_users(apps, schema_editor):
    MyModel = apps.get_model('rtb', 'frameworkuser')
    auth_users = apps.get_model('auth', 'user')
    # admin = auth_users.objects.get(pk=1)
    # if not admin:
    #     raise Exception('You must create superuser first (./manage.py createsuperuser)!')
    MyModel.objects.bulk_create(
        MyModel(user_ptr_id=user.pk,)
        for user in auth_users.objects.all()
    )


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0062_auto_20160723_1252'),
    ]

    operations = [
        migrations.RunPython(add_users, hints={'model_name': "frameworkuser"}, reverse_code=migrations.RunPython.noop),
    ]
