# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0063_auto_20160723_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipUserToAdvertiser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_write', models.BooleanField(default=False)),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rtb.Advertiser')),
            ],
        ),
        migrations.RemoveField(
            model_name='frameworkuser',
            name='apnexusname',
        ),
        migrations.RemoveField(
            model_name='frameworkuser',
            name='permission',
        ),
        migrations.AddField(
            model_name='frameworkuser',
            name='advertisers',
            field=models.ManyToManyField(to='rtb.Advertiser'),
        ),
        migrations.AddField(
            model_name='membershipusertoadvertiser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rtb.FrameworkUser'),
        ),
    ]
