# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import rtb.models.network_analitics_models

def delete_network_analitics(apps, schema_editor):
    MyModel = apps.get_model('rtb', 'networkanalyticsreport_byplacement')
    MyModel.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0064_auto_20160801_0840'),
    ]

    operations = [
        migrations.RunPython(delete_network_analitics, hints={'model_name': "networkanalyticsreport_byplacement"},
                             reverse_code=migrations.RunPython.noop),
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('country_code', models.IntegerField(blank=True, null=True)),
                ('country_name', models.TextField(blank=True, null=True)),
                ('codes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'carrier',
            },
        ),
        migrations.CreateModel(
            name='NetworkCarrierReport_Simple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetch_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('day', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('carrier_name', models.TextField(blank=True, null=True)),
                ('device_type', models.TextField(blank=True, choices=[(b'pc', b'pc'), (b'phone', b'phone'), (b'tablet', b'tablet')], null=True)),
                ('connection_type', models.TextField(blank=True, choices=[(b'Carrier-based', b'Carrier-based'), (b'Wifi or Static', b'Wifi or Static')], null=True)),
                ('seller_member_name', models.TextField(blank=True, null=True)),
                ('seller_type', models.TextField(blank=True, choices=[(b'Real Time', b'Real Time'), (b'Direct', b'Direct')], null=True)),
                ('campaign_name', models.TextField(blank=True, null=True)),
                ('media_type_name', models.TextField(blank=True, null=True)),
                ('size', models.TextField(blank=True, null=True)),
                ('geo_country_name', models.TextField(blank=True, null=True)),
                ('publisher_name', models.TextField(blank=True, null=True)),
                ('imps', models.IntegerField(blank=True, null=True)),
                ('clicks', models.IntegerField(blank=True, null=True)),
                ('total_convs', models.IntegerField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True)),
                ('campaign', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Campaign')),
                ('carrier_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Carrier')),
                ('geo_country', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Country')),
                ('media_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.MediaType')),
                ('publisher', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Publisher')),
                ('seller_member', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.PlatformMember')),
            ],
            options={
                'db_table': 'network_carrier_report_simple',
            },
            bases=(models.Model, rtb.models.network_analitics_models.PostLoadMix),
        ),
        migrations.CreateModel(
            name='NetworkDeviceReport_Simple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetch_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('day', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('device_make_name', models.TextField(blank=True, null=True)),
                ('device_model_name', models.TextField(blank=True, null=True)),
                ('device_type', models.TextField(blank=True, choices=[(b'pc', b'pc'), (b'phone', b'phone'), (b'tablet', b'tablet')], null=True)),
                ('connection_type', models.TextField(blank=True, choices=[(b'Carrier-based', b'Carrier-based'), (b'Wifi or Static', b'Wifi or Static')], null=True)),
                ('operating_system_name', models.TextField(blank=True, null=True)),
                ('browser_name', models.TextField(blank=True, null=True)),
                ('seller_member_name', models.TextField(blank=True, null=True)),
                ('seller_type', models.TextField(blank=True, choices=[(b'Real Time', b'Real Time'), (b'Direct', b'Direct')], null=True)),
                ('campaign_name', models.TextField(blank=True, null=True)),
                ('media_type_name', models.TextField(blank=True, null=True)),
                ('geo_country_name', models.TextField(blank=True, null=True)),
                ('publisher_name', models.TextField(blank=True, null=True)),
                ('imps', models.IntegerField(blank=True, null=True)),
                ('clicks', models.IntegerField(blank=True, null=True)),
                ('total_convs', models.IntegerField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True)),
                ('browser', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Browser')),
                ('campaign', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Campaign')),
                ('device_make', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.DeviceMake')),
                ('device_model', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.DeviceModel')),
                ('geo_country', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Country')),
                ('media_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.MediaType')),
                ('operating_system', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.OperatingSystemExtended')),
                ('publisher', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Publisher')),
                ('seller_member', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='rtb.PlatformMember')),
            ],
            options={
                'db_table': 'network_device_report_simple',
            },
            bases=(models.Model, rtb.models.network_analitics_models.PostLoadMix),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport_byplacement',
            name='campaign_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport_byplacement',
            name='creative',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Creative'),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport_byplacement',
            name='creative_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport_byplacement',
            name='placement_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport_byplacement',
            name='publisher',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Publisher'),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport_byplacement',
            name='publisher_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport_byplacement',
            name='seller_member_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport_byplacement',
            name='size',
            field=models.TextField(blank=True, null=True),
        ),
    ]
