# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 19:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0064_auto_20160723_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membershipusertoadvertiser',
            old_name='user',
            new_name='frameworkuser',
        ),
        migrations.RemoveField(
            model_name='frameworkuser',
            name='advertisers',
        ),
        migrations.AlterModelTable(
            name='membershipusertoadvertiser',
            table='rtb_membershipusertoadvertiser',
        ),
    ]
