# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0065_auto_20160805_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='frameworkuser',
            name='permission',
            field=models.TextField(blank=True, null=True),
        ),
    ]
