# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0065_auto_20160723_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='frameworkuser',
            name='advertisers',
            field=models.ManyToManyField(through='rtb.MembershipUserToAdvertiser', to='rtb.Advertiser'),
        ),
    ]
