# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-12 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0066_frameworkuser_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='frameworkuser',
            name='use_appnexus_rights',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='frameworkuser',
            name='permission',
            field=models.CharField(blank=True, choices=[(b'adminFull', b'Super user'), (b'adminRead', b'Staff user'), (b'userFull', b'User with write rights'), (b'userRead', b'Ordinary user')], max_length=10, null=True),
        ),
    ]
