# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 12:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rtb', '0066_frameworkuser_advertisers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='frameworkuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='frameworkuser',
            name='user_ptr',
        ),
        migrations.AddField(
            model_name='frameworkuser',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True,
                                       serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
