# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-13 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0067_auto_20160812_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='frameworkuser',
            name='appnexus_can_write',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='frameworkuser',
            name='permission',
            field=models.CharField(blank=True, choices=[(b'adminfull', b'Super user'), (b'adminread', b'Staff user'), (b'userfull', b'User with write rights'), (b'userread', b'Ordinary user')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.TextField(blank=True, choices=[(b'member', b'member'), (b'bidder', b'bidder'), (b'publisher', b'publisher'), (b'advertiser', b'advertiser'), (b'member_advertiser', b'member_advertiser'), (b'member_publisher', b'member_publisher')], null=True),
        ),
    ]
