# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-13 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0069_auto_20160813_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkanalyticsreport_byplacement',
            name='site',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Site'),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport_byplacement',
            name='site_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
