# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 10:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0070_auto_20160813_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adprofile',
            name='member',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Member'),
        ),
        migrations.AlterField(
            model_name='adprofile',
            name='publisher',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Publisher'),
        ),
        migrations.AlterField(
            model_name='adprofileadserver',
            name='ad_profile',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.AdProfile'),
        ),
        migrations.AlterField(
            model_name='adprofileadserver',
            name='ad_server',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.AdServer'),
        ),
        migrations.AlterField(
            model_name='adprofilebrand',
            name='ad_profile',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.AdProfile'),
        ),
        migrations.AlterField(
            model_name='adprofilebrand',
            name='brand',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Brand'),
        ),
        migrations.AlterField(
            model_name='adprofilecategory',
            name='ad_profile',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.AdProfile'),
        ),
        migrations.AlterField(
            model_name='adprofilecategory',
            name='category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Category'),
        ),
        migrations.AlterField(
            model_name='adprofilecreative',
            name='ad_profile',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.AdProfile'),
        ),
        migrations.AlterField(
            model_name='adprofilecreative',
            name='creative',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Creative'),
        ),
        migrations.AlterField(
            model_name='adprofilefrequencycaps',
            name='ad_profile',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.AdProfile'),
        ),
        migrations.AlterField(
            model_name='adprofilefrequencycaps',
            name='member',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Member'),
        ),
        migrations.AlterField(
            model_name='adprofilefrequencycapscategory',
            name='category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Category'),
        ),
        migrations.AlterField(
            model_name='adprofilefrequencycapscategory',
            name='frequency_caps',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.AdProfileFrequencyCaps'),
        ),
        migrations.AlterField(
            model_name='adprofilefrequencycapstechnicalattribute',
            name='frequency_caps',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.AdProfileFrequencyCaps'),
        ),
        migrations.AlterField(
            model_name='adprofilefrequencycapstechnicalattribute',
            name='technical_attribute',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.TechnicalAttribute'),
        ),
        migrations.AlterField(
            model_name='adprofilelanguage',
            name='ad_profile',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.AdProfile'),
        ),
        migrations.AlterField(
            model_name='adprofilelanguage',
            name='language',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Language'),
        ),
        migrations.AlterField(
            model_name='adprofilemember',
            name='ad_profile',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.AdProfile'),
        ),
        migrations.AlterField(
            model_name='adprofilemember',
            name='member',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Member'),
        ),
        migrations.AlterField(
            model_name='adprofiletechnicalattribute',
            name='ad_profile',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.AdProfile'),
        ),
        migrations.AlterField(
            model_name='adprofiletechnicalattribute',
            name='technical_attribute',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.TechnicalAttribute'),
        ),
        migrations.AlterField(
            model_name='adqualityrule',
            name='ad_profile',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.AdProfile'),
        ),
        migrations.AlterField(
            model_name='adqualityrule',
            name='member',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Member'),
        ),
        migrations.AlterField(
            model_name='adqualityrule',
            name='profile',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Profile'),
        ),
        migrations.AlterField(
            model_name='adqualityrule',
            name='publisher',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Publisher'),
        ),
        migrations.AlterField(
            model_name='adserverhostname',
            name='ad_server',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.AdServer'),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='profile',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile_id', to='rtb.Profile'),
        ),
        migrations.AlterField(
            model_name='advertiserbrand',
            name='advertiser',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Advertiser'),
        ),
        migrations.AlterField(
            model_name='advertiserbrand',
            name='brand',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Brand'),
        ),
        migrations.AlterField(
            model_name='advertisercategory',
            name='advertiser',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Advertiser'),
        ),
        migrations.AlterField(
            model_name='advertisercategory',
            name='category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Category'),
        ),
        migrations.AlterField(
            model_name='advertiserlabel',
            name='advertiser',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Advertiser'),
        ),
        migrations.AlterField(
            model_name='advertiserlabel',
            name='label',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Label'),
        ),
        migrations.AlterField(
            model_name='advertiserthirdpartypixel',
            name='advertiser',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Advertiser'),
        ),
        migrations.AlterField(
            model_name='advertiserthirdpartypixel',
            name='thirdparty_pixel',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.ThirdPartyPixel'),
        ),
        migrations.AlterField(
            model_name='allowedsegments',
            name='placement',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Placement'),
        ),
        migrations.AlterField(
            model_name='allowedsegments',
            name='segment',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Segment'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Category'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Company'),
        ),
        migrations.AlterField(
            model_name='brandincountry',
            name='brand',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Brand'),
        ),
        migrations.AlterField(
            model_name='brandincountry',
            name='category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Category'),
        ),
        migrations.AlterField(
            model_name='broker',
            name='member',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Member'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='advertiser',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Advertiser'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='bid_model',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.CustomModel'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='line_item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.LineItem'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='profile',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Profile'),
        ),
        migrations.AlterField(
            model_name='campaignbrokerfees',
            name='broker',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Broker'),
        ),
        migrations.AlterField(
            model_name='campaignbrokerfees',
            name='campaign',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Campaign'),
        ),
        migrations.AlterField(
            model_name='campaignconversionpixel',
            name='campaign',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Campaign'),
        ),
        migrations.AlterField(
            model_name='campaignconversionpixel',
            name='conversion_pixel',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.ConversionPixel'),
        ),
        migrations.AlterField(
            model_name='campaigncreative',
            name='campaign',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Campaign'),
        ),
        migrations.AlterField(
            model_name='campaigncreative',
            name='creative',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Creative'),
        ),
        migrations.AlterField(
            model_name='campaignlabel',
            name='campaign',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Campaign'),
        ),
        migrations.AlterField(
            model_name='campaignlabel',
            name='label',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Label'),
        ),
        migrations.AlterField(
            model_name='campaignlineitems',
            name='campaign',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Campaign'),
        ),
        migrations.AlterField(
            model_name='campaignlineitems',
            name='line_item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.LineItem'),
        ),
        migrations.AlterField(
            model_name='clicktracker',
            name='advertiser',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Advertiser'),
        ),
        migrations.AlterField(
            model_name='clicktracker',
            name='line_item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.LineItem'),
        ),
        migrations.AlterField(
            model_name='clicktracker',
            name='member',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Member'),
        ),
        migrations.AlterField(
            model_name='clicktracker',
            name='payment_rule',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.PaymentRule'),
        ),
        migrations.AlterField(
            model_name='clicktracker',
            name='publisher',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Publisher'),
        ),
        migrations.AlterField(
            model_name='clicktrackerfeed',
            name='advertiser',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Advertiser'),
        ),
        migrations.AlterField(
            model_name='clicktrackerfeed',
            name='insertion_order',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.InsertionOrder'),
        ),
        migrations.AlterField(
            model_name='clicktrackerfeed',
            name='line_item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.LineItem'),
        ),
        migrations.AlterField(
            model_name='clicktrackerfeed',
            name='member',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Member'),
        ),
        migrations.AlterField(
            model_name='clicktrackerfeed',
            name='publisher',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Publisher'),
        ),
        migrations.AlterField(
            model_name='clicktrackerfeed',
            name='tag',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Placement'),
        ),
        migrations.AlterField(
            model_name='clicktrackerfeed',
            name='tracker',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.ClickTracker'),
        ),
        migrations.AlterField(
            model_name='clicktrackerfeed',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.User'),
        ),
        migrations.AlterField(
            model_name='clicktrackerlineitem',
            name='click_tracker',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.ClickTracker'),
        ),
        migrations.AlterField(
            model_name='clicktrackerlineitem',
            name='line_item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.LineItem'),
        ),
        migrations.AlterField(
            model_name='clicktrackerpaymentrule',
            name='click_tracker',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.ClickTracker'),
        ),
        migrations.AlterField(
            model_name='clicktrackerpaymentrule',
            name='payment_rule',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.PaymentRule'),
        ),
        migrations.AlterField(
            model_name='clicktrackerplacement',
            name='click_tracker',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.ClickTracker'),
        ),
        migrations.AlterField(
            model_name='clicktrackerplacement',
            name='placement',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Placement'),
        ),
        migrations.AlterField(
            model_name='clicktrackerpublisher',
            name='click_tracker',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.ClickTracker'),
        ),
        migrations.AlterField(
            model_name='clicktrackerpublisher',
            name='publisher',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Publisher'),
        ),
        migrations.AlterField(
            model_name='contentcategory',
            name='parent_category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.ContentCategory'),
        ),
        migrations.AlterField(
            model_name='conversionpixel',
            name='advertiser',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Advertiser'),
        ),
        migrations.AlterField(
            model_name='conversionpixelpiggybackpixels',
            name='conversion_pixel',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.ConversionPixel'),
        ),
        migrations.AlterField(
            model_name='creative',
            name='advertiser',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Advertiser'),
        ),
        migrations.AlterField(
            model_name='creative',
            name='brand',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Brand'),
        ),
        migrations.AlterField(
            model_name='creative',
            name='folder',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.CreativeFolder'),
        ),
        migrations.AlterField(
            model_name='creative',
            name='language',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Language'),
        ),
        migrations.AlterField(
            model_name='creative',
            name='member',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Member'),
        ),
        migrations.AlterField(
            model_name='creative',
            name='profile',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Profile'),
        ),
        migrations.AlterField(
            model_name='creative',
            name='publisher',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Publisher'),
        ),
        migrations.AlterField(
            model_name='creative',
            name='template',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.CreativeTemplate'),
        ),
        migrations.AlterField(
            model_name='creativeadserver',
            name='ad_server',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.AdServer'),
        ),
        migrations.AlterField(
            model_name='creativeadserver',
            name='creative',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Creative'),
        ),
        migrations.AlterField(
            model_name='creativecategory',
            name='category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Category'),
        ),
        migrations.AlterField(
            model_name='creativecategory',
            name='creative',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Creative'),
        ),
        migrations.AlterField(
            model_name='creativecompetitivebrand',
            name='brand',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Brand'),
        ),
        migrations.AlterField(
            model_name='creativecompetitivebrand',
            name='creative',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Creative'),
        ),
        migrations.AlterField(
            model_name='creativecompetitivecategory',
            name='category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Category'),
        ),
        migrations.AlterField(
            model_name='creativecompetitivecategory',
            name='creative',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Creative'),
        ),
        migrations.AlterField(
            model_name='creativefolder',
            name='advertiser',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Advertiser'),
        ),
        migrations.AlterField(
            model_name='creativepixel',
            name='creative',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Creative'),
        ),
        migrations.AlterField(
            model_name='creativepixel',
            name='pixel_template',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.PixelTemplate'),
        ),
        migrations.AlterField(
            model_name='creativesegment',
            name='creative',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Creative'),
        ),
        migrations.AlterField(
            model_name='creativesegment',
            name='segment',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Segment'),
        ),
        migrations.AlterField(
            model_name='creativetechnicalattribute',
            name='creative',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Creative'),
        ),
        migrations.AlterField(
            model_name='creativetechnicalattribute',
            name='technical_attribute',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.TechnicalAttribute'),
        ),
        migrations.AlterField(
            model_name='creativetemplate',
            name='format',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.CreativeFormat'),
        ),
        migrations.AlterField(
            model_name='creativetemplate',
            name='media_subtype',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.MediaSubType'),
        ),
        migrations.AlterField(
            model_name='creativetemplate',
            name='member',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Member'),
        ),
        migrations.AlterField(
            model_name='creativethirdpartypixel',
            name='creative',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Creative'),
        ),
        migrations.AlterField(
            model_name='creativethirdpartypixel',
            name='thirdparty_pixel',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.ThirdPartyPixel'),
        ),
        migrations.AlterField(
            model_name='custommodel',
            name='advertiser',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Advertiser'),
        ),
        migrations.AlterField(
            model_name='custommodel',
            name='member',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Member'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='buyer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='buyer_id', to='rtb.PlatformMember'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='profile',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Profile'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='seller',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='seller_id', to='rtb.PlatformMember'),
        ),
        migrations.AlterField(
            model_name='dealallowedmediasubtype',
            name='deal',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Deal'),
        ),
        migrations.AlterField(
            model_name='dealallowedmediasubtype',
            name='media_sub_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.MediaSubType'),
        ),
        migrations.AlterField(
            model_name='dealallowedmediatype',
            name='deal',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Deal'),
        ),
        migrations.AlterField(
            model_name='dealallowedmediatype',
            name='media_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.MediaType'),
        ),
        migrations.AlterField(
            model_name='dealbrand',
            name='brand',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Brand'),
        ),
        migrations.AlterField(
            model_name='dealbrand',
            name='deal',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Deal'),
        ),
        migrations.AlterField(
            model_name='dealcategory',
            name='category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Category'),
        ),
        migrations.AlterField(
            model_name='dealcategory',
            name='deal',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Deal'),
        ),
        migrations.AlterField(
            model_name='dealcreative',
            name='creative',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Creative'),
        ),
        migrations.AlterField(
            model_name='dealcreative',
            name='deal',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Deal'),
        ),
        migrations.AlterField(
            model_name='deallanguage',
            name='deal',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Deal'),
        ),
        migrations.AlterField(
            model_name='deallanguage',
            name='language',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Language'),
        ),
        migrations.AlterField(
            model_name='dealtechnicalatribute',
            name='deal',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Deal'),
        ),
        migrations.AlterField(
            model_name='dealtechnicalatribute',
            name='technical_attribute',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.TechnicalAttribute'),
        ),
        migrations.AlterField(
            model_name='devicemakecodes',
            name='device_make',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.DeviceMake'),
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='device_make',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.DeviceMake'),
        ),
        migrations.AlterField(
            model_name='devicemodelcodes',
            name='device_model',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.DeviceModel'),
        ),
        migrations.AlterField(
            model_name='filteredadvertisers',
            name='advertiser',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Advertiser'),
        ),
        migrations.AlterField(
            model_name='filteredadvertisers',
            name='placement',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Placement'),
        ),
        migrations.AlterField(
            model_name='filteredcampaigns',
            name='campaign',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Campaign'),
        ),
        migrations.AlterField(
            model_name='filteredcampaigns',
            name='placement',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Placement'),
        ),
        migrations.AlterField(
            model_name='filteredlineitems',
            name='line_item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.LineItem'),
        ),
        migrations.AlterField(
            model_name='filteredlineitems',
            name='placement',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Placement'),
        ),
        migrations.AlterField(
            model_name='filteredpaymentruleadvertisers',
            name='advertiser',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Advertiser'),
        ),
        migrations.AlterField(
            model_name='filteredpaymentruleadvertisers',
            name='payment_rule',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.PaymentRule'),
        ),
        migrations.AlterField(
            model_name='filteredpaymentrulecampaigns',
            name='campaign',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Campaign'),
        ),
        migrations.AlterField(
            model_name='filteredpaymentrulecampaigns',
            name='payment_rule',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.PaymentRule'),
        ),
        migrations.AlterField(
            model_name='filteredpaymentrulelineitems',
            name='line_item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.LineItem'),
        ),
        migrations.AlterField(
            model_name='filteredpaymentrulelineitems',
            name='payment_rule',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.PaymentRule'),
        ),
        migrations.AlterField(
            model_name='geoanaliticsreport',
            name='advertiser',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Advertiser'),
        ),
        migrations.AlterField(
            model_name='geoanaliticsreport',
            name='campaign',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Campaign'),
        ),
        migrations.AlterField(
            model_name='geoanaliticsreport',
            name='geo_dma',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.DemographicArea'),
        ),
        migrations.AlterField(
            model_name='geoanaliticsreport',
            name='insertion_order',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.InsertionOrder'),
        ),
        migrations.AlterField(
            model_name='geoanaliticsreport',
            name='line_item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.LineItem'),
        ),
        migrations.AlterField(
            model_name='geoanaliticsreport',
            name='member',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Member'),
        ),
        migrations.AlterField(
            model_name='geoanaliticsreport',
            name='pixel',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.ConversionPixel'),
        ),
        migrations.AlterField(
            model_name='impressiontracker',
            name='advertiser',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Advertiser'),
        ),
        migrations.AlterField(
            model_name='impressiontracker',
            name='line_item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.LineItem'),
        ),
        migrations.AlterField(
            model_name='impressiontracker',
            name='member',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Member'),
        ),
        migrations.AlterField(
            model_name='impressiontracker',
            name='payment_rule',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.PaymentRule'),
        ),
        migrations.AlterField(
            model_name='impressiontracker',
            name='publisher',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Publisher'),
        ),
        migrations.AlterField(
            model_name='impressiontrackerplacement',
            name='impression_tracker',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.ImpressionTracker'),
        ),
        migrations.AlterField(
            model_name='impressiontrackerplacement',
            name='placement',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Placement'),
        ),
        migrations.AlterField(
            model_name='insertionorder',
            name='advertiser',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Advertiser'),
        ),
        migrations.AlterField(
            model_name='insertionorderbrokerfees',
            name='broker',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Broker'),
        ),
        migrations.AlterField(
            model_name='insertionorderbrokerfees',
            name='insertion_order',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.InsertionOrder'),
        ),
        migrations.AlterField(
            model_name='insertionorderlabel',
            name='insertion_order',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.InsertionOrder'),
        ),
        migrations.AlterField(
            model_name='insertionorderlabel',
            name='line_item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.LineItem'),
        ),
        migrations.AlterField(
            model_name='label',
            name='member',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Member'),
        ),
        migrations.AlterField(
            model_name='labeledobject',
            name='advertiser',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Advertiser'),
        ),
        migrations.AlterField(
            model_name='labeledobject',
            name='campaign',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Campaign'),
        ),
        migrations.AlterField(
            model_name='labeledobject',
            name='insertion_order',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.InsertionOrder'),
        ),
        migrations.AlterField(
            model_name='labeledobject',
            name='label',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Label'),
        ),
        migrations.AlterField(
            model_name='labeledobject',
            name='line_item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.LineItem'),
        ),
        migrations.AlterField(
            model_name='labeledobject',
            name='publisher',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Publisher'),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='advertiser',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Advertiser'),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='insertion_order',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.InsertionOrder'),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='member',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Member'),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='profile',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Profile'),
        ),
        migrations.AlterField(
            model_name='lineitembroker',
            name='broker',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Broker'),
        ),
        migrations.AlterField(
            model_name='lineitembroker',
            name='line_item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.LineItem'),
        ),
        migrations.AlterField(
            model_name='lineitemconversionpixel',
            name='line_item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.LineItem'),
        ),
        migrations.AlterField(
            model_name='lineitemconversionpixel',
            name='pixel',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.ConversionPixel'),
        ),
        migrations.AlterField(
            model_name='lineitemcreatives',
            name='creative',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Creative'),
        ),
        migrations.AlterField(
            model_name='lineitemcreatives',
            name='line_item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.LineItem'),
        ),
        migrations.AlterField(
            model_name='lineitemgoalpixel',
            name='line_item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.LineItem'),
        ),
        migrations.AlterField(
            model_name='lineitemgoalpixel',
            name='pixel',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.GoalPixel'),
        ),
        migrations.AlterField(
            model_name='lineiteminsertionorder',
            name='insertion_order',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.InsertionOrder'),
        ),
        migrations.AlterField(
            model_name='lineiteminsertionorder',
            name='line_item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.LineItem'),
        ),
        migrations.AlterField(
            model_name='lineitemlabel',
            name='label',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Label'),
        ),
        migrations.AlterField(
            model_name='lineitemlabel',
            name='line_item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.LineItem'),
        ),
        migrations.AlterField(
            model_name='manualofferranking',
            name='line_item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.LineItem'),
        ),
        migrations.AlterField(
            model_name='manualofferranking',
            name='managed_optimization_zone',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.OptimizationZone'),
        ),
        migrations.AlterField(
            model_name='mediasubtype',
            name='media_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.MediaType'),
        ),
        migrations.AlterField(
            model_name='mediasubtypenativeassets',
            name='media_sub_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.MediaSubType'),
        ),
        migrations.AlterField(
            model_name='mediasubtypepermittedsizes',
            name='media_sub_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.MediaSubType'),
        ),
        migrations.AlterField(
            model_name='member',
            name='default_ad_profile',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='member_ad_profile_id', to='rtb.AdProfile'),
        ),
        migrations.AlterField(
            model_name='member',
            name='default_buyer_group',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.BuyerGroup'),
        ),
        migrations.AlterField(
            model_name='member',
            name='developer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Developer'),
        ),
        migrations.AlterField(
            model_name='memberbrandexception',
            name='brand',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Brand'),
        ),
        migrations.AlterField(
            model_name='memberbrandexception',
            name='member',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Member'),
        ),
        migrations.AlterField(
            model_name='membercontentcategory',
            name='content_category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.ContentCategory'),
        ),
        migrations.AlterField(
            model_name='membercontentcategory',
            name='member',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Member'),
        ),
        migrations.AlterField(
            model_name='membercountry',
            name='country',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Country'),
        ),
        migrations.AlterField(
            model_name='membercountry',
            name='member',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Member'),
        ),
        migrations.AlterField(
            model_name='memberflooroptimisation',
            name='bidder',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.User'),
        ),
        migrations.AlterField(
            model_name='memberflooroptimisation',
            name='member',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Member'),
        ),
        migrations.AlterField(
            model_name='memberinventorytrust',
            name='member',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Member'),
        ),
        migrations.AlterField(
            model_name='memberplugin',
            name='member',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Member'),
        ),
        migrations.AlterField(
            model_name='memberplugin',
            name='plugin',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Plugin'),
        ),
        migrations.AlterField(
            model_name='memberprofilecountry',
            name='country',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Country'),
        ),
        migrations.AlterField(
            model_name='memberprofilecountry',
            name='member_profile',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.MemberProfile'),
        ),
        migrations.AlterField(
            model_name='memberthirdpartypixel',
            name='member',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Member'),
        ),
        migrations.AlterField(
            model_name='memberthirdpartypixel',
            name='thirdparty_pixel',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.ThirdPartyPixel'),
        ),
        migrations.AlterField(
            model_name='mobileappinstancebundle',
            name='os_family',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.OSFamily'),
        ),
        migrations.AlterField(
            model_name='mobileappstore',
            name='os_family',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.OSFamily'),
        ),
        migrations.AlterField(
            model_name='networkadvertiseranalyticsreport',
            name='advertiser',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Advertiser'),
        ),
        migrations.AlterField(
            model_name='networkadvertiseranalyticsreport',
            name='buyer_member',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='rtb.PlatformMember'),
        ),
        migrations.AlterField(
            model_name='networkadvertiseranalyticsreport',
            name='campaign',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Campaign'),
        ),
        migrations.AlterField(
            model_name='networkadvertiseranalyticsreport',
            name='creative',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Creative'),
        ),
        migrations.AlterField(
            model_name='networkadvertiseranalyticsreport',
            name='deal',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Deal'),
        ),
        migrations.AlterField(
            model_name='networkadvertiseranalyticsreport',
            name='geo_country',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Country'),
        ),
        migrations.AlterField(
            model_name='networkadvertiseranalyticsreport',
            name='insertion_order',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.InsertionOrder'),
        ),
        migrations.AlterField(
            model_name='networkadvertiseranalyticsreport',
            name='line_item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.LineItem'),
        ),
        migrations.AlterField(
            model_name='networkadvertiseranalyticsreport',
            name='media_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.MediaType'),
        ),
        migrations.AlterField(
            model_name='networkadvertiseranalyticsreport',
            name='pixel',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.ConversionPixel'),
        ),
        migrations.AlterField(
            model_name='networkadvertiseranalyticsreport',
            name='placement',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Placement'),
        ),
        migrations.AlterField(
            model_name='networkadvertiseranalyticsreport',
            name='publisher',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Publisher'),
        ),
        migrations.AlterField(
            model_name='networkadvertiseranalyticsreport',
            name='seller_member',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='rtb.PlatformMember'),
        ),
        migrations.AlterField(
            model_name='networkadvertiseranalyticsreport',
            name='site',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Site'),
        ),
        migrations.AlterField(
            model_name='networkanalyticsfeed',
            name='advertiser',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Advertiser'),
        ),
        migrations.AlterField(
            model_name='networkanalyticsfeed',
            name='buyer_member',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='rtb.PlatformMember'),
        ),
        migrations.AlterField(
            model_name='networkanalyticsfeed',
            name='campaign',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Campaign'),
        ),
        migrations.AlterField(
            model_name='networkanalyticsfeed',
            name='creative',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Creative'),
        ),
        migrations.AlterField(
            model_name='networkanalyticsfeed',
            name='deal',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Deal'),
        ),
        migrations.AlterField(
            model_name='networkanalyticsfeed',
            name='entity_member',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='rtb.Member'),
        ),
        migrations.AlterField(
            model_name='networkanalyticsfeed',
            name='external_inv',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.PublisherExternalInventoryCode'),
        ),
        migrations.AlterField(
            model_name='networkanalyticsfeed',
            name='geo_country',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Country'),
        ),
        migrations.AlterField(
            model_name='networkanalyticsfeed',
            name='insertion_order',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.InsertionOrder'),
        ),
        migrations.AlterField(
            model_name='networkanalyticsfeed',
            name='line_item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.LineItem'),
        ),
        migrations.AlterField(
            model_name='networkanalyticsfeed',
            name='media_subtype',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.MediaSubType'),
        ),
        migrations.AlterField(
            model_name='networkanalyticsfeed',
            name='media_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.MediaType'),
        ),
        migrations.AlterField(
            model_name='networkanalyticsfeed',
            name='pixel',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.ConversionPixel'),
        ),
        migrations.AlterField(
            model_name='networkanalyticsfeed',
            name='placement',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Placement'),
        ),
        migrations.AlterField(
            model_name='networkanalyticsfeed',
            name='pub_rule',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.AdQualityRule'),
        ),
        migrations.AlterField(
            model_name='networkanalyticsfeed',
            name='publisher',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Publisher'),
        ),
        migrations.AlterField(
            model_name='networkanalyticsfeed',
            name='seller_member',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='rtb.PlatformMember'),
        ),
        migrations.AlterField(
            model_name='networkanalyticsfeed',
            name='site',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Site'),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='advertiser',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Advertiser'),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='brand',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Brand'),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='buyer_member',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='buyer_member_id', to='rtb.PlatformMember'),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='campaign',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Campaign'),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='creative',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Creative'),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='deal',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Deal'),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='geo_country',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Country'),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='insertion_order',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.InsertionOrder'),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='line_item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.LineItem'),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='media_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.MediaType'),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='pixel',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.ConversionPixel'),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='placement',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Placement'),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='pub_rule',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.AdQualityRule'),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='publisher',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Publisher'),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='seller_member',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='seller_member_id', to='rtb.PlatformMember'),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='site',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Site'),
        ),
        migrations.AlterField(
            model_name='networkcarrierreport',
            name='advertiser',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Advertiser'),
        ),
        migrations.AlterField(
            model_name='networkcarrierreport',
            name='buyer_member',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='rtb.PlatformMember'),
        ),
        migrations.AlterField(
            model_name='networkcarrierreport',
            name='campaign',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Campaign'),
        ),
        migrations.AlterField(
            model_name='networkcarrierreport',
            name='geo_country',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Country'),
        ),
        migrations.AlterField(
            model_name='networkcarrierreport',
            name='insertion_order',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.InsertionOrder'),
        ),
        migrations.AlterField(
            model_name='networkcarrierreport',
            name='line_item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.LineItem'),
        ),
        migrations.AlterField(
            model_name='networkcarrierreport',
            name='media_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.MediaType'),
        ),
        migrations.AlterField(
            model_name='networkcarrierreport',
            name='pixel',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.ConversionPixel'),
        ),
        migrations.AlterField(
            model_name='networkcarrierreport',
            name='pub_rule',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.AdQualityRule'),
        ),
        migrations.AlterField(
            model_name='networkcarrierreport',
            name='publisher',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Publisher'),
        ),
        migrations.AlterField(
            model_name='networkcarrierreport',
            name='seller_member',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='rtb.PlatformMember'),
        ),
        migrations.AlterField(
            model_name='networkdevicereport',
            name='advertiser',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Advertiser'),
        ),
        migrations.AlterField(
            model_name='networkdevicereport',
            name='browser',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Browser'),
        ),
        migrations.AlterField(
            model_name='networkdevicereport',
            name='buyer_member',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='rtb.PlatformMember'),
        ),
        migrations.AlterField(
            model_name='networkdevicereport',
            name='campaign',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Campaign'),
        ),
        migrations.AlterField(
            model_name='networkdevicereport',
            name='device_make',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.DeviceMake'),
        ),
        migrations.AlterField(
            model_name='networkdevicereport',
            name='device_model',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.DeviceModel'),
        ),
        migrations.AlterField(
            model_name='networkdevicereport',
            name='geo_country',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Country'),
        ),
        migrations.AlterField(
            model_name='networkdevicereport',
            name='insertion_order',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.InsertionOrder'),
        ),
        migrations.AlterField(
            model_name='networkdevicereport',
            name='line_item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.LineItem'),
        ),
        migrations.AlterField(
            model_name='networkdevicereport',
            name='media_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.MediaType'),
        ),
        migrations.AlterField(
            model_name='networkdevicereport',
            name='operating_system',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.OperatingSystem'),
        ),
        migrations.AlterField(
            model_name='networkdevicereport',
            name='pixel',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.ConversionPixel'),
        ),
        migrations.AlterField(
            model_name='networkdevicereport',
            name='pub_rule',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.AdQualityRule'),
        ),
        migrations.AlterField(
            model_name='networkdevicereport',
            name='publisher',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Publisher'),
        ),
        migrations.AlterField(
            model_name='networkdevicereport',
            name='seller_member',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='rtb.PlatformMember'),
        ),
        migrations.AlterField(
            model_name='operatingsystem',
            name='os_family',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.OSFamily'),
        ),
        migrations.AlterField(
            model_name='operatingsystemextended',
            name='os_family',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.OSFamily'),
        ),
        migrations.AlterField(
            model_name='paymentrule',
            name='profile',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Profile'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='ad_profile',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.AdProfile'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='default_creative',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Creative'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='publisher',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Publisher'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='site',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Site'),
        ),
        migrations.AlterField(
            model_name='placementcontentcategory',
            name='content_category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.ContentCategory'),
        ),
        migrations.AlterField(
            model_name='placementcontentcategory',
            name='placement',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Placement'),
        ),
        migrations.AlterField(
            model_name='placementestimatedclearprices',
            name='placement',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Placement'),
        ),
        migrations.AlterField(
            model_name='placementinventoryattributes',
            name='inventory_attribute',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.InventoryAttribute'),
        ),
        migrations.AlterField(
            model_name='placementinventoryattributes',
            name='placement',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Placement'),
        ),
        migrations.AlterField(
            model_name='placementmediasubtype',
            name='media_sub_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.MediaSubType'),
        ),
        migrations.AlterField(
            model_name='placementmediasubtype',
            name='placement',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Placement'),
        ),
        migrations.AlterField(
            model_name='placementmediatype',
            name='media_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.MediaType'),
        ),
        migrations.AlterField(
            model_name='placementmediatype',
            name='placement',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Placement'),
        ),
        migrations.AlterField(
            model_name='placementpopvalues',
            name='placement',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Placement'),
        ),
        migrations.AlterField(
            model_name='placementprivatesizes',
            name='placement',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Placement'),
        ),
        migrations.AlterField(
            model_name='platformmember',
            name='bidder',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.User'),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='developer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Developer'),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='plugin_category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Category'),
        ),
        migrations.AlterField(
            model_name='plugindomain',
            name='plugin',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Plugin'),
        ),
        migrations.AlterField(
            model_name='plugininstance',
            name='plugin',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Plugin'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='advertiser',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='advertiser_id', to='rtb.Advertiser'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='base_payment_rule',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.PaymentRule'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='default_ad_profile',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='publisher_ad_profile_id', to='rtb.AdProfile'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='default_site',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Site'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='ym_profile',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ym_profile_id', to='rtb.YieldManagementProfile'),
        ),
        migrations.AlterField(
            model_name='publisherbrandexceptions',
            name='brand',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Brand'),
        ),
        migrations.AlterField(
            model_name='publisherbrandexceptions',
            name='publisher',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Publisher'),
        ),
        migrations.AlterField(
            model_name='publishercontact',
            name='publisher',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Publisher'),
        ),
        migrations.AlterField(
            model_name='publisherexternalinventorycode',
            name='publisher',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Publisher'),
        ),
        migrations.AlterField(
            model_name='publisherlabel',
            name='label',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Label'),
        ),
        migrations.AlterField(
            model_name='publisherlabel',
            name='publisher',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Publisher'),
        ),
        migrations.AlterField(
            model_name='publisherplacement',
            name='placement',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Placement'),
        ),
        migrations.AlterField(
            model_name='publisherplacement',
            name='publisher',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Publisher'),
        ),
        migrations.AlterField(
            model_name='region',
            name='country',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Country'),
        ),
        migrations.AlterField(
            model_name='segment',
            name='advertiser',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Advertiser'),
        ),
        migrations.AlterField(
            model_name='segment',
            name='member',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Member'),
        ),
        migrations.AlterField(
            model_name='segment',
            name='parent_segment',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Segment'),
        ),
        migrations.AlterField(
            model_name='segmentpiggybackpixels',
            name='segment',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Segment'),
        ),
        migrations.AlterField(
            model_name='sellermembergroup',
            name='member',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Member'),
        ),
        migrations.AlterField(
            model_name='site',
            name='managed_optimization_zone',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='managed_optimization_zone_id', to='rtb.OptimizationZone'),
        ),
        migrations.AlterField(
            model_name='site',
            name='mobile_app_instance',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.MobileAppInstance'),
        ),
        migrations.AlterField(
            model_name='site',
            name='primary_content_category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.ContentCategory'),
        ),
        migrations.AlterField(
            model_name='site',
            name='publisherd',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Publisher'),
        ),
        migrations.AlterField(
            model_name='site',
            name='rtb_optimization_zone',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rtb_optimization_zone_id', to='rtb.OptimizationZone'),
        ),
        migrations.AlterField(
            model_name='sitecontentcategory',
            name='content_category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.ContentCategory'),
        ),
        migrations.AlterField(
            model_name='sitedomainperformancereport',
            name='advertiser',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Advertiser'),
        ),
        migrations.AlterField(
            model_name='sitedomainperformancereport',
            name='buyer_member',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Member'),
        ),
        migrations.AlterField(
            model_name='sitedomainperformancereport',
            name='campaign',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Campaign'),
        ),
        migrations.AlterField(
            model_name='sitedomainperformancereport',
            name='conversion_pixel',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.ConversionPixel'),
        ),
        migrations.AlterField(
            model_name='sitedomainperformancereport',
            name='deal',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Deal'),
        ),
        migrations.AlterField(
            model_name='sitedomainperformancereport',
            name='line_item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.LineItem'),
        ),
        migrations.AlterField(
            model_name='sitedomainperformancereport',
            name='operating_system',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.OperatingSystemExtended'),
        ),
        migrations.AlterField(
            model_name='sitedomainperformancereport',
            name='second_level_category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='second_level_category_id', to='rtb.ContentCategory'),
        ),
        migrations.AlterField(
            model_name='sitedomainperformancereport',
            name='top_level_category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='top_level_category_id', to='rtb.ContentCategory'),
        ),
        migrations.AlterField(
            model_name='siteinventoryattributes',
            name='inventory_attribute',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.InventoryAttribute'),
        ),
        migrations.AlterField(
            model_name='user',
            name='advertiser',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Advertiser'),
        ),
        migrations.AlterField(
            model_name='user',
            name='entity',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Member'),
        ),
        migrations.AlterField(
            model_name='user',
            name='publisher',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Publisher'),
        ),
        migrations.AlterField(
            model_name='yieldmanagementprofile',
            name='publisher',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Publisher'),
        ),
        migrations.AlterField(
            model_name='yieldmanagementprofilemodifiers',
            name='technical_attribute',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.TechnicalAttribute'),
        ),
        migrations.AlterField(
            model_name='yieldmanagementprofilemodifiers',
            name='yield_management_profile',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.YieldManagementProfile'),
        ),
    ]
