# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-21 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0071_auto_20160818_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creative',
            name='google_audit_feedback',
        ),
        migrations.RemoveField(
            model_name='creative',
            name='google_audit_status',
        ),
        migrations.RemoveField(
            model_name='creative',
            name='msft_audit_feedback',
        ),
        migrations.RemoveField(
            model_name='creative',
            name='msft_audit_status',
        ),
        migrations.RemoveField(
            model_name='creativetemplate',
            name='content_xml',
        ),
        migrations.RemoveField(
            model_name='memberinventorytrust',
            name='default_is_banned',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='segment_targets',
        ),
        migrations.AddField(
            model_name='creative',
            name='adx_audit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creative',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
