# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-21 20:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0073_auto_20160821_1935'),
    ]

    operations = [
        migrations.RenameField(
            'networkanalyticsreport',
            'media_type',
            'media_subtype'
        ),
    ]
