# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-21 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0074_auto_20160821_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='media_subtype',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.MediaSubType'),
        ),
    ]
