# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-21 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0075_auto_20160821_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkanalyticsreport',
            name='media_type',
            field=models.ForeignKey(db_index=False, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.MediaType'),
        ),
        migrations.RunSQL('CREATE INDEX "network_analytics_report__media_type_id" ON "network_analytics_report" ("media_type_id");'),
    ]
