# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 07:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0077_auto_20160821_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkanalyticsreport_byplacement',
            name='bid_type',
            field=models.TextField(blank=True, choices=[(b'Manual', b'Manual'), (b'Learn', b'Learn'), (b'Optimized', b'Optimized'), (b'Unknown', b'Unknown'), (b'Optimized give up', b'Optimized give up'), (b'Learn give up', b'Learn give up'), (b'Manual give up', b'Manual give up')], null=True),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport_byplacement',
            name='geo_country',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Country'),
        ),
        migrations.AddField(
            model_name='networkanalyticsreport_byplacement',
            name='imp_type_id',
            field=models.IntegerField(blank=True, choices=[(b'1', b'Blank'), (b'2', b'PSA'), (b'3', b'Default Error'), (b'4', b'Default'), (b'5', b'Kept'), (b'6', b'Resold'), (b'7', b'RTB'), (b'8', b'PSA Error'), (b'9', b'External Impression'), (b'10', b'External Click'), (b'11', b'Insertion')], null=True),
        ),
        migrations.AlterField(
            model_name='networkanalyticsreport',
            name='media_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.MediaType'),
        ),
    ]
