# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 14:03
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0083_auto_20160914_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlplacementsclusterskmeans',
            name='distanceToClusters',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=10, max_digits=35), null=True, size=None),
        ),
    ]
