# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 22:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0085_auto_20160921_1447'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mlclusterscentroidskmeans',
            table='ml_clusters_centroids_kmeans',
        ),
    ]
