# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-27 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0086_auto_20160921_2210'),
        ('rtb', '0083_add_indexes_amend_types_20160904_2241'),
    ]

    operations = [
    ]
