# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-30 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0086_auto_20160921_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlclusterscentroidskmeans',
            name='test_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mlplacementdailyfeatures',
            name='cpc',
            field=models.DecimalField(decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='mlplacementdailyfeatures',
            name='cpm',
            field=models.DecimalField(decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='mlplacementdailyfeatures',
            name='cvr',
            field=models.DecimalField(decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='mlplacementsclusterskmeans',
            name='expert_decision',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='mlplacementsclusterskmeans',
            name='test_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='mlclusterscentroidskmeans',
            unique_together=set([('cluster', 'day', 'test_number')]),
        ),
        migrations.AlterUniqueTogether(
            name='mlplacementsclusterskmeans',
            unique_together=set([('placement', 'day', 'test_number')]),
        ),
    ]
