# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-05 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0088_merge_20160930_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLNormalizationData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('test_number', models.IntegerField(db_index=True)),
                ('day', models.IntegerField(db_index=True)),
                ('maxcpa', models.FloatField(null=True)),
                ('maxcvr', models.DecimalField(decimal_places=10, max_digits=35, null=True)),
                ('maxcpc', models.DecimalField(decimal_places=10, max_digits=35, null=True)),
                ('maxcpm', models.DecimalField(decimal_places=10, max_digits=35, null=True)),
            ],
            options={
                'db_table': 'ml_normalization_data',
            },
        ),
        migrations.AlterUniqueTogether(
            name='mlnormalizationdata',
            unique_together=set([('test_number', 'day')]),
        ),
    ]
