# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-05 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0088_merge_20160930_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementState',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.TextField(blank=True, null=True)),
                ('suspend', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Campaign')),
                ('placement', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Placement')),
            ],
            options={
                'db_table': 'placement_state',
            },
        ),
    ]
