# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-10 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0090_fill_prev_testnumbers'),
        ('rtb', '0089_placementstate'),
    ]

    operations = [
    ]
