# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-10 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0091_merge_20161010_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placementstate',
            name='state',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
