# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-20 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0092_auto_20161010_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='RtbImpressionTracker',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('LocationsOrigins', models.TextField(blank=True, null=True)),
                ('UserCountry', models.TextField(blank=True, null=True)),
                ('SessionFreq', models.TextField(blank=True, null=True)),
                ('PricePaid', models.TextField(blank=True, null=True)),
                ('AdvFreq', models.TextField(blank=True, null=True)),
                ('UserState', models.TextField(blank=True, null=True)),
                ('CpgId', models.TextField(blank=True, null=True)),
                ('CustomModelLastModified', models.TextField(blank=True, null=True)),
                ('UserId', models.TextField(blank=True, null=True)),
                ('XRealIp', models.TextField(blank=True, null=True)),
                ('BidPrice', models.TextField(blank=True, null=True)),
                ('SegIds', models.TextField(blank=True, null=True)),
                ('UserAgent', models.TextField(blank=True, null=True)),
                ('AuctionId', models.TextField(blank=True, null=True)),
                ('RemUser', models.TextField(blank=True, null=True)),
                ('CpId', models.TextField(blank=True, null=True)),
                ('UserCity', models.TextField(blank=True, null=True)),
                ('Age', models.TextField(blank=True, null=True)),
                ('ReservePrice', models.TextField(blank=True, null=True)),
                ('CacheBuster', models.TextField(blank=True, null=True)),
                ('Ecp', models.TextField(blank=True, null=True)),
                ('CustomModelId', models.TextField(blank=True, null=True)),
                ('PlacementId', models.TextField(blank=True, db_index=True, null=True)),
                ('SeqCodes', models.TextField(blank=True, null=True)),
                ('CustomModelLeafName', models.TextField(blank=True, null=True)),
                ('XForwardedFor', models.TextField(blank=True, null=True)),
                ('Date', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'rtb_impression_tracker',
            },
        ),
        migrations.CreateModel(
            name='RtbImpressionTrackerPlacement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('placement', models.IntegerField(blank=True, null=True)),
                ('domain', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rtb_impression_tracker_placement',
            },
        ),
    ]
