# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-23 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0093_rtbimpressiontracker_rtbimpressiontrackerplacement'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementstate',
            name='change',
            field=models.BooleanField(default=False),
        ),
    ]
