# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-25 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0094_placementstate_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placementstate',
            name='campaign',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Campaign', unique=True),
        ),
        migrations.AlterField(
            model_name='placementstate',
            name='placement',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Placement', unique=True),
        ),
    ]
