# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-25 07:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0095_auto_20161025_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placementstate',
            name='campaign',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Campaign'),
        ),
        migrations.AlterField(
            model_name='placementstate',
            name='placement',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Placement'),
        ),
    ]
