# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-26 07:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0096_auto_20161025_0751'),
        ('rtb', '0095_auto_20161025_1407'),
    ]

    operations = [
    ]
