# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-31 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0100_auto_20161031_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastModified',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'last_modified',
            },
        ),
    ]
