# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-03 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0101_lastmodified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastmodified',
            name='type',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
