# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-04 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0102_auto_20161103_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastToken',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True, unique=True)),
                ('token', models.TextField(blank=True, null=True, unique=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'last_token',
            },
        ),
    ]
