# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-04 14:56
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0104_materialized_view_placements_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLViewFullPlacementsData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imps', models.IntegerField(db_index=True)),
                ('clicks', models.IntegerField()),
                ('total_convs', models.IntegerField()),
                ('imps_viewed', models.IntegerField()),
                ('view_measured_imps', models.IntegerField()),
                ('sum_cost', models.DecimalField(decimal_places=10, max_digits=35)),
                ('view_rate', models.FloatField()),
                ('view_measurement_rate', models.FloatField()),
                ('cpa', models.FloatField()),
                ('ctr', models.FloatField()),
                ('cvr', models.DecimalField(decimal_places=10, max_digits=35, null=True)),
                ('cpc', models.DecimalField(decimal_places=10, max_digits=35, null=True)),
                ('cpm', models.DecimalField(decimal_places=10, max_digits=35, null=True)),
            ],
            options={
                'db_table': 'ml_view_full_placements_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MLTestDataSet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created', models.DateField(db_index=True, unique=True)),
            ],
            options={
                'ordering': ['-created'],
                'db_table': 'ml_test_data_set',
            },
        ),
    ]
