# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-07 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0105_mltestdataset_mlviewfullplacementsdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlexpertsplacementsmarks',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='mltestdataset',
            name='created',
            field=models.DateTimeField(db_index=True, unique=True),
        ),
    ]
