# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-15 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0106_auto_20161107_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlplacementsclusterskmeans',
            name='good',
            field=models.NullBooleanField(),
        ),
    ]
