# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-16 13:50
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0107_mlplacementsclusterskmeans_good'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLLogisticRegressionCoeff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.IntegerField(db_index=True)),
                ('coeff', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=10, max_digits=35), size=None)),
                ('test_number', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'ml_logistic_regression_coeff',
            },
        ),
        migrations.CreateModel(
            name='MLLogisticRegressionResults',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.IntegerField(db_index=True)),
                ('probability', models.DecimalField(decimal_places=10, max_digits=35)),
                ('test_number', models.IntegerField(null=True)),
                ('expert_decision', models.NullBooleanField()),
                ('placement', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Placement')),
            ],
            options={
                'db_table': 'ml_logistic_regression_results',
            },
        ),
        migrations.AlterUniqueTogether(
            name='mllogisticregressioncoeff',
            unique_together=set([('day', 'test_number')]),
        ),
        migrations.AlterUniqueTogether(
            name='mllogisticregressionresults',
            unique_together=set([('placement', 'day', 'test_number')]),
        ),
    ]
