# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-17 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0109_view_rules_campaign_placements'),
    ]

    operations = [
        migrations.AddField(
            model_name='mllogisticregressioncoeff',
            name='good_direction',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mllogisticregressioncoeff',
            name='test_number',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='mllogisticregressionresults',
            name='expert_decision',
            field=models.NullBooleanField(db_index=True),
        ),
        migrations.AlterField(
            model_name='mllogisticregressionresults',
            name='test_number',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
