# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-17 13:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0110_auto_20161117_0859'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mlexpertsplacementsmarks',
            unique_together=set([('placement', 'day')]),
        ),
    ]
