# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-21 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0112_view_rules_campaign_placements'),
    ]

    operations = [
        migrations.AddField(
            model_name='mllogisticregressionresults',
            name='good',
            field=models.NullBooleanField(),
        ),
    ]
