# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-02 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0114_view_rules_join_preditions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttentionMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'attention_message',
            },
        ),
        migrations.CreateModel(
            name='TechnicalWork',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'technical_work',
            },
        ),
    ]
