# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-04 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0115_attentionmessage_technicalwork'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attentionmessage',
            name='date',
        ),
        migrations.AddField(
            model_name='attentionmessage',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
