# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-03 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0118_auto_20161212_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='RtbAdStartTracker',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('CpId', models.TextField(blank=True, null=True)),
                ('AdvId', models.TextField(blank=True, null=True)),
                ('CreativeId', models.TextField(blank=True, null=True)),
                ('AuctionId', models.TextField(blank=True, null=True)),
                ('cpvm', models.TextField(blank=True, null=True)),
                ('Date', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'rtb_adstart_tracker',
            },
        ),
    ]
