# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-03 12:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0119_auto_20161227_1532'),
        ('rtb', '0119_rtbadstarttracker'),
    ]

    operations = [
    ]
