# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-04 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0121_advertiser_ad_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAdCampaigns',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('advertiser_id', models.IntegerField(db_index=True)),
                ('campaign_id', models.IntegerField(db_index=True)),
                ('date', models.DateTimeField(db_index=True)),
                ('imp_hour', models.IntegerField()),
                ('ad_starts_hour', models.IntegerField()),
                ('spent_hour', models.DecimalField(decimal_places=10, max_digits=35)),
                ('cpm_hour', models.DecimalField(decimal_places=10, max_digits=35)),
                ('fill_rate_hour', models.DecimalField(decimal_places=10, max_digits=35)),
                ('profit_loss_hour', models.DecimalField(decimal_places=10, max_digits=35)),
            ],
            options={
                'db_table': 'video_ad_campaigns',
            },
        ),
    ]
