# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-04 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0122_videoadcampaigns'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoadcampaigns',
            name='bid_hour',
            field=models.DecimalField(decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='videoadcampaigns',
            name='cpvm_hour',
            field=models.DecimalField(decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='videoadcampaigns',
            name='spent_cpm_hour',
            field=models.DecimalField(decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AddField(
            model_name='videoadcampaigns',
            name='spent_cpvm_hour',
            field=models.DecimalField(decimal_places=10, max_digits=35, null=True),
        ),
    ]
