# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-05 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0123_auto_20170104_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertiser',
            name='ad_type',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
