# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-10 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0124_auto_20170105_0905'),
    ]

    operations = [
        migrations.RunSQL(
            """ UPDATE rtb_adstart_tracker SET "CpId" = NULL WHERE "CpId" LIKE ' ' or "CpId" LIKE ''; """),
        migrations.RunSQL(
            """ UPDATE rtb_adstart_tracker SET "AdvId" = NULL WHERE "AdvId" LIKE ' ' or "AdvId" LIKE ''; """),
        migrations.RunSQL(
            """ UPDATE rtb_adstart_tracker SET "CreativeId" = NULL WHERE "CreativeId" LIKE ' ' or "CreativeId" LIKE ''; """),
        migrations.RunSQL(
            """ UPDATE rtb_adstart_tracker SET "AuctionId" = NULL WHERE "AuctionId" LIKE ' ' or "AuctionId" LIKE ''; """),
        migrations.RunSQL(
            """ UPDATE rtb_adstart_tracker SET "cpvm" = NULL WHERE "cpvm" LIKE ' ' or "cpvm" LIKE ''; """),

        migrations.RunSQL(
            """ UPDATE rtb_conversion_tracker SET "CpId" = NULL WHERE "CpId" LIKE ' ' or "CpId" LIKE ''; """),
        migrations.RunSQL(
            """ UPDATE rtb_conversion_tracker SET "AdvId" = NULL WHERE "AdvId" LIKE ' ' or "AdvId" LIKE ''; """),
        migrations.RunSQL(
            """ UPDATE rtb_conversion_tracker SET "CreativeId" = NULL WHERE "CreativeId" LIKE ' ' or "CreativeId" LIKE ''; """),
        migrations.RunSQL(
            """ UPDATE rtb_conversion_tracker SET "AuctionId" = NULL WHERE "AuctionId" LIKE ' ' or "AuctionId" LIKE ''; """),

        migrations.RunSQL(""" UPDATE rtb_click_tracker SET "CpId" = NULL WHERE "CpId" LIKE ' ' or "CpId" LIKE ''; """),
        migrations.RunSQL(
            """ UPDATE rtb_click_tracker SET "AdvId" = NULL WHERE "AdvId" LIKE ' ' or "AdvId" LIKE ''; """),
        migrations.RunSQL(
            """ UPDATE rtb_click_tracker SET "CreativeId" = NULL WHERE "CreativeId" LIKE ' ' or "CreativeId" LIKE ''; """),
        migrations.RunSQL(
            """ UPDATE rtb_click_tracker SET "AuctionId" = NULL WHERE "AuctionId" LIKE ' ' or "AuctionId" LIKE ''; """),

        migrations.RunSQL("""
            UPDATE rtb_impression_tracker SET "PricePaid" = NULL WHERE "PricePaid" LIKE ' ' or "PricePaid" LIKE '';
            UPDATE rtb_impression_tracker SET "AdvFreq" = NULL WHERE "AdvFreq" LIKE ' ' or "AdvFreq" LIKE '';
            UPDATE rtb_impression_tracker SET "CpgId" = NULL WHERE "CpgId" LIKE ' ' or "CpgId" LIKE '';
            UPDATE rtb_impression_tracker SET "UserId" = NULL WHERE "UserId" LIKE ' ' or "UserId" LIKE '';
            UPDATE rtb_impression_tracker SET "BidPrice" = NULL WHERE "BidPrice" LIKE ' ' or "BidPrice" LIKE '';
            UPDATE rtb_impression_tracker SET "SegIds" = NULL WHERE "SegIds" LIKE ' ' or "SegIds" LIKE '';
            UPDATE rtb_impression_tracker SET "AuctionId" = NULL WHERE "AuctionId" LIKE ' ' or "AuctionId" LIKE '';
            UPDATE rtb_impression_tracker SET "RemUser" = NULL WHERE "RemUser" LIKE ' ' or "RemUser" LIKE '';
            UPDATE rtb_impression_tracker SET "CpId" = NULL WHERE "CpId" LIKE ' ' or "CpId" LIKE '';
            UPDATE rtb_impression_tracker SET "Age" = NULL WHERE "Age" LIKE ' ' or "Age" LIKE '';
            UPDATE rtb_impression_tracker SET "ReservePrice" = NULL WHERE "ReservePrice" LIKE ' ' or "ReservePrice" LIKE '';
            UPDATE rtb_impression_tracker SET "CacheBuster" = NULL WHERE "CacheBuster" LIKE ' ' or "CacheBuster" LIKE '';
            UPDATE rtb_impression_tracker SET "Ecp" = NULL WHERE "Ecp" LIKE ' ' or "Ecp" LIKE '';
            UPDATE rtb_impression_tracker SET "CustomModelId" = NULL WHERE "CustomModelId" LIKE ' ' or "CustomModelId" LIKE '';
            UPDATE rtb_impression_tracker SET "PlacementId" = NULL WHERE "PlacementId" LIKE ' ' or "PlacementId" LIKE '';
            UPDATE rtb_impression_tracker SET "CreativeId" = NULL WHERE "CreativeId" LIKE ' ' or "CreativeId" LIKE '';
            UPDATE rtb_impression_tracker SET "AdvId" = NULL WHERE "AdvId" LIKE ' ' or "AdvId" LIKE '';
         """),
        migrations.AlterField(
            model_name='rtbadstarttracker',
            name='AdvId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rtbadstarttracker',
            name='AuctionId',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rtbadstarttracker',
            name='CpId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rtbadstarttracker',
            name='CreativeId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rtbadstarttracker',
            name='cpvm',
            field=models.DecimalField(decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AlterField(
            model_name='rtbclicktracker',
            name='AdvId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rtbclicktracker',
            name='AuctionId',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rtbclicktracker',
            name='CpId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rtbclicktracker',
            name='CreativeId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rtbconversiontracker',
            name='AdvId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rtbconversiontracker',
            name='AuctionId',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rtbconversiontracker',
            name='CpId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rtbconversiontracker',
            name='CreativeId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rtbimpressiontracker',
            name='AdvId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rtbimpressiontracker',
            name='Age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rtbimpressiontracker',
            name='AuctionId',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rtbimpressiontracker',
            name='BidPrice',
            field=models.DecimalField(decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AlterField(
            model_name='rtbimpressiontracker',
            name='CacheBuster',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rtbimpressiontracker',
            name='CpId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rtbimpressiontracker',
            name='CpgId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rtbimpressiontracker',
            name='CreativeId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rtbimpressiontracker',
            name='CustomModelId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rtbimpressiontracker',
            name='Ecp',
            field=models.DecimalField(decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AlterField(
            model_name='rtbimpressiontracker',
            name='PlacementId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rtbimpressiontracker',
            name='PricePaid',
            field=models.DecimalField(decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AlterField(
            model_name='rtbimpressiontracker',
            name='RemUser',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rtbimpressiontracker',
            name='ReservePrice',
            field=models.DecimalField(decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AlterField(
            model_name='rtbimpressiontracker',
            name='SegIds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rtbimpressiontracker',
            name='UserId',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
