# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-13 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0126_auto_20170110_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoadcampaigns',
            name='ad_starts_hour',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='videoadcampaigns',
            name='cpm_hour',
            field=models.DecimalField(decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AlterField(
            model_name='videoadcampaigns',
            name='fill_rate_hour',
            field=models.DecimalField(decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AlterField(
            model_name='videoadcampaigns',
            name='imp_hour',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='videoadcampaigns',
            name='profit_loss_hour',
            field=models.DecimalField(decimal_places=10, max_digits=35, null=True),
        ),
        migrations.AlterField(
            model_name='videoadcampaigns',
            name='spent_hour',
            field=models.DecimalField(decimal_places=10, max_digits=35, null=True),
        ),
    ]
