# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-13 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0127_auto_20170113_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitedomainperformancereport',
            name='hour',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
