# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-18 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0130_alter_video_ad_campaigns_time_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RtbDomainTracker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('domain', models.TextField(blank=True, db_index=True, null=True)),
                ('auctionid', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('userid', models.BigIntegerField(blank=True, null=True)),
                ('advid', models.IntegerField(blank=True, null=True)),
                ('placement', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Placement', unique=True)),
            ],
            options={
                'db_table': 'rtb_domain_tracker',
            },
        ),
    ]
