# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-18 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0131_rtbdomaintracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='rtbdomaintracker',
            name='Date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
