# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-19 07:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0132_rtbdomaintracker_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtbdomaintracker',
            name='placement',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Placement'),
        ),
    ]
