# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-19 07:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0133_auto_20170119_0712'),
    ]

    operations = [
        migrations.RunSQL('ALTER TABLE rtb_domain_tracker ALTER COLUMN "Date" TYPE timestamp without time zone;')
    ]
