# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-05 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0137_timestamp_mlvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlvideoadcampaignsresults',
            name='res_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.RunSQL(
            'ALTER TABLE ml_video_ad_campaigns_results ALTER COLUMN res_date TYPE timestamp without time zone;'),
    ]
