# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-06 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0138_mlvideoadcampaignsresults_res_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlvideoadcampaignsmodelsinfo',
            name='evaluation_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.RunSQL(
            'ALTER TABLE ml_video_ad_campaigns_models_info ALTER COLUMN evaluation_date TYPE timestamp without time zone;'),
    ]
