# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-07 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0139_auto_20170206_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlvideoadcampaignsresults',
            name='profit_loss',
            field=models.DecimalField(decimal_places=10, max_digits=35, null=True),
        ),
    ]
