# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-17 13:21
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0141_ml_placements_results_indx'),
    ]

    operations = [
        migrations.CreateModel(
            name='UIUsualCampaignsGridDataAll',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('evaluation_date', models.DateTimeField(db_index=True)),
                ('spent', models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True)),
                ('conversions', models.IntegerField()),
                ('imps', models.IntegerField()),
                ('clicks', models.IntegerField()),
                ('cpc', models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True)),
                ('cpm', models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True)),
                ('cvr', models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True)),
                ('ctr', models.FloatField(blank=True, null=True)),
                ('imps_viewed', models.IntegerField(blank=True, null=True)),
                ('view_measured_imps', models.IntegerField(blank=True, null=True)),
                ('view_measurement_rate', models.FloatField(blank=True, null=True)),
                ('view_rate', models.FloatField(blank=True, null=True)),
                ('chart', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), null=True, size=None)),
                ('campaign', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Campaign', unique=True)),
            ],
            options={
                'db_table': 'ui_usual_campaigns_grid_data_all',
            },
        ),
        migrations.CreateModel(
            name='UIUsualCampaignsGridDataCurMonth',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('evaluation_date', models.DateTimeField(db_index=True)),
                ('window_start_date', models.DateTimeField(db_index=True)),
                ('spent', models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True)),
                ('conversions', models.IntegerField()),
                ('imps', models.IntegerField()),
                ('clicks', models.IntegerField()),
                ('cpc', models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True)),
                ('cpm', models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True)),
                ('cvr', models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True)),
                ('ctr', models.FloatField(blank=True, null=True)),
                ('imps_viewed', models.IntegerField(blank=True, null=True)),
                ('view_measured_imps', models.IntegerField(blank=True, null=True)),
                ('view_measurement_rate', models.FloatField(blank=True, null=True)),
                ('view_rate', models.FloatField(blank=True, null=True)),
                ('chart', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), null=True, size=None)),
                ('campaign', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Campaign', unique=True)),
            ],
            options={
                'db_table': 'ui_usual_campaigns_grid_data_cur_month',
            },
        ),
        migrations.CreateModel(
            name='UIUsualCampaignsGridDataLast14Days',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('evaluation_date', models.DateTimeField(db_index=True)),
                ('window_start_date', models.DateTimeField(db_index=True)),
                ('spent', models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True)),
                ('conversions', models.IntegerField()),
                ('imps', models.IntegerField()),
                ('clicks', models.IntegerField()),
                ('cpc', models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True)),
                ('cpm', models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True)),
                ('cvr', models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True)),
                ('ctr', models.FloatField(blank=True, null=True)),
                ('imps_viewed', models.IntegerField(blank=True, null=True)),
                ('view_measured_imps', models.IntegerField(blank=True, null=True)),
                ('view_measurement_rate', models.FloatField(blank=True, null=True)),
                ('view_rate', models.FloatField(blank=True, null=True)),
                ('chart', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), null=True, size=None)),
                ('campaign', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Campaign', unique=True)),
            ],
            options={
                'db_table': 'ui_usual_campaigns_grid_data_last_14_days',
            },
        ),
        migrations.CreateModel(
            name='UIUsualCampaignsGridDataLast21Days',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('evaluation_date', models.DateTimeField(db_index=True)),
                ('window_start_date', models.DateTimeField(db_index=True)),
                ('spent', models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True)),
                ('conversions', models.IntegerField()),
                ('imps', models.IntegerField()),
                ('clicks', models.IntegerField()),
                ('cpc', models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True)),
                ('cpm', models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True)),
                ('cvr', models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True)),
                ('ctr', models.FloatField(blank=True, null=True)),
                ('imps_viewed', models.IntegerField(blank=True, null=True)),
                ('view_measured_imps', models.IntegerField(blank=True, null=True)),
                ('view_measurement_rate', models.FloatField(blank=True, null=True)),
                ('view_rate', models.FloatField(blank=True, null=True)),
                ('chart', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), null=True, size=None)),
                ('campaign', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Campaign', unique=True)),
            ],
            options={
                'db_table': 'ui_usual_campaigns_grid_data_last_21_days',
            },
        ),
        migrations.CreateModel(
            name='UIUsualCampaignsGridDataLast3Days',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('evaluation_date', models.DateTimeField(db_index=True)),
                ('window_start_date', models.DateTimeField(db_index=True)),
                ('spent', models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True)),
                ('conversions', models.IntegerField()),
                ('imps', models.IntegerField()),
                ('clicks', models.IntegerField()),
                ('cpc', models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True)),
                ('cpm', models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True)),
                ('cvr', models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True)),
                ('ctr', models.FloatField(blank=True, null=True)),
                ('imps_viewed', models.IntegerField(blank=True, null=True)),
                ('view_measured_imps', models.IntegerField(blank=True, null=True)),
                ('view_measurement_rate', models.FloatField(blank=True, null=True)),
                ('view_rate', models.FloatField(blank=True, null=True)),
                ('chart', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), null=True, size=None)),
                ('campaign', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Campaign', unique=True)),
            ],
            options={
                'db_table': 'ui_usual_campaigns_grid_data_last_3_days',
            },
        ),
        migrations.CreateModel(
            name='UIUsualCampaignsGridDataLast7Days',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('evaluation_date', models.DateTimeField(db_index=True)),
                ('window_start_date', models.DateTimeField(db_index=True)),
                ('spent', models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True)),
                ('conversions', models.IntegerField()),
                ('imps', models.IntegerField()),
                ('clicks', models.IntegerField()),
                ('cpc', models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True)),
                ('cpm', models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True)),
                ('cvr', models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True)),
                ('ctr', models.FloatField(blank=True, null=True)),
                ('imps_viewed', models.IntegerField(blank=True, null=True)),
                ('view_measured_imps', models.IntegerField(blank=True, null=True)),
                ('view_measurement_rate', models.FloatField(blank=True, null=True)),
                ('view_rate', models.FloatField(blank=True, null=True)),
                ('chart', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), null=True, size=None)),
                ('campaign', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Campaign', unique=True)),
            ],
            options={
                'db_table': 'ui_usual_campaigns_grid_data_last_7_days',
            },
        ),
        migrations.CreateModel(
            name='UIUsualCampaignsGridDataLast90Days',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('evaluation_date', models.DateTimeField(db_index=True)),
                ('window_start_date', models.DateTimeField(db_index=True)),
                ('spent', models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True)),
                ('conversions', models.IntegerField()),
                ('imps', models.IntegerField()),
                ('clicks', models.IntegerField()),
                ('cpc', models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True)),
                ('cpm', models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True)),
                ('cvr', models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True)),
                ('ctr', models.FloatField(blank=True, null=True)),
                ('imps_viewed', models.IntegerField(blank=True, null=True)),
                ('view_measured_imps', models.IntegerField(blank=True, null=True)),
                ('view_measurement_rate', models.FloatField(blank=True, null=True)),
                ('view_rate', models.FloatField(blank=True, null=True)),
                ('chart', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), null=True, size=None)),
                ('campaign', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Campaign', unique=True)),
            ],
            options={
                'db_table': 'ui_usual_campaigns_grid_data_last_90_days',
            },
        ),
        migrations.CreateModel(
            name='UIUsualCampaignsGridDataLastMonth',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('evaluation_date', models.DateTimeField(db_index=True)),
                ('window_start_date', models.DateTimeField(db_index=True)),
                ('spent', models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True)),
                ('conversions', models.IntegerField()),
                ('imps', models.IntegerField()),
                ('clicks', models.IntegerField()),
                ('cpc', models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True)),
                ('cpm', models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True)),
                ('cvr', models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True)),
                ('ctr', models.FloatField(blank=True, null=True)),
                ('imps_viewed', models.IntegerField(blank=True, null=True)),
                ('view_measured_imps', models.IntegerField(blank=True, null=True)),
                ('view_measurement_rate', models.FloatField(blank=True, null=True)),
                ('view_rate', models.FloatField(blank=True, null=True)),
                ('chart', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), null=True, size=None)),
                ('campaign', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Campaign', unique=True)),
            ],
            options={
                'db_table': 'ui_usual_campaigns_grid_data_last_month',
            },
        ),
        migrations.CreateModel(
            name='UIUsualCampaignsGridDataYesterday',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('evaluation_date', models.DateTimeField(db_index=True)),
                ('window_start_date', models.DateTimeField(db_index=True)),
                ('spent', models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True)),
                ('conversions', models.IntegerField()),
                ('imps', models.IntegerField()),
                ('clicks', models.IntegerField()),
                ('cpc', models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True)),
                ('cpm', models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True)),
                ('cvr', models.DecimalField(blank=True, decimal_places=10, max_digits=35, null=True)),
                ('ctr', models.FloatField(blank=True, null=True)),
                ('imps_viewed', models.IntegerField(blank=True, null=True)),
                ('view_measured_imps', models.IntegerField(blank=True, null=True)),
                ('view_measurement_rate', models.FloatField(blank=True, null=True)),
                ('view_rate', models.FloatField(blank=True, null=True)),
                ('chart', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), null=True, size=None)),
                ('campaign', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Campaign', unique=True)),
            ],
            options={
                'db_table': 'ui_usual_campaigns_grid_data_yesterday',
            },
        ),
        migrations.CreateModel(
            name='UIVideoCampaignsGridDataAll',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('evaluation_date', models.DateTimeField(db_index=True)),
                ('spent', models.DecimalField(decimal_places=10, max_digits=35, null=True)),
                ('imps', models.IntegerField(null=True)),
                ('ad_starts', models.IntegerField(null=True)),
                ('cpm', models.DecimalField(decimal_places=10, max_digits=35, null=True)),
                ('fill_rate', models.DecimalField(decimal_places=10, max_digits=35, null=True)),
                ('profit_loss', models.DecimalField(decimal_places=10, max_digits=35, null=True)),
                ('delta_fill_rate', models.DecimalField(decimal_places=10, max_digits=35, null=True)),
                ('delta_profit_loss', models.DecimalField(decimal_places=10, max_digits=35, null=True)),
                ('chart', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), null=True, size=None)),
                ('campaign', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Campaign', unique=True)),
            ],
            options={
                'db_table': 'ui_video_campaigns_grid_data_all',
            },
        ),
        migrations.CreateModel(
            name='UIVideoCampaignsGridDataCurMonth',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('evaluation_date', models.DateTimeField(db_index=True)),
                ('window_start_date', models.DateTimeField(db_index=True)),
                ('spent', models.DecimalField(decimal_places=10, max_digits=35, null=True)),
                ('imps', models.IntegerField(null=True)),
                ('ad_starts', models.IntegerField(null=True)),
                ('cpm', models.DecimalField(decimal_places=10, max_digits=35, null=True)),
                ('fill_rate', models.DecimalField(decimal_places=10, max_digits=35, null=True)),
                ('profit_loss', models.DecimalField(decimal_places=10, max_digits=35, null=True)),
                ('delta_fill_rate', models.DecimalField(decimal_places=10, max_digits=35, null=True)),
                ('delta_profit_loss', models.DecimalField(decimal_places=10, max_digits=35, null=True)),
                ('chart', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), null=True, size=None)),
                ('campaign', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Campaign', unique=True)),
            ],
            options={
                'db_table': 'ui_video_campaigns_grid_data_cur_month',
            },
        ),
        migrations.CreateModel(
            name='UIVideoCampaignsGridDataLast14Days',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('evaluation_date', models.DateTimeField(db_index=True)),
                ('window_start_date', models.DateTimeField(db_index=True)),
                ('spent', models.DecimalField(decimal_places=10, max_digits=35, null=True)),
                ('imps', models.IntegerField(null=True)),
                ('ad_starts', models.IntegerField(null=True)),
                ('cpm', models.DecimalField(decimal_places=10, max_digits=35, null=True)),
                ('fill_rate', models.DecimalField(decimal_places=10, max_digits=35, null=True)),
                ('profit_loss', models.DecimalField(decimal_places=10, max_digits=35, null=True)),
                ('delta_fill_rate', models.DecimalField(decimal_places=10, max_digits=35, null=True)),
                ('delta_profit_loss', models.DecimalField(decimal_places=10, max_digits=35, null=True)),
                ('chart', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), null=True, size=None)),
                ('campaign', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Campaign', unique=True)),
            ],
            options={
                'db_table': 'ui_video_campaigns_grid_data_last_14_days',
            },
        ),
        migrations.CreateModel(
            name='UIVideoCampaignsGridDataLast21Days',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('evaluation_date', models.DateTimeField(db_index=True)),
                ('window_start_date', models.DateTimeField(db_index=True)),
                ('spent', models.DecimalField(decimal_places=10, max_digits=35, null=True)),
                ('imps', models.IntegerField(null=True)),
                ('ad_starts', models.IntegerField(null=True)),
                ('cpm', models.DecimalField(decimal_places=10, max_digits=35, null=True)),
                ('fill_rate', models.DecimalField(decimal_places=10, max_digits=35, null=True)),
                ('profit_loss', models.DecimalField(decimal_places=10, max_digits=35, null=True)),
                ('delta_fill_rate', models.DecimalField(decimal_places=10, max_digits=35, null=True)),
                ('delta_profit_loss', models.DecimalField(decimal_places=10, max_digits=35, null=True)),
                ('chart', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), null=True, size=None)),
                ('campaign', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Campaign', unique=True)),
            ],
            options={
                'db_table': 'ui_video_campaigns_grid_data_last_21_days',
            },
        ),
        migrations.CreateModel(
            name='UIVideoCampaignsGridDataLast3Days',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('evaluation_date', models.DateTimeField(db_index=True)),
                ('window_start_date', models.DateTimeField(db_index=True)),
                ('spent', models.DecimalField(decimal_places=10, max_digits=35, null=True)),
                ('imps', models.IntegerField(null=True)),
                ('ad_starts', models.IntegerField(null=True)),
                ('cpm', models.DecimalField(decimal_places=10, max_digits=35, null=True)),
                ('fill_rate', models.DecimalField(decimal_places=10, max_digits=35, null=True)),
                ('profit_loss', models.DecimalField(decimal_places=10, max_digits=35, null=True)),
                ('delta_fill_rate', models.DecimalField(decimal_places=10, max_digits=35, null=True)),
                ('delta_profit_loss', models.DecimalField(decimal_places=10, max_digits=35, null=True)),
                ('chart', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), null=True, size=None)),
                ('campaign', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Campaign', unique=True)),
            ],
            options={
                'db_table': 'ui_video_campaigns_grid_data_last_3_days',
            },
        ),
        migrations.CreateModel(
            name='UIVideoCampaignsGridDataLast7Days',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('evaluation_date', models.DateTimeField(db_index=True)),
                ('window_start_date', models.DateTimeField(db_index=True)),
                ('spent', models.DecimalField(decimal_places=10, max_digits=35, null=True)),
                ('imps', models.IntegerField(null=True)),
                ('ad_starts', models.IntegerField(null=True)),
                ('cpm', models.DecimalField(decimal_places=10, max_digits=35, null=True)),
                ('fill_rate', models.DecimalField(decimal_places=10, max_digits=35, null=True)),
                ('profit_loss', models.DecimalField(decimal_places=10, max_digits=35, null=True)),
                ('delta_fill_rate', models.DecimalField(decimal_places=10, max_digits=35, null=True)),
                ('delta_profit_loss', models.DecimalField(decimal_places=10, max_digits=35, null=True)),
                ('chart', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), null=True, size=None)),
                ('campaign', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Campaign', unique=True)),
            ],
            options={
                'db_table': 'ui_video_campaigns_grid_data_last_7_days',
            },
        ),
        migrations.CreateModel(
            name='UIVideoCampaignsGridDataLast90Days',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('evaluation_date', models.DateTimeField(db_index=True)),
                ('window_start_date', models.DateTimeField(db_index=True)),
                ('spent', models.DecimalField(decimal_places=10, max_digits=35, null=True)),
                ('imps', models.IntegerField(null=True)),
                ('ad_starts', models.IntegerField(null=True)),
                ('cpm', models.DecimalField(decimal_places=10, max_digits=35, null=True)),
                ('fill_rate', models.DecimalField(decimal_places=10, max_digits=35, null=True)),
                ('profit_loss', models.DecimalField(decimal_places=10, max_digits=35, null=True)),
                ('delta_fill_rate', models.DecimalField(decimal_places=10, max_digits=35, null=True)),
                ('delta_profit_loss', models.DecimalField(decimal_places=10, max_digits=35, null=True)),
                ('chart', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), null=True, size=None)),
                ('campaign', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Campaign', unique=True)),
            ],
            options={
                'db_table': 'ui_video_campaigns_grid_data_last_90_days',
            },
        ),
        migrations.CreateModel(
            name='UIVideoCampaignsGridDataLastMonth',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('evaluation_date', models.DateTimeField(db_index=True)),
                ('window_start_date', models.DateTimeField(db_index=True)),
                ('spent', models.DecimalField(decimal_places=10, max_digits=35, null=True)),
                ('imps', models.IntegerField(null=True)),
                ('ad_starts', models.IntegerField(null=True)),
                ('cpm', models.DecimalField(decimal_places=10, max_digits=35, null=True)),
                ('fill_rate', models.DecimalField(decimal_places=10, max_digits=35, null=True)),
                ('profit_loss', models.DecimalField(decimal_places=10, max_digits=35, null=True)),
                ('delta_fill_rate', models.DecimalField(decimal_places=10, max_digits=35, null=True)),
                ('delta_profit_loss', models.DecimalField(decimal_places=10, max_digits=35, null=True)),
                ('chart', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), null=True, size=None)),
                ('campaign', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Campaign', unique=True)),
            ],
            options={
                'db_table': 'ui_video_campaigns_grid_data_last_month',
            },
        ),
        migrations.CreateModel(
            name='UIVideoCampaignsGridDataYesterday',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('evaluation_date', models.DateTimeField(db_index=True)),
                ('window_start_date', models.DateTimeField(db_index=True)),
                ('spent', models.DecimalField(decimal_places=10, max_digits=35, null=True)),
                ('imps', models.IntegerField(null=True)),
                ('ad_starts', models.IntegerField(null=True)),
                ('cpm', models.DecimalField(decimal_places=10, max_digits=35, null=True)),
                ('fill_rate', models.DecimalField(decimal_places=10, max_digits=35, null=True)),
                ('profit_loss', models.DecimalField(decimal_places=10, max_digits=35, null=True)),
                ('delta_fill_rate', models.DecimalField(decimal_places=10, max_digits=35, null=True)),
                ('delta_profit_loss', models.DecimalField(decimal_places=10, max_digits=35, null=True)),
                ('chart', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), null=True, size=None)),
                ('campaign', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Campaign', unique=True)),
            ],
            options={
                'db_table': 'ui_video_campaigns_grid_data_yesterday',
            },
        ),

        migrations.RunSQL(
            'ALTER TABLE ui_usual_campaigns_grid_data_yesterday ALTER COLUMN evaluation_date TYPE timestamp without time zone;'),
        migrations.RunSQL(
            'ALTER TABLE ui_usual_campaigns_grid_data_yesterday ALTER COLUMN window_start_date TYPE timestamp without time zone;'),

        migrations.RunSQL(
            'ALTER TABLE ui_usual_campaigns_grid_data_last_3_days ALTER COLUMN evaluation_date TYPE timestamp without time zone;'),
        migrations.RunSQL(
            'ALTER TABLE ui_usual_campaigns_grid_data_last_3_days ALTER COLUMN window_start_date TYPE timestamp without time zone;'),

        migrations.RunSQL(
            'ALTER TABLE ui_usual_campaigns_grid_data_last_7_days ALTER COLUMN evaluation_date TYPE timestamp without time zone;'),
        migrations.RunSQL(
            'ALTER TABLE ui_usual_campaigns_grid_data_last_7_days ALTER COLUMN window_start_date TYPE timestamp without time zone;'),

        migrations.RunSQL(
            'ALTER TABLE ui_usual_campaigns_grid_data_last_14_days ALTER COLUMN evaluation_date TYPE timestamp without time zone;'),
        migrations.RunSQL(
            'ALTER TABLE ui_usual_campaigns_grid_data_last_14_days ALTER COLUMN window_start_date TYPE timestamp without time zone;'),

        migrations.RunSQL(
            'ALTER TABLE ui_usual_campaigns_grid_data_last_21_days ALTER COLUMN evaluation_date TYPE timestamp without time zone;'),
        migrations.RunSQL(
            'ALTER TABLE ui_usual_campaigns_grid_data_last_21_days ALTER COLUMN window_start_date TYPE timestamp without time zone;'),

        migrations.RunSQL(
            'ALTER TABLE ui_usual_campaigns_grid_data_cur_month ALTER COLUMN evaluation_date TYPE timestamp without time zone;'),
        migrations.RunSQL(
            'ALTER TABLE ui_usual_campaigns_grid_data_cur_month ALTER COLUMN window_start_date TYPE timestamp without time zone;'),

        migrations.RunSQL(
            'ALTER TABLE ui_usual_campaigns_grid_data_last_month ALTER COLUMN evaluation_date TYPE timestamp without time zone;'),
        migrations.RunSQL(
            'ALTER TABLE ui_usual_campaigns_grid_data_last_month ALTER COLUMN window_start_date TYPE timestamp without time zone;'),

        migrations.RunSQL(
            'ALTER TABLE ui_usual_campaigns_grid_data_last_90_days ALTER COLUMN evaluation_date TYPE timestamp without time zone;'),
        migrations.RunSQL(
            'ALTER TABLE ui_usual_campaigns_grid_data_last_90_days ALTER COLUMN window_start_date TYPE timestamp without time zone;'),

        migrations.RunSQL(
            'ALTER TABLE ui_usual_campaigns_grid_data_all ALTER COLUMN evaluation_date TYPE timestamp without time zone;'),


        migrations.RunSQL(
            'ALTER TABLE ui_video_campaigns_grid_data_yesterday ALTER COLUMN evaluation_date TYPE timestamp without time zone;'),
        migrations.RunSQL(
            'ALTER TABLE ui_video_campaigns_grid_data_yesterday ALTER COLUMN window_start_date TYPE timestamp without time zone;'),

        migrations.RunSQL(
            'ALTER TABLE ui_video_campaigns_grid_data_last_3_days ALTER COLUMN evaluation_date TYPE timestamp without time zone;'),
        migrations.RunSQL(
            'ALTER TABLE ui_video_campaigns_grid_data_last_3_days ALTER COLUMN window_start_date TYPE timestamp without time zone;'),

        migrations.RunSQL(
            'ALTER TABLE ui_video_campaigns_grid_data_last_7_days ALTER COLUMN evaluation_date TYPE timestamp without time zone;'),
        migrations.RunSQL(
            'ALTER TABLE ui_video_campaigns_grid_data_last_7_days ALTER COLUMN window_start_date TYPE timestamp without time zone;'),

        migrations.RunSQL(
            'ALTER TABLE ui_video_campaigns_grid_data_last_14_days ALTER COLUMN evaluation_date TYPE timestamp without time zone;'),
        migrations.RunSQL(
            'ALTER TABLE ui_video_campaigns_grid_data_last_14_days ALTER COLUMN window_start_date TYPE timestamp without time zone;'),

        migrations.RunSQL(
            'ALTER TABLE ui_video_campaigns_grid_data_last_21_days ALTER COLUMN evaluation_date TYPE timestamp without time zone;'),
        migrations.RunSQL(
            'ALTER TABLE ui_video_campaigns_grid_data_last_21_days ALTER COLUMN window_start_date TYPE timestamp without time zone;'),

        migrations.RunSQL(
            'ALTER TABLE ui_video_campaigns_grid_data_cur_month ALTER COLUMN evaluation_date TYPE timestamp without time zone;'),
        migrations.RunSQL(
            'ALTER TABLE ui_video_campaigns_grid_data_cur_month ALTER COLUMN window_start_date TYPE timestamp without time zone;'),

        migrations.RunSQL(
            'ALTER TABLE ui_video_campaigns_grid_data_last_month ALTER COLUMN evaluation_date TYPE timestamp without time zone;'),
        migrations.RunSQL(
            'ALTER TABLE ui_video_campaigns_grid_data_last_month ALTER COLUMN window_start_date TYPE timestamp without time zone;'),

        migrations.RunSQL(
            'ALTER TABLE ui_video_campaigns_grid_data_last_90_days ALTER COLUMN evaluation_date TYPE timestamp without time zone;'),
        migrations.RunSQL(
            'ALTER TABLE ui_video_campaigns_grid_data_last_90_days ALTER COLUMN window_start_date TYPE timestamp without time zone;'),

        migrations.RunSQL(
            'ALTER TABLE ui_video_campaigns_grid_data_all ALTER COLUMN evaluation_date TYPE timestamp without time zone;'),
    ]
