# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-19 23:31
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0142_uiusualcampaignsgriddataall_uiusualcampaignsgriddatacurmonth_uiusualcampaignsgriddatalast14days_uius'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uiusualcampaignsgriddataall',
            name='chart',
        ),
        migrations.RemoveField(
            model_name='uiusualcampaignsgriddatacurmonth',
            name='chart',
        ),
        migrations.RemoveField(
            model_name='uiusualcampaignsgriddatalast14days',
            name='chart',
        ),
        migrations.RemoveField(
            model_name='uiusualcampaignsgriddatalast21days',
            name='chart',
        ),
        migrations.RemoveField(
            model_name='uiusualcampaignsgriddatalast3days',
            name='chart',
        ),
        migrations.RemoveField(
            model_name='uiusualcampaignsgriddatalast7days',
            name='chart',
        ),
        migrations.RemoveField(
            model_name='uiusualcampaignsgriddatalast90days',
            name='chart',
        ),
        migrations.RemoveField(
            model_name='uiusualcampaignsgriddatalastmonth',
            name='chart',
        ),
        migrations.RemoveField(
            model_name='uiusualcampaignsgriddatayesterday',
            name='chart',
        ),
        migrations.RemoveField(
            model_name='uivideocampaignsgriddataall',
            name='chart',
        ),
        migrations.RemoveField(
            model_name='uivideocampaignsgriddatacurmonth',
            name='chart',
        ),
        migrations.RemoveField(
            model_name='uivideocampaignsgriddatalast14days',
            name='chart',
        ),
        migrations.RemoveField(
            model_name='uivideocampaignsgriddatalast21days',
            name='chart',
        ),
        migrations.RemoveField(
            model_name='uivideocampaignsgriddatalast3days',
            name='chart',
        ),
        migrations.RemoveField(
            model_name='uivideocampaignsgriddatalast7days',
            name='chart',
        ),
        migrations.RemoveField(
            model_name='uivideocampaignsgriddatalast90days',
            name='chart',
        ),
        migrations.RemoveField(
            model_name='uivideocampaignsgriddatalastmonth',
            name='chart',
        ),
        migrations.RemoveField(
            model_name='uivideocampaignsgriddatayesterday',
            name='chart',
        ),
        migrations.AddField(
            model_name='uiusualcampaignsgriddataall',
            name='day_chart',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[], null=True),
        ),
        migrations.AddField(
            model_name='uiusualcampaignsgriddatacurmonth',
            name='day_chart',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[], null=True),
        ),
        migrations.AddField(
            model_name='uiusualcampaignsgriddatalast14days',
            name='day_chart',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[], null=True),
        ),
        migrations.AddField(
            model_name='uiusualcampaignsgriddatalast21days',
            name='day_chart',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[], null=True),
        ),
        migrations.AddField(
            model_name='uiusualcampaignsgriddatalast3days',
            name='day_chart',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[], null=True),
        ),
        migrations.AddField(
            model_name='uiusualcampaignsgriddatalast7days',
            name='day_chart',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[], null=True),
        ),
        migrations.AddField(
            model_name='uiusualcampaignsgriddatalast90days',
            name='day_chart',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[], null=True),
        ),
        migrations.AddField(
            model_name='uiusualcampaignsgriddatalastmonth',
            name='day_chart',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[], null=True),
        ),
        migrations.AddField(
            model_name='uiusualcampaignsgriddatayesterday',
            name='day_chart',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[], null=True),
        ),
        migrations.AddField(
            model_name='uivideocampaignsgriddataall',
            name='day_chart',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[], null=True),
        ),
        migrations.AddField(
            model_name='uivideocampaignsgriddatacurmonth',
            name='day_chart',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[], null=True),
        ),
        migrations.AddField(
            model_name='uivideocampaignsgriddatalast14days',
            name='day_chart',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[], null=True),
        ),
        migrations.AddField(
            model_name='uivideocampaignsgriddatalast21days',
            name='day_chart',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[], null=True),
        ),
        migrations.AddField(
            model_name='uivideocampaignsgriddatalast3days',
            name='day_chart',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[], null=True),
        ),
        migrations.AddField(
            model_name='uivideocampaignsgriddatalast7days',
            name='day_chart',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[], null=True),
        ),
        migrations.AddField(
            model_name='uivideocampaignsgriddatalast90days',
            name='day_chart',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[], null=True),
        ),
        migrations.AddField(
            model_name='uivideocampaignsgriddatalastmonth',
            name='day_chart',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[], null=True),
        ),
        migrations.AddField(
            model_name='uivideocampaignsgriddatayesterday',
            name='day_chart',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[], null=True),
        ),
    ]
