# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-24 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0144_uiusualplacementsgriddataall_uiusualplacementsgriddatacurmonth_uiusualplacementsgriddatalast14days_u'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertiser',
            name='grid_data_source',
            field=models.TextField(blank=True, db_index=True, default=b'report', null=True),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='ad_type',
            field=models.TextField(blank=True, db_index=True, default=b'usualAds', null=True),
        ),

        migrations.RunSQL(
            "UPDATE advertiser SET ad_type='usualAds' WHERE ad_type is null;"),
        migrations.RunSQL(
            "UPDATE advertiser SET grid_data_source='report' WHERE grid_data_source is null;"),
    ]
