# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-27 07:59
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0146_auto_20170224_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='UIUsualPlacementsGraph',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.TextField(db_index=True)),
                ('evaluation_date', models.DateTimeField(db_index=True)),
                ('window_start_date', models.DateTimeField(db_index=True)),
                ('day_chart', django.contrib.postgres.fields.jsonb.JSONField(default=[], null=True)),
                ('campaign', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Campaign')),
            ],
            options={
                'db_table': 'ui_usual_placements_graph',
            },
        ),
        migrations.AlterUniqueTogether(
            name='uiusualplacementsgraph',
            unique_together=set([('campaign', 'type')]),
        ),

        migrations.RunSQL(
            'ALTER TABLE ui_usual_advertisers_graph ALTER COLUMN evaluation_date TYPE timestamp without time zone;'),
        migrations.RunSQL(
            'ALTER TABLE ui_usual_advertisers_graph ALTER COLUMN window_start_date TYPE timestamp without time zone;'),

        migrations.RunSQL(
            'ALTER TABLE ui_usual_placements_graph ALTER COLUMN evaluation_date TYPE timestamp without time zone;'),
        migrations.RunSQL(
            'ALTER TABLE ui_usual_placements_graph ALTER COLUMN window_start_date TYPE timestamp without time zone;'),
    ]
