# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-28 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0147_auto_20170227_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='uiusualplacementsgriddataall',
            name='campaign',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Campaign'),
        ),
        migrations.AddField(
            model_name='uiusualplacementsgriddatacurmonth',
            name='campaign',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Campaign'),
        ),
        migrations.AddField(
            model_name='uiusualplacementsgriddatalast14days',
            name='campaign',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Campaign'),
        ),
        migrations.AddField(
            model_name='uiusualplacementsgriddatalast21days',
            name='campaign',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Campaign'),
        ),
        migrations.AddField(
            model_name='uiusualplacementsgriddatalast3days',
            name='campaign',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Campaign'),
        ),
        migrations.AddField(
            model_name='uiusualplacementsgriddatalast7days',
            name='campaign',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Campaign'),
        ),
        migrations.AddField(
            model_name='uiusualplacementsgriddatalast90days',
            name='campaign',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Campaign'),
        ),
        migrations.AddField(
            model_name='uiusualplacementsgriddatalastmonth',
            name='campaign',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Campaign'),
        ),
        migrations.AddField(
            model_name='uiusualplacementsgriddatayesterday',
            name='campaign',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Campaign'),
        ),
        migrations.AlterField(
            model_name='uiusualplacementsgriddataall',
            name='placement',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Placement'),
        ),
        migrations.AlterField(
            model_name='uiusualplacementsgriddatacurmonth',
            name='placement',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Placement'),
        ),
        migrations.AlterField(
            model_name='uiusualplacementsgriddatalast14days',
            name='placement',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Placement'),
        ),
        migrations.AlterField(
            model_name='uiusualplacementsgriddatalast21days',
            name='placement',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Placement'),
        ),
        migrations.AlterField(
            model_name='uiusualplacementsgriddatalast3days',
            name='placement',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Placement'),
        ),
        migrations.AlterField(
            model_name='uiusualplacementsgriddatalast7days',
            name='placement',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Placement'),
        ),
        migrations.AlterField(
            model_name='uiusualplacementsgriddatalast90days',
            name='placement',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Placement'),
        ),
        migrations.AlterField(
            model_name='uiusualplacementsgriddatalastmonth',
            name='placement',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Placement'),
        ),
        migrations.AlterField(
            model_name='uiusualplacementsgriddatayesterday',
            name='placement',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Placement'),
        ),
        migrations.AlterUniqueTogether(
            name='uiusualplacementsgriddataall',
            unique_together=set([('campaign', 'placement')]),
        ),
        migrations.AlterUniqueTogether(
            name='uiusualplacementsgriddatacurmonth',
            unique_together=set([('campaign', 'placement')]),
        ),
        migrations.AlterUniqueTogether(
            name='uiusualplacementsgriddatalast14days',
            unique_together=set([('campaign', 'placement')]),
        ),
        migrations.AlterUniqueTogether(
            name='uiusualplacementsgriddatalast21days',
            unique_together=set([('campaign', 'placement')]),
        ),
        migrations.AlterUniqueTogether(
            name='uiusualplacementsgriddatalast3days',
            unique_together=set([('campaign', 'placement')]),
        ),
        migrations.AlterUniqueTogether(
            name='uiusualplacementsgriddatalast7days',
            unique_together=set([('campaign', 'placement')]),
        ),
        migrations.AlterUniqueTogether(
            name='uiusualplacementsgriddatalast90days',
            unique_together=set([('campaign', 'placement')]),
        ),
        migrations.AlterUniqueTogether(
            name='uiusualplacementsgriddatalastmonth',
            unique_together=set([('campaign', 'placement')]),
        ),
        migrations.AlterUniqueTogether(
            name='uiusualplacementsgriddatayesterday',
            unique_together=set([('campaign', 'placement')]),
        ),
    ]
