# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-07 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0150_auto_20170305_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementsAdditionalNames',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('publisher_name', models.TextField(blank=True, null=True)),
                ('seller_member_name', models.TextField(blank=True, null=True)),
                ('placement', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Placement', unique=True)),
            ],
            options={
                'db_table': 'placements_additional_names',
            },
        ),

        migrations.RunSQL("delete from placements_additional_names"),

        migrations.RunSQL("""
insert into placements_additional_names as ut (
    placement_id,
    publisher_name,
    seller_member_name)
  select
    distinct on (t.placement_id)
    t.placement_id,
    t.publisher_name,
    t.seller_member_name
  from
    network_analytics_report_by_placement t;
                """),
    ]
