# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-22 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0160_tracker_cpm_fix_second_encounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertiser',
            name='rules_type',
            field=models.TextField(blank=True, db_index=True, default=b'report', null=True),
        ),
    ]
