# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-23 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0161_advertiser_rules_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlclusterscentroidskmeans',
            name='adv_type',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='mlnormalizationdata',
            name='adv_type',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='mlplacementdailyfeatures',
            name='adv_type',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='mlplacementsclusterskmeans',
            name='adv_type',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='mlclusterscentroidskmeans',
            unique_together=set([('cluster', 'day', 'test_number', 'adv_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='mlnormalizationdata',
            unique_together=set([('test_number', 'day', 'adv_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='mlplacementdailyfeatures',
            unique_together=set([('placement', 'day', 'adv_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='mlplacementsclusterskmeans',
            unique_together=set([('placement', 'day', 'test_number', 'adv_type')]),
        ),

        migrations.RunSQL("""update advertiser set ad_type='ecommerceAd' where ad_type='usualAds';"""),
    ]
