# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-28 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0162_rules_type_report_and_tracker'),
        ('rtb', '0162_auto_20170323_1613'),
    ]

    operations = [
    ]
