# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-28 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0163_auto_20170328_0815'),
        ('rtb', '0163_merge_20170328_1359'),
    ]

    operations = [
    ]
