# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-07 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0169_auto_20170403_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertiser',
            name='token',
            field=models.TextField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
