# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-15 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtb', '0170_advertiser_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='creative_format_action',
            field=models.TextField(blank=True, null=True),
        ),
    ]
