# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-07 11:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rtb', '0170_advertiser_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainList',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('advertiser', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rtb.Advertiser')),
            ],
            options={
                'db_table': 'domain_list',
            },
        ),
    ]
